import * as Dialog from '@radix-ui/react-dialog'
import { useState } from 'react'
import { Download,FileSpreadsheet,LoaderCircle,Upload,X } from 'lucide-react'
import { api,queryClient } from '../api'
import { Button } from './ui/button'

export function AssetImport({onClose}:{onClose:()=>void}){
 const [file,setFile]=useState<File|null>(null);const [pending,setPending]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<number|null>(null)
 const submit=async()=>{if(!file)return;setPending(true);setError('');try{const form=new FormData();form.append('file',file);const data=await api('/assets/import',{method:'POST',body:form});setResult(data.created);queryClient.invalidateQueries()}catch(e){setError((e as Error).message)}finally{setPending(false)}}
 return <Dialog.Root open onOpenChange={open=>{if(!open&&!pending)onClose()}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="import-dialog"><div className="editor-heading"><div><span className="eyebrow">DANH SÁCH TÀI SẢN</span><Dialog.Title>Nhập tài sản từ Excel</Dialog.Title><Dialog.Description>Mỗi dòng nhập một tài sản có số sê-ri vào kho và ghi nhận phiếu nhập.</Dialog.Description></div><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="Đóng"><X size={20}/></Button></Dialog.Close></div>{result!==null?<div className="import-success"><FileSpreadsheet size={38}/><h3>{result} tài sản đã được nhập</h3><p>Tài sản và phiếu nhập kho đã được lưu trong hệ thống.</p><Button onClick={onClose}>Hoàn tất</Button></div>:<><div className="import-guide"><strong>Trước khi nhập</strong><ol><li>Tải biểu mẫu Excel.</li><li>Sử dụng tên loại tài sản và mã kho đã cấu hình.</li><li>Nhập mã kho tiếp nhận, ví dụ <code>WH-Q7</code>.</li></ol><a className="button button-outline" href="/api/assets/import/template"><Download size={16}/>Tải biểu mẫu</a></div><label className="import-drop"><Upload size={28}/><strong>{file?.name||'Chọn tệp XLSX'}</strong><span>Tối đa 5 MB. Hủy toàn bộ lượt nhập nếu có dòng không hợp lệ.</span><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{error&&<div className="error">{error}</div>}<footer className="editor-footer"><Button variant="outline" onClick={onClose}>Hủy</Button><Button disabled={!file||pending} onClick={submit}>{pending?<LoaderCircle className="spin" size={16}/>:<Upload size={16}/>}Nhập tài sản</Button></footer></>}</Dialog.Content></Dialog.Portal></Dialog.Root>
}
