import { vi,eventLabels,statusLabels } from '../i18n'
import { LocationPath } from './LocationPath'
import { useMemo, useState } from 'react'
import { useReactTable,getCoreRowModel,getSortedRowModel,getPaginationRowModel,flexRender,type SortingState,type VisibilityState } from '@tanstack/react-table'
import { ArrowUpDown,Columns3,ChevronLeft,ChevronRight,Search,Inbox } from 'lucide-react'
import { label,formatDate,type Row } from '../api'
import { Button } from './ui/button'
export function Badge({children}:{children:any}){const value=String(children||'');const style=/critical|broken|overdue|repair|conflict|lost/i.test(value)?'red':/đang bảo trì/i.test(value)?'amber':/sẵn sàng|đang sử dụng/i.test(value)?'green':/progress|assigned|used|published|completed|resolved|available|in use|^up$/i.test(value)?'green':/waiting|high|reserved|maintenance/i.test(value)?'amber':'slate';return <span className={'badge '+style}><i/>{eventLabels[value]||statusLabels[value]||vi(value)||'—'}</span>}
export function Cell({value,name}:{value:any,name:string}){if(name==='event_type'||name==='operation_type')return <>{eventLabels[String(value)]||String(value||'—')}</>;if(['group','kind','action','mode_label','category_label'].includes(name))return <>{vi(String(value||'—'))}</>;if(name==='transaction_type')return <>{vi(String(value||'—'))}</>;if(name==='photo_url')return value?<img className="asset-table-photo" src={value} alt="Tài sản" loading="lazy"/>:<span className="asset-table-photo empty"><Inbox size={14}/></span>;if(value===null||value===undefined||value==='')return <span className="muted">—</span>;if(['location_label','from_location_label','recipient_location_label'].includes(name))return <LocationPath value={String(value)}/>;if(typeof value==='boolean')return <span className={'bool '+(value?'yes':'')}>{value?'Bật':'Tắt'}</span>;if(name.includes('status')||name.includes('priority')||name==='role')return <Badge>{value}</Badge>;if(name.endsWith('_at')||['expected_return','transaction_date','operation_date','since','location_since','current_assignment_since'].includes(name))return <>{formatDate(value)}</>;if(['received_date','handover_date'].includes(name))return <>{new Date(value+'T00:00:00').toLocaleDateString('vi-VN',{day:'2-digit',month:'short',year:'numeric'})}</>;if(typeof value==='object')return <span className="json-cell" title={JSON.stringify(value,null,2)}>{JSON.stringify(value)}</span>;return <span className={['code','number','address','mac','cidr'].includes(name)?'mono':''}>{String(value)}</span>}
export function DataTable({rows,columns,onRow,q='',setQ,total,page=1,setPage,sorting,setSorting,toolbar,renderActions}:{rows:Row[],columns:string[],onRow?:(row:Row)=>void,q?:string,setQ?:(s:string)=>void,total?:number,page?:number,setPage?:(n:number)=>void,sorting?:SortingState,setSorting?:(s:SortingState)=>void,toolbar?:React.ReactNode,renderActions?:(row:Row)=>React.ReactNode}){
 const [localQ,setLocalQ]=useState('');const [localPage,setLocalPage]=useState(1);
 const searched=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes((setQ?q:localQ).toLowerCase())),[rows,setQ,q,localQ]);const effectivePage=setPage?page:localPage;const effectiveTotal=total??searched.length;const changePage=setPage||setLocalPage;
 const [localSorting,setLocalSorting]=useState<SortingState>([]);const [visibility,setVisibility]=useState<VisibilityState>({});const [showColumns,setShowColumns]=useState(false)
 const cols=useMemo(()=>[...columns.map(key=>({accessorKey:key,header:key==='photo_url'?'Ảnh':label(key.replace('_label','')),cell:({getValue}:any)=><Cell value={getValue()} name={key}/>})),...(renderActions?[{id:'actions',header:'Thao tác',enableSorting:false,cell:({row}:any)=><div onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}>{renderActions(row.original)}</div>}]:[])],[columns,renderActions])
 const table=useReactTable({data:setPage?rows:searched,columns:cols,state:{sorting:sorting||localSorting,columnVisibility:visibility,pagination:{pageIndex:effectivePage-1,pageSize:20}},onSortingChange:updater=>{const next=typeof updater==='function'?updater(sorting||localSorting):updater;setSorting?setSorting(next):setLocalSorting(next)},onColumnVisibilityChange:setVisibility,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),manualSorting:!!setSorting,manualPagination:!!setPage,autoResetPageIndex:false,getPaginationRowModel:getPaginationRowModel()})
 return <div className="table-card"><div className="table-toolbar"><div className="input-icon"><Search size={16}/><input aria-label="Tìm trong bảng" placeholder="Tìm bản ghi…" value={setQ?q:localQ} onChange={e=>{setQ?setQ(e.target.value):setLocalQ(e.target.value);setLocalPage(1)}}/></div>{toolbar}<div className="column-menu"><Button variant="outline" size="sm" aria-expanded={showColumns} onClick={()=>setShowColumns(!showColumns)}><Columns3 size={15}/>Cột hiển thị</Button>{showColumns&&<div className="popover">{table.getAllLeafColumns().map(c=><label key={c.id}><input type="checkbox" checked={c.getIsVisible()} onChange={c.getToggleVisibilityHandler()}/>{label(c.id.replace('_label',''))}</label>)}</div>}</div></div><div className="table-scroll"><table><thead>{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id}><button onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}<ArrowUpDown size={12}/></button></th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id} className={onRow?'clickable':''} onClick={()=>onRow?.(r.original)} tabIndex={onRow?0:undefined} onKeyDown={e=>{if(e.key==='Enter'&&onRow){e.preventDefault();onRow(r.original)}}}>{r.getVisibleCells().map(c=><td key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table>{!searched.length&&<div className="empty"><Inbox size={32}/><h3>Không tìm thấy bản ghi</h3><p>Thử thay đổi điều kiện tìm kiếm hoặc tạo bản ghi mới.</p></div>}</div><div className="table-footer"><span>{`${effectiveTotal?((effectivePage-1)*20+1):0}–${Math.min(effectivePage*20,effectiveTotal)} / ${effectiveTotal}`} bản ghi</span>{<div><Button variant="outline" size="sm" aria-label="Trang trước" disabled={effectivePage===1} onClick={()=>changePage(effectivePage-1)}><ChevronLeft size={14}/></Button><span>Trang {effectivePage}</span><Button variant="outline" size="sm" aria-label="Trang sau" disabled={effectivePage*20>=effectiveTotal} onClick={()=>changePage(effectivePage+1)}><ChevronRight size={14}/></Button></div>}</div></div>
}
