import { useMemo, useState } from 'react'
import { useReactTable,getCoreRowModel,getSortedRowModel,getPaginationRowModel,flexRender,type SortingState,type VisibilityState } from '@tanstack/react-table'
import { ArrowUpDown,Columns3,ChevronLeft,ChevronRight,Search,Inbox } from 'lucide-react'
import { label,formatDate,type Row } from '../api'
import { Button } from './ui/button'
export function Badge({children}:{children:any}){const value=String(children||'');const style=/critical|broken|overdue|repair|conflict|lost/i.test(value)?'red':/progress|assigned|used|published|completed|resolved|available|in use|^up$/i.test(value)?'green':/waiting|high|reserved|maintenance/i.test(value)?'amber':'slate';return <span className={'badge '+style}><i/>{value||'—'}</span>}
export function Cell({value,name}:{value:any,name:string}){if(value===null||value===undefined||value==='')return <span className="muted">—</span>;if(typeof value==='boolean')return <span className={'bool '+(value?'yes':'')}>{value?'Enabled':'Disabled'}</span>;if(name.includes('status')||name.includes('priority')||name==='role')return <Badge>{value}</Badge>;if(name.endsWith('_at')||['expected_return','purchase_date','warranty_expiry'].includes(name))return <>{formatDate(value)}</>;if(typeof value==='object')return <span className="json-cell" title={JSON.stringify(value,null,2)}>{JSON.stringify(value)}</span>;return <span className={['code','number','address','mac','cidr'].includes(name)?'mono':''}>{String(value)}</span>}
export function DataTable({rows,columns,onRow,q='',setQ,total,page=1,setPage,sorting,setSorting,toolbar}:{rows:Row[],columns:string[],onRow?:(row:Row)=>void,q?:string,setQ?:(s:string)=>void,total?:number,page?:number,setPage?:(n:number)=>void,sorting?:SortingState,setSorting?:(s:SortingState)=>void,toolbar?:React.ReactNode}){
 const [localQ,setLocalQ]=useState('');const [localPage,setLocalPage]=useState(1);
 const searched=rows.filter(r=>JSON.stringify(r).toLowerCase().includes((setQ?q:localQ).toLowerCase()));const effectivePage=setPage?page:localPage;const effectiveTotal=total??searched.length;const changePage=setPage||setLocalPage;
 const [localSorting,setLocalSorting]=useState<SortingState>([]);const [visibility,setVisibility]=useState<VisibilityState>({});const [showColumns,setShowColumns]=useState(false)
 const cols=useMemo(()=>columns.map(key=>({accessorKey:key,header:label(key.replace('_label','')),cell:({getValue}:any)=><Cell value={getValue()} name={key}/>})),[columns])
 const table=useReactTable({data:setPage?rows:searched,columns:cols,state:{sorting:sorting||localSorting,columnVisibility:visibility,pagination:{pageIndex:effectivePage-1,pageSize:20}},onSortingChange:updater=>{const next=typeof updater==='function'?updater(sorting||localSorting):updater;setSorting?setSorting(next):setLocalSorting(next)},onColumnVisibilityChange:setVisibility,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel(),manualSorting:!!setSorting,manualPagination:!!setPage,getPaginationRowModel:getPaginationRowModel()})
 return <div className="table-card"><div className="table-toolbar"><div className="input-icon"><Search size={16}/><input aria-label="Search table" placeholder="Search records…" value={setQ?q:localQ} onChange={e=>{setQ?setQ(e.target.value):setLocalQ(e.target.value);setLocalPage(1)}}/></div>{toolbar}<div className="column-menu"><Button variant="outline" size="sm" onClick={()=>setShowColumns(!showColumns)}><Columns3 size={15}/>Columns</Button>{showColumns&&<div className="popover">{table.getAllLeafColumns().map(c=><label key={c.id}><input type="checkbox" checked={c.getIsVisible()} onChange={c.getToggleVisibilityHandler()}/>{label(c.id.replace('_label',''))}</label>)}</div>}</div></div><div className="table-scroll"><table><thead>{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id}><button onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}<ArrowUpDown size={12}/></button></th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id} className={onRow?'clickable':''} onClick={()=>onRow?.(r.original)} tabIndex={onRow?0:undefined} onKeyDown={e=>{if(e.key==='Enter')onRow?.(r.original)}}>{r.getVisibleCells().map(c=><td key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table>{!searched.length&&<div className="empty"><Inbox size={32}/><h3>No records found</h3><p>Try changing your search or create a new record.</p></div>}</div><div className="table-footer"><span>{`${effectiveTotal?((effectivePage-1)*20+1):0}–${Math.min(effectivePage*20,effectiveTotal)} of ${effectiveTotal}`} records</span>{<div><Button variant="outline" size="sm" disabled={effectivePage===1} onClick={()=>changePage(effectivePage-1)}><ChevronLeft size={14}/></Button><span>Page {effectivePage}</span><Button variant="outline" size="sm" disabled={effectivePage*20>=effectiveTotal} onClick={()=>changePage(effectivePage+1)}><ChevronRight size={14}/></Button></div>}</div></div>
}
