import { Printer, Upload, Check, FileText } from 'lucide-react'
import { useState } from 'react'
import { type Row } from '../api'
import { Button } from './ui/button'

const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))
export function printHandover(data:Row){
 const popup=window.open('','_blank');if(!popup)return false
 const date=new Date(data.transaction_date),day=date.getDate(),month=date.getMonth()+1,year=date.getFullYear(),e=escape
 popup.document.write(`<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Biên bản bàn giao thiết bị</title><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font:14px 'Times New Roman',serif;color:#111;max-width:174mm;margin:20px auto;line-height:1.5}.top{display:flex;justify-content:space-between;align-items:flex-start}.top img{width:120px}.nation{text-align:center;font-weight:bold}.date{text-align:right;font-style:italic;margin:28px 0}h1{text-align:center;font-size:20px;margin:28px 0}p{margin:12px 0}table{border-collapse:collapse;width:100%;margin:22px 0;font-size:12px}th,td{border:1px solid #111;padding:8px 4px;text-align:center;overflow-wrap:anywhere}th{font-weight:bold}.signatures{display:flex;justify-content:space-around;text-align:center;margin-top:20px}.signature{width:45%}.signature small{display:block;font-style:italic}.signature p{margin-top:90px}.toolbar{font:14px sans-serif;background:#eff6ff;padding:12px;display:flex;justify-content:space-between;align-items:center}.toolbar button{padding:8px 18px;cursor:pointer}@media print{body{margin:0;max-width:none}.toolbar{display:none}}</style></head><body><div class="toolbar"><span>Biên bản bàn giao · A4</span><button onclick="window.print()">In biên bản</button></div><div class="top"><img src="${e(window.location.origin)}/handover-logo.png" alt="Eton"><div class="nation">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM<br>Độc lập – Tự do – Hạnh phúc</div></div><div class="date">${e(data.city)}, ngày ${day} tháng ${month} năm ${year}</div><h1>BIÊN BẢN BÀN GIAO THIẾT BỊ</h1><p><b>BÊN GIAO:</b> ${e(data.sender_name)}<br>Bộ phận/Chức vụ: ${e(data.sender_department)}</p><p><b>BÊN NHẬN:</b> ${e(data.recipient_name)}<br>Bộ phận/Chức vụ: ${e(data.recipient_department)}</p><p>Hôm nay ngày ${day}/${month}/${year} tại ${e(data.place)}, hai bên đã giao nhận đầy đủ các tài sản sau đây:</p><p>Mục đích sử dụng: ${e(data.purpose)}</p><table><thead><tr>${['TT','Mã tài sản','S/N','Model','Device name','Hiện trạng','SL','Ngày Giao'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody><tr>${[1,data.asset_code,data.serial||'—',data.model||'—',data.device_name||'—',data.condition,data.quantity,`${day}/${month}/${year}`].map(x=>`<td>${e(x)}</td>`).join('')}</tr></tbody></table><p>Bên nhận có trách nhiệm quản lý các tài sản trên theo quy định của Công ty CP Eton kể từ ngày nhận bàn giao. Nếu làm mất mát, hư hỏng phải chịu trách nhiệm bồi thường theo qui định của Công ty.</p><p>Biên bản này được lập thành 02 bản có giá trị như nhau, mỗi bên giữ 01 bản.</p><div class="date">${e(data.city)}, ngày ${day} tháng ${month} năm ${year}</div><div class="signatures"><div class="signature"><b>NGƯỜI GIAO</b><small>(Ký, ghi họ tên)</small><p>${e(data.sender_name)}</p></div><div class="signature"><b>NGƯỜI NHẬN</b><small>(Ký, ghi họ tên)</small><p>${e(data.recipient_name)}</p></div></div></body></html>`)
 popup.document.close();Promise.all([popup.document.fonts.ready,...Array.from(popup.document.images).map(img=>img.decode().catch(()=>undefined))]).then(()=>{if(!popup.closed){popup.focus();popup.print()}});return true
}
export function HandoverPanel({info,onChange,snapshot,file,onFile,pending,ready}:{info:Row,onChange:(key:string,value:string)=>void,snapshot:Row,file:File|null,onFile:(file:File|null)=>void,pending:boolean,ready:boolean}){
 const [error,setError]=useState('')
 return <section className="handover-panel"><header><div><h3><FileText size={17}/>Biên bản bàn giao</h3><p>In mẫu → Ký bàn giao → Tải bản đã ký để hoàn tất.</p></div><Button type="button" variant="outline" disabled={pending||!ready} onClick={()=>{setError(printHandover(snapshot)?'':'Trình duyệt đang chặn cửa sổ in. Cho phép mở popup để in biên bản.')}}><Printer size={16}/>In biên bản</Button></header><details><summary>Thông tin trên biên bản</summary><div className="form-grid quick-maintenance-grid">{[['sender_name','Người giao'],['sender_department','Bộ phận / Chức vụ người giao'],['recipient_department','Bộ phận / Chức vụ người nhận'],['place','Địa điểm bàn giao'],['purpose','Mục đích sử dụng'],['city','Tỉnh / Thành phố']].map(([key,label])=><label key={key}><span>{label}{key!=='recipient_department'&&<b> *</b>}</span><input required={key!=='recipient_department'} maxLength={key==='place'||key==='purpose'?500:key==='city'?100:150} disabled={pending} value={info[key]||''} onChange={event=>onChange(key,event.target.value)}/></label>)}</div></details><label className={'handover-upload'+(file?' attached':'')}><span>{file?<Check size={20}/>:<Upload size={20}/>}<span><strong>{file?file.name:'Tải biên bản bàn giao đã ký'}<b> *</b></strong><small>{file?'Đã đính kèm · Nhấn để chọn tệp khác':'PDF, JPG hoặc PNG · Tối đa 10 MB'}</small></span></span><input aria-label="Biên bản bàn giao đã ký" type="file" accept=".pdf,.jpg,.jpeg,.png" disabled={pending} onChange={event=>{const selected=event.target.files?.[0]||null;event.target.value='';if(selected&&(selected.size>10*1024*1024||!selected.size||!['application/pdf','image/jpeg','image/png'].includes(selected.type))){setError('Chọn tệp PDF, JPG hoặc PNG, không trống và tối đa 10 MB.');onFile(null)}else{setError('');onFile(selected)}}}/></label>{error&&<p className="error" role="alert">{error}</p>}</section>
}
