import { test,expect } from '@playwright/test'

test('five asset states: select initial status, finish repair, issue, retire and dispose',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const meta=await (await page.request.get('/api/meta')).json()
 const statusId=(code:string)=>String(meta['master-data'].find((s:any)=>s.group==='asset_status'&&s.code===code).id)
 await page.goto('/warehouses')
 await page.getByRole('button',{name:'Nhập tài sản',exact:true}).click()
 const dialog=page.getByRole('dialog')
 const status=dialog.getByLabel('Trạng thái',{exact:false})
 await expect(status).toBeEnabled()
 await expect(status).toHaveValue(statusId('available'))
 await expect(status.locator('option')).toHaveText(['Chọn trạng thái','Sẵn sàng','Đang sử dụng','Đang bảo trì','Hư / Ngừng sử dụng','Đã thanh lý'])
 await status.selectOption('')
 expect(await status.evaluate((node:HTMLSelectElement)=>node.validity.valueMissing)).toBe(true)
 await status.selectOption(statusId('maintenance'))
 await dialog.getByLabel('Loại',{exact:false}).selectOption({label:'Laptop'})
 await dialog.getByLabel('Model',{exact:false}).fill('STATUSFLOW')
 const serial='FLOW-'+Date.now()
 await dialog.getByLabel('Số sê-ri',{exact:false}).fill(serial)
 await dialog.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 const created=(await (await page.request.get('/api/assets?q='+serial)).json()).items[0]
 expect(created.current_status).toBe('MAINTENANCE')
 await page.goto('/assets/'+created.id)
 await expect(page.locator('.asset-title-line')).toContainText('Đang bảo trì')
 await expect(page.getByRole('button',{name:'Xuất kho',exact:true})).toHaveCount(0)
 await page.locator('.asset-command-bar').getByRole('button',{name:'Bảo trì / Sửa chữa',exact:true}).click()
 await dialog.getByLabel('Nhóm vấn đề',{exact:false}).selectOption({label:'Phần cứng'})
 await dialog.getByLabel('Trạng thái',{exact:false}).selectOption({label:'Mới'})
 await dialog.getByRole('textbox',{name:'Vấn đề *',exact:true}).fill('Màn hình không hiển thị')
 await dialog.getByLabel('Cách xử lý',{exact:false}).fill('Thay cáp màn hình và kiểm tra hoạt động')
 await dialog.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button',{name:'Hoàn tất xử lý',exact:true}).click()
 await dialog.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('link',{name:created.code+' →',exact:true}).click()
 await expect(page.locator('.asset-title-line')).toContainText('Sẵn sàng')
 await page.getByRole('button',{name:'Xuất kho',exact:true}).click()
 await dialog.getByLabel('Người nhận',{exact:false}).selectOption('4')
 await dialog.getByRole('button',{name:'Xác nhận xuất kho'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.asset-title-line')).toContainText('Đang sử dụng')
 await page.getByRole('button',{name:'Ngừng sử dụng',exact:true}).click()
 await dialog.getByLabel('Lý do',{exact:false}).fill('Thiết bị hư, không tiếp tục sử dụng')
 await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.asset-title-line')).toContainText('Hư / Ngừng sử dụng')
 await page.getByRole('button',{name:'Thanh lý',exact:true}).click()
 await expect(dialog.getByLabel('Tài sản',{exact:false})).toHaveValue(String(created.id))
 await dialog.getByLabel('Lý do',{exact:false}).fill('Bàn giao thanh lý theo biên bản')
 await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.asset-title-line')).toContainText('Đã thanh lý')
 for(const name of ['Xuất kho','Thu hồi','Ngừng sử dụng','Thanh lý','Bảo trì'])await expect(page.locator('.asset-command-bar').getByRole('button',{name,exact:true})).toHaveCount(0)
 await page.getByRole('tab',{name:'Lịch sử',exact:true}).click()
 await expect(page.locator('.asset-lifecycle')).toContainText('Hư / Ngừng sử dụng → Đã thanh lý')
 await page.getByLabel('Loại sự kiện',{exact:true}).selectOption('DISPOSED')
 const row=page.locator('.asset-lifecycle tbody tr')
 await expect(row).toHaveCount(1)
 await row.click()
 await expect(dialog).toContainText('Bàn giao thanh lý theo biên bản')
 await expect(dialog).toContainText('Nguyen Minh Anh')
 await page.screenshot({path:'/tmp/it-helpdesk-status-validation/disposal-history.png',fullPage:true})
 await page.keyboard.press('Escape')
 await page.goto('/assets?status=disposed&q='+serial)
 await expect(page.locator('tbody')).toContainText(serial)
 const detail=await (await page.request.get('/api/assets/'+created.id+'/detail')).json()
 expect(detail.current_status).toBe('DISPOSED')
 expect(detail.lifecycle.map((e:any)=>e.event_type)).toEqual(['DISPOSED','RETIRED','ISSUED','MAINTENANCE','MAINTENANCE','RECEIVED'])
 expect(errors).toEqual([])
})
