import { test,expect } from '@playwright/test'

test('chuyển người phụ trách nguyên tử và xem lịch sử tiếng Việt',async({page})=>{
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const headers={'X-Requested-With':'Helpdesk'}
 const meta=await (await page.request.get('/api/meta')).json()
 const station=meta.locations.find((r:any)=>r.name==='DG-01BD')
 const create=await page.request.post('/api/assets/register',{headers,data:{model:'AUDIT',serial:'REASSIGN-'+Date.now(),warehouse_id:meta.warehouses[0].id,type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id}})
 expect(create.status()).toBe(201)
 const asset=await create.json()
 const issue=await page.request.post('/api/inventory/transactions',{headers,data:{transaction_type:'ISSUE',asset_id:asset.id,warehouse_id:asset.warehouse_id,recipient_user_id:4,recipient_location_id:station.id}})
 expect(issue.status()).toBe(201)
 await page.goto('/assets/'+asset.id)
 await page.getByRole('button',{name:'Chuyển người phụ trách',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByLabel('Người phụ trách mới').selectOption('2')
 await dialog.getByLabel('Lý do').fill('Bàn giao ca vận hành')
 await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.asset-assignee')).toContainText(meta.users.find((u:any)=>u.id===2).name)
 await page.getByRole('tab',{name:'Lịch sử',exact:true}).click()
 const history=page.locator('.asset-lifecycle')
 await expect(history.locator('tbody tr')).toHaveCount(3)
 await expect(history.locator('tbody tr').first()).toContainText('Chuyển người chịu trách nhiệm')
 await page.getByLabel('Loại sự kiện',{exact:true}).selectOption('REASSIGNED')
 await expect(history.locator('tbody tr')).toHaveCount(1)
 await history.locator('tbody tr').first().focus()
 await page.keyboard.press('Enter')
 await expect(dialog).toBeVisible()
 await expect(dialog).toContainText(meta.users.find((u:any)=>u.id===4).name)
 await expect(dialog).toContainText(meta.users.find((u:any)=>u.id===2).name)
 const state=dialog.locator('section').filter({has:page.getByRole('heading',{name:'Trạng thái trước và sau thao tác'})})
 await expect(state.getByRole('cell',{name:'Đang sử dụng',exact:true})).toHaveCount(2)
 await expect(state.getByRole('cell',{name:'Q7 › OUTBOUND › DG-01BD',exact:true})).toHaveCount(2)
 await page.screenshot({path:'/tmp/helpdesk-event-vietnamese.png',fullPage:true})
 await page.keyboard.press('Escape')
 await expect(dialog).not.toBeVisible()
 const data=await (await page.request.get(`/api/assets/${asset.id}/detail`)).json()
 expect(data.lifecycle.map((e:any)=>e.event_type)).toEqual(['REASSIGNED','ISSUED','RECEIVED'])
 expect(data.current_location).toBe(station.id)
 expect(data.current_status).toBe('IN_USE')
 expect(data.current_assignee).toBe(2)
})
