import { test,expect } from '@playwright/test'

test('asset workspace, scoped editing, popup issue/return and retirement lifecycle',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.setViewportSize({width:1536,height:1024})
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập'}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const meta=await (await page.request.get('/api/meta')).json()
 const actor=await (await page.request.get('/api/auth/me')).json()
 const response=await page.request.post('/api/assets/register',{headers:{'X-Requested-With':'Helpdesk'},data:{model:'TE299',serial:'DETAIL-'+Date.now(),type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,warehouse_id:meta.warehouses[0].id}})
 expect(response.status()).toBe(201)
 const asset=await response.json();const url='/assets/'+asset.id
 await page.goto(url)
 await expect(page.getByRole('tab')).toHaveText(['Tổng quan','Mạng','Lịch sử'])
 await expect(page.getByRole('heading',{name:'TE299',exact:true})).toBeVisible()
 await expect(page.locator('.asset-fields')).toHaveCount(4)
 for(const field of ['Tên','Source','Warranty Expiry','Ghi chú'])await expect(page.locator('.asset-fields dt').filter({hasText:new RegExp('^'+field+'$')})).toHaveCount(0)
 const receiving=page.locator('.asset-card').filter({has:page.getByRole('heading',{name:'Nhập và bàn giao'})})
 await expect(receiving).toContainText(actor.name)
 await page.getByRole('button',{name:'Sửa thông tin',exact:true}).click()
 let dialog=page.getByRole('dialog')
 for(const field of ['Tên','Source','Warranty Expiry','Ghi chú'])await expect(dialog.getByLabel(field,{exact:true})).toHaveCount(0)
 await dialog.getByRole('button',{name:'Đóng'}).click()
 const additional=page.locator('.asset-card').filter({has:page.getByRole('heading',{name:'Thông tin bổ sung'})})
 await additional.getByRole('button',{name:'Sửa',exact:true}).click()
 dialog=page.getByRole('dialog')
 await expect(dialog.getByLabel('Model',{exact:false})).toHaveCount(0)
 await dialog.getByLabel('Mô tả').fill('Asset workspace verification')
 await dialog.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(additional).toContainText('Asset workspace verification')
 await page.screenshot({path:'/tmp/helpdesk-asset-overview.png',fullPage:true})
 await page.locator('.asset-assignee').getByRole('button',{name:'Cấp phát',exact:true}).click()
 dialog=page.getByRole('dialog')
 await expect(dialog.getByRole('combobox',{name:'Tài sản *',exact:true})).toHaveValue(String(asset.id))
 await dialog.getByLabel('Trạm nhận').selectOption({label:'Q7 / OUTBOUND / DG-01BD'})
 await dialog.getByRole('button',{name:'Xác nhận xuất kho'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page).toHaveURL(new RegExp(url+'$'))
 await expect(receiving).toContainText(actor.name)
 await expect(receiving.locator('dd').last()).toHaveText(actor.name)
 await page.getByRole('button',{name:'Thu hồi về kho',exact:true}).click()
 dialog=page.getByRole('dialog')
 await expect(dialog.getByRole('combobox',{name:'Tài sản *',exact:true})).toHaveValue(String(asset.id))
 await expect(dialog.getByRole('combobox',{name:'Kho *',exact:true})).toBeEnabled()
 await dialog.getByRole('button',{name:'Xác nhận nhập kho'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button',{name:'Ngừng sử dụng',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Lý do',{exact:false}).fill('End of service life')
 await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.asset-title-line')).toContainText('Ngừng sử dụng')
 await page.getByRole('tab',{name:'Lịch sử',exact:true}).click()
 await expect(page.locator('.asset-lifecycle')).toContainText('Nhập tài sản')
 await expect(page.locator('.asset-lifecycle')).toContainText('Cấp phát')
 await expect(page.locator('.asset-lifecycle')).toContainText('Ngừng sử dụng')
 await expect(page.locator('.asset-lifecycle')).toContainText('End of service life')
 await page.screenshot({path:'/tmp/helpdesk-asset-history.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 await expect(page.locator('.sidebar')).not.toBeInViewport()
 await page.screenshot({path:'/tmp/helpdesk-asset-history-mobile.png',fullPage:true,animations:'disabled'})
 expect(errors).toEqual([])
})
