import {test,expect} from '@playwright/test'
for(const [outcome,state] of [['Đã khắc phục','AVAILABLE'],['Không khắc phục được','RETIRED']])test('inline maintenance outcome: '+outcome,async({page})=>{
 const headers={'X-Requested-With':'Helpdesk'}
 await page.request.post('/api/auth/login',{headers,data:{username:'admin',password:'WarehouseTest2026!'}})
 const meta=await (await page.request.get('/api/meta')).json()
 const post=async(path:string,data:any)=>{const r=await page.request.post('/api'+path,{headers,data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()}
 const asset=await post('/assets/register',{warehouse_id:meta.warehouses[0].id,type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,model:'ZD421',serial:'INLINE-'+state+'-'+Date.now()})
 const md=(group:string,code:string)=>meta['master-data'].find((r:any)=>r.group===group&&r.code===code).id
 const record=await post('/maintenance',{asset_id:asset.id,type_id:md('maintenance_type','hardware'),status_id:md('maintenance_status','open'),problem:'Máy in không ra tem.',technician_id:3})
 await page.setViewportSize({width:1366,height:768})
 await page.goto('/maintenance/'+record.id)
 await expect(page.getByRole('button',{name:'Chỉnh sửa',exact:true})).toHaveCount(0)
 await expect(page.getByRole('textbox',{name:'Vấn đề',exact:true})).toBeEditable()
 await page.getByRole('button',{name:'Hoàn tất',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('chọn kết quả')
 await page.getByRole('textbox',{name:'Nguyên nhân',exact:true}).fill('Đầu in nhiệt lỗi.')
 await page.getByRole('textbox',{name:'Cách xử lý',exact:true}).fill(outcome==='Đã khắc phục'?'Thay đầu in nhiệt.':'Kiểm tra, không thể sửa chữa.')
 await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click()
 await expect(page.getByRole('button',{name:'Lưu thay đổi',exact:true})).toBeDisabled()
 await page.reload()
 await expect(page.getByRole('textbox',{name:'Nguyên nhân',exact:true})).toHaveValue('Đầu in nhiệt lỗi.')
 await page.getByRole('radio',{name:outcome,exact:true}).check()
 expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBeTruthy()
 await page.screenshot({path:'/tmp/maintenance-inline-'+state+'.png',fullPage:true})
 await page.getByRole('button',{name:'Hoàn tất',exact:true}).click()
 await expect(page.locator('.maintenance-title-line .badge')).toHaveText('Hoàn tất')
 await expect(page.getByRole('textbox',{name:'Vấn đề',exact:true})).toHaveCount(0)
 await expect(page.getByRole('radio',{name:outcome,exact:true})).toBeDisabled()
 await expect(page.getByRole('button',{name:'Lưu thay đổi',exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Hoàn tất',exact:true})).toHaveCount(0)
 const current=await (await page.request.get('/api/assets/'+asset.id)).json()
 expect(current.current_status).toBe(state)
 expect(current.current_location_id).toBe(asset.current_location_id)
 expect(current.warehouse_id).toBe(asset.warehouse_id)
 if(state==='RETIRED')await expect(page.locator('.maintenance-device-summary')).toContainText('Hư / Ngừng sử dụng')
 const patch=await page.request.patch('/api/maintenance/'+record.id,{headers,data:{note:'Attempt to change completed record'}})
 expect(patch.status()).toBe(422)
})
