import {test,expect} from '@playwright/test'
test('maintenance detail shows resolution steps, device and real duration',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill('WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const headers={'X-Requested-With':'Helpdesk'},meta=await (await page.request.get('/api/meta')).json()
 const md=(g:string,c:string)=>meta['master-data'].find((r:any)=>r.group===g&&r.code===c).id
 const post=async(path:string,data:any)=>{const r=await page.request.post('/api'+path,{headers,data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()}
 const serial='DETAIL-'+Date.now()
 const asset=await post('/assets/register',{model:'MFC-L5900',brand:'Brother',serial,type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,warehouse_id:meta.warehouses[0].id})
 await post('/inventory/transactions',{transaction_type:'ISSUE',asset_id:asset.id,warehouse_id:asset.warehouse_id,recipient_user_id:4,recipient_location_id:meta.locations.find((r:any)=>r.name==='DG-01BD').id})
 const start=new Date(Date.now()-120*60000),end=new Date(start.getTime()+75*60000)
 const record=await post('/maintenance',{asset_id:asset.id,type_id:md('maintenance_type','network'),status_id:md('maintenance_status','completed'),resolution_outcome:'FIXED',technician_id:3,problem:'Máy in không in được qua mạng. Các trạm không thể sử dụng.',diagnosis:'Cụm card mạng bị hỏng, không nhận link.',action_taken:'1. Kiểm tra dây mạng và switch.\n2. Thay cụm card mạng.\n3. Cấu hình lại IP và test in.\n4. Kiểm tra hoạt động ổn định.',parts_replaced:'Network board (Brother)\nCáp mạng',vendor:'Nhà cung cấp thiết bị',note:'Đã kiểm tra tại trạm.',start_at:start.toISOString(),end_at:end.toISOString()})
 await page.goto('/maintenance/'+record.id)
 await expect(page.getByRole('heading',{name:record.number,exact:true})).toBeVisible()
 await expect(page.locator('.maintenance-title-line')).toContainText('Hoàn tất')
 for(const title of ['Vấn đề','Nguyên nhân','Cách xử lý','Linh kiện thay thế','Thông tin thiết bị'])await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible()
 await expect(page.locator('.maintenance-info-rows')).toContainText('S/N')
 await expect(page.locator('.maintenance-header-meta')).toContainText('1 giờ 15 phút')
 await expect(page.getByRole('heading',{name:'Thông tin phiếu',exact:true})).toHaveCount(0)
 await expect(page.getByText('Kết thúc dự kiến',{exact:true})).toHaveCount(0)
 await expect(page.locator('.maintenance-step-number')).toHaveCount(0)
 await expect(page.locator('.maintenance-device-summary')).toContainText('MFC-L5900')
 await expect(page.locator('.maintenance-sidebar')).toContainText(serial)
 await expect(page.locator('.maintenance-legacy-parts>div')).toHaveCount(2)
 await expect(page.locator('.maintenance-legacy-parts')).toContainText('Network board (Brother)')
 await expect(page.getByRole('button',{name:'Hoàn tất',exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'Thao tác khác'}).click()
 await expect(page.getByRole('button',{name:'Thu hồi về kho',exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Ngừng sử dụng',exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'Đóng menu thao tác'}).click()
 for(const size of [{width:1440,height:900},{width:1366,height:768}]){
  await page.setViewportSize(size)
  expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBeTruthy()
  await page.screenshot({path:`/tmp/maintenance-redesign-${size.width}.png`,fullPage:true})
 }
 await page.setViewportSize({width:390,height:844})
 await expect.poll(()=>page.locator('.sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.screenshot({path:'/tmp/maintenance-detail-mobile.png',fullPage:true})
 expect(errors).toEqual([])
})
