import {test,expect} from '@playwright/test'
test('new maintenance has two states and saves warehouse component selection',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 const headers={'X-Requested-With':'Helpdesk'}
 await page.request.post('/api/auth/login',{headers,data:{username:'admin',password:'WarehouseTest2026!'}})
 const meta=await (await page.request.get('/api/meta')).json()
 const post=async(path:string,data:any)=>{const r=await page.request.post('/api'+path,{headers,data});expect(r.ok(),await r.text()).toBeTruthy();return r.json()}
 const asset=await post('/assets/register',{warehouse_id:meta.warehouses[0].id,type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,model:'ThinkPad',serial:'COMPACT-'+Date.now()})
 const part=await post('/assets/register',{warehouse_id:meta.warehouses[0].id,type_id:meta['asset-types'].find((r:any)=>r.name==='Linh kiện').id,model:'RAM 16 GB',serial:'RAM-'+Date.now()})
 await page.goto('/maintenance')
 await page.getByRole('button',{name:'Tạo mới bản ghi',exact:true}).click()
 const dialog=page.getByRole('dialog')
 const status=dialog.getByLabel('Trạng thái xử lý')
 await expect(status.locator('option')).toHaveText(['Chọn trạng thái xử lý','Mới','Hoàn tất'])
 await expect(status).toHaveValue(String(meta['master-data'].find((r:any)=>r.group==='maintenance_status'&&r.code==='open').id))
 await dialog.getByLabel('Tài sản', {exact:false}).first().selectOption(String(asset.id))
 await dialog.getByLabel('Nhóm vấn đề').selectOption(String(meta['master-data'].find((r:any)=>r.group==='maintenance_type'&&r.code==='hardware').id))
 await dialog.getByRole('textbox',{name:'Vấn đề *',exact:true}).fill('Máy thiếu bộ nhớ')
 await dialog.getByLabel('Người xử lý').selectOption('3')
 await dialog.getByLabel('Chọn linh kiện trong kho').selectOption(String(part.id))
 await dialog.getByRole('button',{name:'Tạo phiếu',exact:true}).click()
 await expect(dialog).toHaveCount(0)
 const list=await (await page.request.get('/api/maintenance?q='+encodeURIComponent('Máy thiếu bộ nhớ'))).json()
 const record=list.items.find((r:any)=>r.asset_id===asset.id)
 expect(record.replacement_asset_ids).toEqual([part.id])
 const issued=await (await page.request.get('/api/assets/'+part.id+'/detail')).json()
 expect(issued.warehouse_id).toBeNull()
 expect(issued.current_status).toBe('IN_USE')
 expect(issued.lifecycle.filter((e:any)=>e.event_type==='ISSUED')).toHaveLength(1)
 await page.goto('/maintenance/'+record.id)
 await expect(page.locator('.maintenance-title-line .badge')).toHaveText('Mới')
 await expect(page.locator('.maintenance-title-line .badge')).toHaveClass(/amber/)
 await expect(page.locator('.maintenance-part')).toContainText(part.serial)
 await expect(page.getByRole('button',{name:'Bỏ linh kiện '+part.code})).toHaveCount(0)
 await page.reload()
 await expect(page.locator('.maintenance-part')).toContainText(part.serial)
 await page.getByRole('textbox',{name:'Nguyên nhân',exact:true}).fill('Bộ nhớ không đủ')
 await page.getByRole('textbox',{name:'Cách xử lý',exact:true}).fill('Lắp thêm bộ nhớ')
 await page.getByRole('radio',{name:'Đã khắc phục',exact:true}).check()
 await page.getByRole('button',{name:'Hoàn tất',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page.locator('.maintenance-title-line .badge')).toHaveText('Hoàn tất')
 expect(errors).toEqual([])
})
