import { postStock, attachReturnDocument } from './stock-helpers'
import { test,expect } from '@playwright/test'

for(const flow of ['onsite','resume','return','retire'])test('maintenance issue flow: '+flow,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const headers={'X-Requested-With':'Helpdesk'}
 const meta=await (await page.request.get('/api/meta')).json()
 const create=await page.request.post('/api/assets/register',{headers,data:{model:'MAINTFLOW',serial:'MAINT-'+flow+'-'+Date.now(),type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,warehouse_id:meta.warehouses[0].id}})
 expect(create.status()).toBe(201)
 const asset=await create.json()
 const station=meta.locations.find((r:any)=>r.name==='DG-01BD')
 const issue=await postStock(page.request,{transaction_type:'ISSUE',asset_id:asset.id,warehouse_id:asset.warehouse_id,recipient_location_id:station.id,recipient_user_id:4})
 expect(issue.status()).toBe(201)
 const state=async()=>await (await page.request.get(`/api/assets/${asset.id}/detail`)).json()
 const created=await page.request.post('/api/maintenance',{headers,data:{asset_id:asset.id,type_id:meta['master-data'].find((r:any)=>r.group==='maintenance_type'&&r.code==='network').id,status_id:meta['master-data'].find((r:any)=>r.group==='maintenance_status'&&r.code==='open').id,problem:'Máy in mất kết nối '+flow,technician_id:3,estimate_hours:2}})
 expect(created.status()).toBe(201)
 await page.goto('/maintenance/'+(await created.json()).id)
 const dialog=page.getByRole('dialog')
 const url=page.url()
 let current=await state()
 expect(current.current_status).toBe('IN_USE')
 expect(current.current_location).toBe(station.id)
 expect(current.current_assignee).toBe(4)
 await page.getByRole('textbox',{name:'Nguyên nhân',exact:true}).fill('Lỗi cáp mạng')
 await page.getByRole('textbox',{name:'Cách xử lý',exact:true}).fill('Thay cáp và kiểm tra kết nối')
 await page.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 expect((await state()).current_status).toBe('IN_USE')
 if(flow!=='onsite'){
  await page.getByRole('button',{name:'Thao tác khác',exact:true}).click()
  await page.getByRole('button',{name:'Dừng thiết bị để sửa',exact:true}).click()
  await expect(page.getByRole('button',{name:'Dừng thiết bị để sửa',exact:true})).toHaveCount(0)
  current=await state()
  expect(current.current_status).toBe('MAINTENANCE')
  expect(current.current_location).toBe(station.id)
  expect(current.current_assignee).toBe(4)
 }
 if(flow==='onsite'||flow==='resume'){
  await page.getByRole('radio',{name:'Đã khắc phục',exact:true}).check()
  await page.getByRole('button',{name:'Hoàn tất',exact:true}).click()
 }else if(flow==='return'){
  await page.getByRole('button',{name:'Thao tác khác',exact:true}).click()
  await page.getByRole('button',{name:'Thu hồi về kho',exact:true}).click()
  await expect(dialog.getByLabel('Tình trạng thu hồi')).toHaveValue('AVAILABLE')
  await dialog.getByLabel('Nguyên nhân thu hồi').fill('Thu hồi thiết bị về kho')
 await attachReturnDocument(dialog)
 await dialog.getByRole('button',{name:'Xác nhận thu hồi'}).click()
 }else{
  await page.getByRole('button',{name:'Thao tác khác',exact:true}).click()
  await page.getByRole('button',{name:'Ngừng sử dụng',exact:true}).click()
  await dialog.getByLabel('Lý do',{exact:false}).fill('Không thể sửa, xác định không tiếp tục sử dụng')
  await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 }
 await expect(dialog).not.toBeVisible()
 await expect(page.getByRole('button',{name:'Hoàn tất',exact:true})).toHaveCount(0)
 current=await state()
 expect(current.current_status).toBe(flow==='retire'?'RETIRED':'AVAILABLE')
 if(flow==='onsite'||flow==='resume'){
  expect(current.current_location).toBe(station.id);expect(current.current_assignee).toBeNull()
 }
 if(flow==='return'){
  expect(current.warehouse_id).toBe(asset.warehouse_id);expect(current.current_assignee).toBeNull()
 }
 expect(current.lifecycle[0].after_state.maintenance.action_taken).toBe('Thay cáp và kiểm tra kết nối')
 await page.getByRole('link',{name:'Xem lịch sử tài sản',exact:false}).click()
 const first=page.locator('.asset-lifecycle tbody tr').first()
 await expect(first).toContainText('Nguyen Minh Anh')
 await first.click()
 await expect(dialog).toContainText('Thay cáp và kiểm tra kết nối')
 await expect(dialog).toContainText('Lỗi cáp mạng')
 await expect(dialog.getByRole('link',{name:'Mở phiếu bảo trì'})).toHaveAttribute('href',new URL(url).pathname)
 await page.keyboard.press('Escape')
 await page.goto('/maintenance')
 await page.getByRole('textbox',{name:'Tìm trong bảng'}).fill('Máy in mất kết nối '+flow)
 await expect(page.locator('tbody')).toContainText(meta['master-data'].find((r:any)=>r.group==='maintenance_type'&&r.code==='network').name)
 await page.setViewportSize({width:390,height:844})
 await page.goto(url)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
