import {test,expect} from '@playwright/test'
test('quick maintenance completes immediately and retains custody',async({page})=>{
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill('WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const headers={'X-Requested-With':'Helpdesk'},meta=await (await page.request.get('/api/meta')).json()
 const response=await page.request.post('/api/assets/register',{headers,data:{model:'QUICK',serial:'QUICK-'+Date.now(),type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,warehouse_id:meta.warehouses[0].id}})
 expect(response.status()).toBe(201);const asset=await response.json()
 expect((await page.request.post('/api/inventory/transactions',{headers,data:{transaction_type:'ISSUE',asset_id:asset.id,warehouse_id:asset.warehouse_id,recipient_user_id:4}})).status()).toBe(201)
 await page.goto('/assets/'+asset.id)
 await page.locator('.asset-command-bar').getByRole('button',{name:'Bảo trì',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog.getByRole('heading',{name:'Bảo trì nhanh',exact:true})).toBeVisible()
 await expect(dialog.getByRole('button',{name:'Thu hồi & tạo phiếu',exact:true})).toBeVisible()
 expect(await dialog.locator('.quick-maintenance-body').evaluate(el=>el.scrollHeight<=el.clientHeight)).toBeTruthy()
 await expect(dialog.getByLabel('Ghi chú')).toBeHidden()
 await dialog.getByLabel('Nhóm vấn đề').selectOption({label:'Mạng'})
 await dialog.getByRole('textbox',{name:'Vấn đề *',exact:true}).fill('Mất kết nối')
 await dialog.getByLabel('Nguyên nhân / Chẩn đoán').fill('Cáp mạng lỏng')
 await dialog.getByLabel('Cách xử lý').fill('Cắm lại cáp, kiểm tra kết nối tốt')
 await expect(dialog.getByLabel('Thời gian dự kiến (giờ)')).toHaveCount(0)
 await expect(dialog.getByLabel('Trạng thái xử lý')).toHaveCount(0)
 await dialog.getByLabel('Kết quả xử lý').selectOption({label:'Đã khắc phục'})
 await dialog.getByRole('button',{name:'Hoàn tất',exact:true}).click()
 await expect(dialog).not.toBeVisible();await expect(page).toHaveURL(new RegExp('/assets/'+asset.id+'$'))
 const current=await (await page.request.get('/api/assets/'+asset.id+'/detail')).json()
 expect(current.current_status).toBe('AVAILABLE');expect(current.current_assignee).toBeNull()
 expect(current.lifecycle[0].after_state.maintenance.end_at).toBeTruthy()
 expect(current.lifecycle[0].after_state.maintenance.action_taken).toBe('Cắm lại cáp, kiểm tra kết nối tốt')
 await expect(page.getByRole('button',{name:'Hoàn tất',exact:true})).toHaveCount(0)
})
