import { test,expect } from '@playwright/test'
test('return popup creates repair atomically and keeps table history',async({page})=>{
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill('WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const meta=await (await page.request.get('/api/meta')).json(),headers={'X-Requested-With':'Helpdesk'}
 const res=await page.request.post('/api/assets/register',{headers,data:{model:'RETURNPOPUP',serial:'POPUP-'+Date.now(),type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,warehouse_id:meta.warehouses[0].id}})
 expect(res.status()).toBe(201);const asset=await res.json()
 expect((await page.request.post('/api/inventory/transactions',{headers,data:{transaction_type:'ISSUE',warehouse_id:asset.warehouse_id,asset_id:asset.id,recipient_user_id:4}})).status()).toBe(201)
 await page.goto('/assets/'+asset.id)
 await page.locator('.asset-command-bar').getByRole('button',{name:'Bảo trì / Sửa chữa',exact:true}).click()
 await page.getByRole('button',{name:'Bảo trì cần thời gian: Thu hồi và tạo phiếu'}).click()
 const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible()
 const box=await dialog.boundingBox();expect(Math.abs(box!.x+box!.width/2-720)).toBeLessThan(3)
 await dialog.getByLabel('Nguyên nhân thu hồi').fill('Không lên nguồn, thu hồi để sửa')
 await expect(dialog.getByLabel('Tạo phiếu bảo trì sau thu hồi')).toBeChecked()
 await expect(dialog.getByLabel('Thời gian dự kiến (giờ)')).toHaveCount(0)
 await expect(dialog.getByLabel('Tình trạng thu hồi')).toHaveValue('MAINTENANCE')
 await dialog.getByRole('textbox',{name:'Vấn đề *',exact:true}).fill('Không lên nguồn')
 await dialog.getByLabel('Nhóm vấn đề').selectOption({label:'Nguồn điện'})
 await dialog.getByLabel('Người xử lý').selectOption('3')
 await dialog.getByLabel('Nguyên nhân / Chẩn đoán').fill('Nghi nguồn hỏng')
 await dialog.getByRole('button',{name:'Thu hồi và tạo bảo trì'}).click()
 await expect(dialog).not.toBeVisible()
 const current=await (await page.request.get(`/api/assets/${asset.id}/detail`)).json()
 expect(current.current_status).toBe('MAINTENANCE');expect(current.warehouse_id).toBe(asset.warehouse_id);expect(current.current_assignee).toBeNull()
 const repair=current.lifecycle[0].after_state.maintenance
 expect(repair.problem).toBe('Không lên nguồn')
 await page.goto('/assets/'+asset.id+'?tab=history')
 await expect(page.locator('.asset-lifecycle table')).toBeVisible()
 await page.goto('/maintenance/'+repair.id)
 await page.getByRole('textbox',{name:'Cách xử lý',exact:true}).fill('Thay nguồn, kiểm tra OK')
 await page.getByRole('radio',{name:'Đã khắc phục',exact:true}).check()
 await page.setViewportSize({width:390,height:844})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.getByRole('button',{name:'Hoàn tất',exact:true}).click()
 await expect(page.locator('.maintenance-title-line')).toContainText('Hoàn tất')
 expect((await (await page.request.get(`/api/assets/${asset.id}/detail`)).json()).current_status).toBe('AVAILABLE')
})
