import { test,expect } from '@playwright/test'
import { fileURLToPath } from 'node:url'
const signedTemplate=fileURLToPath(new URL('../../[Template]BBBANGIAONHANTHIEtBI.pdf',import.meta.url))
test('person issue requires signed handover, prints A4 and saves document in stock history',async({page})=>{
 await page.setViewportSize({width:1920,height:1080})
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const meta=await (await page.request.get('/api/meta')).json()
 const response=await page.request.post('/api/assets/register',{headers:{'X-Requested-With':'Helpdesk'},data:{model:'Handover test',serial:'HANDOVER-'+Date.now(),type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,warehouse_id:meta.warehouses[0].id}})
 expect(response.status()).toBe(201);const asset=await response.json()
 await page.goto('/assets/'+asset.id)
 await page.getByRole('button',{name:'Xuất kho',exact:true}).click()
 const dialog=page.getByRole('dialog'),submit=dialog.getByRole('button',{name:'Xác nhận xuất kho',exact:true})
 await dialog.getByRole('combobox',{name:/Người nhận/}).selectOption('4')
 await expect(submit).toBeDisabled()
 const popupPromise=page.waitForEvent('popup')
 await dialog.getByRole('button',{name:'In biên bản',exact:true}).click()
 const popup=await popupPromise
 await expect(popup.getByRole('heading',{name:'BIÊN BẢN BÀN GIAO THIẾT BỊ',exact:true})).toBeVisible()
 await expect(popup.locator('table')).toContainText(asset.code)
 await expect(popup.locator('body')).toContainText(meta.users.find((u:any)=>u.id===4).name)
 await popup.waitForFunction(()=>Array.from(document.images).every(image=>image.complete&&image.naturalWidth>0))
 await popup.close()
 await dialog.getByLabel('Biên bản bàn giao đã ký',{exact:true}).setInputFiles(signedTemplate)
 await expect(submit).toBeEnabled()
 await dialog.getByLabel('Tình trạng',{exact:false}).fill('Tốt, đã kiểm tra')
 await expect(submit).toBeDisabled()
 await dialog.getByLabel('Biên bản bàn giao đã ký',{exact:true}).setInputFiles(signedTemplate)
 expect(await dialog.locator('.quick-maintenance-body').evaluate(el=>el.scrollHeight<=el.clientHeight)).toBeTruthy()
 const completion=page.waitForResponse(r=>r.url().endsWith('/api/inventory/issue-with-handover')&&r.request().method()==='POST')
 await submit.click();const result=await completion;expect(result.status()).toBe(201);const transaction=await result.json()
 await expect(dialog).not.toBeVisible();await expect(page).toHaveURL(new RegExp('/assets/'+asset.id+'$'))
 const document=await page.request.get(transaction.handover_url);expect(document.status()).toBe(200);expect(document.headers()['content-type']).toBe('application/pdf')
 await page.goto('/inventory?tab=history')
 await page.getByRole('textbox',{name:'Tìm trong bảng'}).fill(transaction.number)
 await page.getByRole('row').filter({hasText:transaction.number}).click()
 await expect(page.getByRole('dialog').getByRole('link',{name:'Tải biên bản',exact:true})).toHaveAttribute('href',transaction.handover_url)
})

test('return requires a signed document and prints a generated device name',async({page})=>{
 await page.setViewportSize({width:1920,height:1080})
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 const meta=await (await page.request.get('/api/meta')).json()
 const serial='RETURN-DOC-'+Date.now()
 const created=await page.request.post('/api/assets/register',{headers:{'X-Requested-With':'Helpdesk'},data:{model:'Latitude 5530',serial,type_id:meta['asset-types'].find((r:any)=>r.name==='Laptop').id,warehouse_id:meta.warehouses[0].id}})
 expect(created.status()).toBe(201);const asset=await created.json()
 expect(asset.name).toBe('Laptop - Latitude 5530 - '+serial)
 const {postStock}=await import('./stock-helpers')
 expect((await postStock(page.request,{transaction_type:'ISSUE',asset_id:asset.id,warehouse_id:asset.warehouse_id,recipient_user_id:4})).status()).toBe(201)
 await page.goto('/assets/'+asset.id)
 await page.locator('.asset-command-bar').getByRole('button',{name:'Thu hồi',exact:true}).click()
 const dialog=page.getByRole('dialog'),submit=dialog.getByRole('button',{name:'Xác nhận thu hồi',exact:true})
 await dialog.getByLabel('Nguyên nhân thu hồi').fill('Thu hồi để đổi thiết bị')
 await expect(submit).toBeDisabled()
 const popupPromise=page.waitForEvent('popup');await dialog.getByRole('button',{name:'In biên bản',exact:true}).click();const popup=await popupPromise
 await expect(popup.getByRole('heading',{name:'BIÊN BẢN THU HỒI THIẾT BỊ',exact:true})).toBeVisible()
 await expect(popup.locator('table')).toContainText(asset.name)
 await expect(popup.locator('body')).toContainText('Thu hồi để đổi thiết bị')
 await popup.close()
 await dialog.getByLabel('Biên bản thu hồi đã ký',{exact:true}).setInputFiles(signedTemplate)
 await expect(submit).toBeEnabled()
 expect(await dialog.locator('.quick-maintenance-body').evaluate(el=>el.scrollHeight<=el.clientHeight)).toBeTruthy()
 const done=page.waitForResponse(r=>r.url().endsWith('/api/inventory/movement-with-document')&&r.request().method()==='POST')
 await submit.click();const response=await done;expect(response.status()).toBe(201);const row=await response.json()
 await expect(dialog).not.toBeVisible()
 expect(row.handover_snapshot.document_kind).toBe('RETURN')
 expect(row.handover_snapshot.device_name).toBe(asset.name)
 expect((await page.request.get(row.handover_url)).status()).toBe(200)
})
