import { test,expect } from '@playwright/test'

test('warehouse consumables and station workspace on desktop and mobile',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'WarehouseTest2026!')
 await page.getByRole('button',{name:'Đăng nhập'}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
 await page.goto('/assets')
 await expect(page.getByRole('button',{name:'Create asset'})).toHaveCount(0)
 await page.goto('/warehouses')
 await page.getByRole('button',{name:'Nhập vật tư / thu hồi'}).click()
 let dialog=page.getByRole('dialog')
 await dialog.getByLabel('Nhập vật tư').selectOption('new')
 const code='RIBBON-'+Date.now()
 await dialog.getByLabel('Mã *',{exact:true}).fill(code)
 await dialog.getByLabel('Tên *',{exact:true}).fill('Thermal transfer ribbon')
 await dialog.getByLabel('Số lượng *',{exact:true}).fill('10')
 await dialog.getByRole('button',{name:'Xác nhận nhập kho'}).click()
 await expect(dialog).not.toBeVisible()
 await page.goto('/inventory?tab=consumables')
 await page.getByRole('textbox',{name:'Tìm trong bảng'}).fill(code)
 await page.getByRole('row').filter({hasText:code}).getByRole('button',{name:'Xuất kho',exact:true}).click()
 dialog=page.getByRole('dialog')
 await expect(dialog.getByRole('combobox',{name:'Vật tư *',exact:true})).toBeDisabled()
 await expect(page).toHaveURL(/inventory\?tab=consumables/)
 await dialog.getByLabel('Số lượng *',{exact:true}).fill('3')
 await dialog.getByRole('button',{name:'Xác nhận xuất kho'}).click()
 await expect(dialog.getByRole('alert')).toContainText('Vui lòng chọn người hoặc trạm nhận')
 await dialog.getByLabel('Trạm nhận').selectOption({label:'Q7 / OUTBOUND / DG-18BD'})
 await dialog.getByRole('button',{name:'Xác nhận xuất kho'}).click()
 await expect(dialog).not.toBeVisible()
 await page.goto('/inventory?tab=consumables')
 const row=page.getByRole('row').filter({hasText:code})
 await expect(row.getByRole('cell',{name:'7',exact:true})).toBeVisible()
 await page.screenshot({path:'/tmp/helpdesk-warehouse-desktop.png',fullPage:true})
 await page.goto('/locations')
 await page.getByRole('textbox',{name:'Tìm vị trí'}).fill('Q7 / OUTBOUND / DG-18BD')
 await page.getByRole('button',{name:'DG-18BD',exact:true}).click()
 await page.getByRole('textbox',{name:'Tìm vị trí'}).fill('')
 await expect(page.locator('.location-detail-heading')).toContainText('DG-18BD')
 await expect(page.locator('.location-info-grid')).toContainText('192.168.20.80')
 await page.getByRole('tab',{name:'Mạng',exact:true}).click()
 await expect(page.getByRole('cell',{name:'192.168.20.80',exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'Lịch sử',exact:true}).click()
 await expect(page.getByRole('cell',{name:code,exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'Người dùng',exact:true}).click()
 await page.getByRole('tab',{name:'Tổng quan',exact:true}).click()
 await page.getByRole('button',{name:'Sửa',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Vị trí thực tế').fill('Building D - 1st Floor, Area B')
 await dialog.getByLabel('Bộ phận',{exact:true}).fill('Operations')
 await dialog.getByLabel('Tầng',{exact:true}).fill('1st Floor')
 await dialog.getByLabel('Khu vực',{exact:true}).fill('Area B')
 await dialog.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.location-info-grid')).toContainText('Operations')
 await page.screenshot({path:'/tmp/helpdesk-station-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await expect(page.locator('.location-detail-heading')).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
 await expect(page.locator('.sidebar')).not.toBeInViewport()
 await page.screenshot({path:'/tmp/helpdesk-station-mobile.png',fullPage:true,animations:'disabled'})
 expect(errors).toEqual([])
})
