import { test,expect } from '@playwright/test'

test.beforeEach(async({page})=>{
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('admin')
 await page.getByLabel('Password',{exact:true}).fill(process.env.DEMO_PASSWORD||'HelpdeskDemo2026!')
 await page.getByRole('button',{name:'Sign in'}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
})

test('search IP to asset and trace network, tickets and history',async({page})=>{
 await page.screenshot({path:'/tmp/helpdesk-dashboard.png',fullPage:true})
 await page.getByRole('textbox',{name:'Global search'}).fill('192.168.20.80')
 await expect(page.locator('.search-results')).toContainText('PRN-012')
 await page.locator('.search-results a').filter({hasText:'assets'}).first().click()
 await expect(page.getByRole('heading',{name:'Outbound label printer'})).toBeVisible()
 await page.getByRole('button',{name:'Network',exact:true}).click()
 await expect(page.locator('.detail-tables')).toContainText('192.168.20.80')
 await expect(page.locator('.detail-tables')).toContainText('Gi3')
 await page.locator('.view-tabs').getByRole('button',{name:'Location',exact:true}).click()
 await expect(page.locator('.detail-tables')).toContainText('DG-18BD')
 await page.getByRole('button',{name:'Tickets',exact:true}).click()
 await expect(page.locator('.detail-tables')).toContainText('Printer skipping labels')
 await page.getByRole('button',{name:'History',exact:true}).click()
 await expect(page.locator('.detail-tables')).toContainText('created')
})

test('create and update a ticket through the real API',async({page})=>{
 await page.getByRole('button',{name:'Create',exact:true}).click()
 await page.getByRole('button',{name:'New ticket',exact:true}).click()
 const dialog=page.getByRole('dialog')
 const title='Browser incident '+Date.now()
 await dialog.getByLabel('Title',{exact:false}).fill(title)
 await dialog.getByLabel('Description',{exact:false}).fill('A real browser-created incident for workflow verification.')
 await dialog.getByLabel('Category',{exact:false}).first().selectOption({label:'hardware · Hardware'})
 await dialog.getByLabel('Priority',{exact:false}).selectOption({label:'medium · Medium'})
 await dialog.getByLabel('Status',{exact:false}).selectOption({label:'open · Open'})
 await dialog.getByRole('button',{name:'Save changes'}).click()
 await expect(dialog).not.toBeVisible()
 await page.goto('/tickets')
 await page.getByRole('textbox',{name:'Search table'}).fill(title)
 await page.getByRole('cell',{name:title,exact:true}).click()
 await expect(page.getByRole('heading',{name:title})).toBeVisible()
 await page.getByPlaceholder('Add an update to the timeline…').fill('Verified end-to-end timeline update.')
 await page.getByRole('button',{name:'Post update'}).click()
 await expect(page.locator('.timeline')).toContainText('Verified end-to-end timeline update.')
})

test('all modules load and mobile navigation works',async({page})=>{
 const failures:string[]=[]
 page.on('pageerror',e=>failures.push(e.message))
 for(const path of ['assets','asset-types','locations','assignments','location-history','tickets','ip-addresses','subnets','vlans','switch-ports','maintenance','articles','reports','settings','master-data','users','audit-logs']){
  await page.goto('/'+path)
  await expect(page.locator('.main-content h1')).toBeVisible()
  await expect(page.locator('.main-content .error')).toHaveCount(0)
 }
 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 await page.getByRole('button',{name:'Open navigation'}).click()
 await expect(page.locator('.sidebar')).toBeInViewport()
 await page.locator('.sidebar').getByRole('link',{name:'Assets',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Asset inventory'})).toBeVisible()
 await expect(page.locator('.sidebar')).not.toBeInViewport()
 await expect(page.locator('.loading')).toHaveCount(0)
 await page.screenshot({path:'/tmp/helpdesk-mobile.png',fullPage:true})
 expect(failures).toEqual([])
})

test('asset create, move, assignment, return and maintenance via UI',async({page})=>{
 const code='E2E-'+Date.now()
 await page.goto('/assets')
 await page.getByRole('button',{name:'Create asset',exact:true}).click()
 let dialog=page.getByRole('dialog')
 await dialog.getByLabel('Code',{exact:false}).fill(code)
 await dialog.getByLabel('Name',{exact:false}).fill('Browser lifecycle asset')
 await dialog.getByLabel('Type',{exact:false}).selectOption({label:'Laptop'})
 await dialog.getByLabel('Status',{exact:false}).selectOption({label:'available · Available'})
 await dialog.getByRole('button',{name:'Save changes'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('textbox',{name:'Search table'}).fill(code)
 await page.getByRole('cell',{name:code,exact:true}).click()
 await page.getByRole('button',{name:'Move device',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Location',{exact:false}).selectOption({index:3})
 await dialog.getByLabel('Reason',{exact:false}).fill('Browser verified move')
 await dialog.getByRole('button',{name:'Save operation'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button',{name:'Assign',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('User',{exact:false}).selectOption({label:'Nguyen Van An'})
 await dialog.getByLabel('Condition Out',{exact:false}).fill('Good, tested')
 await dialog.getByRole('button',{name:'Save operation'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button',{name:'Return',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Condition In',{exact:false}).fill('Good, returned')
 await dialog.getByRole('button',{name:'Save operation'}).click()
 await expect(dialog).not.toBeVisible()
 await page.locator('.asset-actions').getByRole('button',{name:'Maintenance',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Type',{exact:false}).selectOption({label:'inspection · Inspection'})
 await dialog.getByLabel('Status',{exact:false}).selectOption({label:'open · Open'})
 await dialog.getByLabel('Problem',{exact:false}).fill('Routine browser inspection')
 await dialog.getByRole('button',{name:'Save changes'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.detail-subtitle')).toContainText('Repair')
 await page.locator('.view-tabs').getByRole('button',{name:'Assignment',exact:true}).click()
 await expect(page.locator('.detail-tables')).toContainText('Good, returned')
})
