import { test,expect } from '@playwright/test'

test.beforeEach(async({page})=>{
 await page.goto('/')
 await page.getByLabel('Tên đăng nhập',{exact:true}).fill('admin')
 await page.getByLabel('Mật khẩu',{exact:true}).fill(process.env.DEMO_PASSWORD||'HelpdeskDemo2026!')
 await page.getByRole('button',{name:'Đăng nhập'}).click()
 await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible()
})

test('search IP to asset and trace network and history without ticket UI',async({page})=>{
 await page.screenshot({path:'/tmp/helpdesk-dashboard.png',fullPage:true})
 await page.getByRole('textbox',{name:'Tìm kiếm toàn hệ thống'}).fill('192.168.20.80')
 await expect(page.locator('.search-results')).toContainText('PRN-012')
 await page.locator('.search-results a').filter({hasText:'Danh sách tài sản'}).first().click()
 await expect(page.getByRole('heading',{name:'ZT411'})).toBeVisible()
 await page.getByRole('tab',{name:'Mạng',exact:true}).click()
 await expect(page.locator('.detail-tables')).toContainText('192.168.20.80')
 await expect(page.locator('.detail-tables')).toContainText('Gi3')
 await page.getByRole('tab',{name:'Tổng quan',exact:true}).click()
 await expect(page.locator('.asset-overview-grid')).toContainText('DG-18BD')
 await expect(page.getByRole('tab')).toHaveCount(3)
 await expect(page.getByRole('button',{name:'Tickets',exact:true})).toHaveCount(0)
 await page.getByRole('tab',{name:'Lịch sử',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Lịch sử tài sản'})).toBeVisible()
})

test('Inventory history and direct Stations navigation replace legacy modules',async({page})=>{
 await page.goto('/inventory-items')
 await expect(page).toHaveURL(/\/inventory$/)
 await expect(page.getByRole('heading',{name:'Tồn kho',exact:true})).toBeVisible()
 await page.goto('/warehouses')
 await expect(page.locator('table')).toHaveCount(0)
 await expect(page.locator('.sidebar').getByRole('link',{name:'Lịch sử',exact:true})).toHaveCount(0)
 await page.locator('.sidebar').getByRole('link',{name:'Trạm làm việc',exact:true}).click()
 await expect(page).toHaveURL(/\/locations$/)
 await expect(page.locator('.sidebar').getByText('All locations',{exact:true})).toHaveCount(0)
 await page.goto('/history?tab=stock')
 await expect(page).toHaveURL(/\/inventory\?tab=history/)
 await page.goto('/tickets')
 await expect(page).toHaveURL(/\/assets$/)
})

test('all modules load and mobile navigation works',async({page})=>{
 const failures:string[]=[]
 page.on('pageerror',e=>failures.push(e.message))
 for(const path of ['assets','asset-types','locations','assignments','location-history','tickets','ip-addresses','subnets','vlans','switch-ports','maintenance','articles','reports','settings','master-data','users','audit-logs']){
  await page.goto('/'+path)
  await expect(page.locator('.main-content h1')).toBeVisible()
  await expect(page.locator('.main-content .error')).toHaveCount(0)
 }
 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 await page.getByRole('button',{name:'Mở menu'}).click()
 await expect(page.locator('.sidebar')).toBeInViewport()
 await page.locator('.sidebar').getByRole('link',{name:'Tài sản',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Danh sách tài sản'})).toBeVisible()
 await expect(page.locator('.sidebar')).not.toBeInViewport()
 await expect(page.locator('.loading')).toHaveCount(0)
 await page.screenshot({path:'/tmp/helpdesk-mobile.png',fullPage:true})
 expect(failures).toEqual([])
})

test('asset create, move, assignment, return and maintenance via UI',async({page})=>{
 const serial='UI'+String(Date.now()).slice(-8)
 const code='M1-'+serial
 await page.goto('/assets')
 await expect(page.getByRole('button',{name:'CSV'})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'XLSX'})).toBeVisible()
 await page.goto('/warehouses')
 await page.getByRole('button',{name:'Nhập Excel',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Nhập tài sản từ Excel'})).toBeVisible()
 await page.getByRole('button',{name:'Đóng'}).click()
 await page.getByRole('button',{name:'Nhập tài sản',exact:true}).click()
 let dialog=page.getByRole('dialog')
 await dialog.getByLabel('Model',{exact:false}).fill('M1')
 await dialog.getByLabel('Số sê-ri',{exact:false}).fill(serial)
 await dialog.getByLabel('Loại',{exact:false}).selectOption({label:'Laptop'})
 await expect(dialog.getByLabel('Trạng thái',{exact:false})).toBeDisabled()
 await dialog.getByLabel('Kho tiếp nhận',{exact:false}).selectOption({label:'WH-Q7 · Q7 IT Warehouse'})
 await dialog.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 await page.goto('/assets')
 await page.getByRole('textbox',{name:'Tìm trong bảng'}).fill(code)
 await page.getByRole('cell',{name:code,exact:true}).click()
 await expect(page.getByRole('heading',{name:'M1',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Xuất kho',exact:true}).click()
 dialog=page.getByRole('dialog')
 await expect(dialog.getByRole('combobox',{name:'Tài sản *',exact:true})).toBeDisabled()
 await expect(page).toHaveURL(/assets\/\d+/)
 await dialog.getByRole('combobox',{name:'Trạm nhận',exact:true}).selectOption({label:'Q7 / OUTBOUND / DG-01BD'})
 await dialog.getByRole('button',{name:'Xác nhận xuất kho'}).click()
 await expect(dialog).not.toBeVisible()
 await page.goto('/assets')
 await page.getByRole('textbox',{name:'Tìm trong bảng'}).fill(code)
 await page.getByRole('cell',{name:code,exact:true}).click()
 await expect(page.getByRole('heading',{name:'Thông tin tài sản'})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Vị trí và người phụ trách'})).toBeVisible()
 await page.getByRole('button',{name:'Điều chuyển vị trí',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Vị trí',{exact:false}).selectOption({label:'Q7 / OUTBOUND / DG-12AD'})
 await dialog.getByLabel('Lý do',{exact:false}).fill('Browser verified move')
 await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button',{name:'Cấp phát',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Người dùng',{exact:false}).selectOption({label:'Nguyen Van An'})
 await dialog.getByLabel('Tình trạng cấp phát',{exact:false}).fill('Good, tested')
 await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button',{name:'Thu hồi',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Tình trạng thu hồi',{exact:false}).fill('Good, returned')
 await dialog.getByRole('button',{name:'Lưu thao tác'}).click()
 await expect(dialog).not.toBeVisible()
 await page.locator('.asset-command-bar').getByRole('button',{name:'Bảo trì',exact:true}).click()
 dialog=page.getByRole('dialog')
 await dialog.getByLabel('Loại',{exact:false}).selectOption({label:'inspection · Kiểm tra'})
 await dialog.getByLabel('Trạng thái',{exact:false}).selectOption({label:'open · Mới'})
 await dialog.getByLabel('Vấn đề',{exact:false}).fill('Routine browser inspection')
 await dialog.getByRole('button',{name:'Lưu thay đổi'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(page.locator('.asset-title-line')).toContainText('Đang bảo trì')
 await page.getByRole('tab',{name:'Lịch sử',exact:true}).click()
 await expect(page.locator('.asset-lifecycle')).toContainText('Good, returned')
})
