"""Vietnamese display labels for exported documents; API field keys stay stable."""
FIELD_LABELS = {'action': 'Thao tác',
 'action_taken': 'Cách xử lý',
 'actions': 'Thao tác',
 'active': 'Hoạt động',
 'address': 'Địa chỉ',
 'after_state': 'Trạng thái sau',
 'allow_assignment': 'Cho phép cấp phát',
 'allow_station': 'Cho phép cấp cho trạm',
 'allow_ticket': 'Cho phép tạo phiếu hỗ trợ',
 'archived': 'Đã lưu trữ',
 'area': 'Khu vực',
 'asset': 'Tài sản',
 'asset_type': 'Loại tài sản',
 'assign': 'Cấp phát',
 'assigned_to': 'Người phụ trách',
 'author': 'Tác giả',
 'available_ips': 'IP còn trống',
 'before_state': 'Trạng thái trước',
 'bin_shelf': 'Kệ / ngăn',
 'brand': 'Hãng',
 'category': 'Phân loại',
 'cause': 'Nguyên nhân',
 'cidr': 'CIDR',
 'code': 'Mã',
 'color': 'Màu',
 'commands': 'Câu lệnh',
 'condition': 'Tình trạng',
 'condition_after': 'Tình trạng sau',
 'condition_before': 'Tình trạng trước',
 'condition_in': 'Tình trạng thu hồi',
 'condition_out': 'Tình trạng cấp phát',
 'connected_asset': 'Tài sản kết nối',
 'cost': 'Chi phí',
 'created_at': 'Ngày tạo',
 'current_assignee': 'Người phụ trách hiện tại',
 'current_assignee_id': 'ID người phụ trách hiện tại',
 'current_location': 'Vị trí hiện tại',
 'current_location_id': 'ID vị trí hiện tại',
 'current_status': 'Trạng thái hiện tại',
 'department': 'Bộ phận',
 'description': 'Mô tả',
 'diagnosis': 'Chẩn đoán',
 'dns': 'DNS',
 'due_at': 'Hạn xử lý',
 'end_at': 'Ngày kết thúc',
 'ended_at': 'Ngày kết thúc',
 'event_type': 'Loại sự kiện',
 'expected_return': 'Ngày dự kiến trả',
 'floor': 'Tầng',
 'from': 'Từ',
 'from_entity': 'Nguồn',
 'from_entity_type': 'Loại nguồn',
 'from_location': 'Vị trí trước',
 'gateway': 'Cổng mạng',
 'group': 'Nhóm',
 'handed_over_by': 'Người bàn giao',
 'handover_date': 'Ngày bàn giao',
 'has_ports': 'Có cổng mạng',
 'hostname': 'Tên máy',
 'id': 'ID',
 'interface': 'Giao diện mạng',
 'item': 'Vật tư',
 'kind': 'Cấp vị trí',
 'location': 'Vị trí',
 'mac': 'MAC',
 'maintenance': 'Bảo trì',
 'minimum_stock': 'Tồn tối thiểu',
 'mode': 'Chế độ',
 'model': 'Model',
 'move': 'Điều chuyển',
 'name': 'Tên',
 'native_vlan': 'VLAN gốc',
 'new_value': 'Giá trị sau',
 'note': 'Ghi chú',
 'notes': 'Ghi chú',
 'number': 'Mã phiếu',
 'object_id': 'Mã đối tượng',
 'object_type': 'Loại đối tượng',
 'occurred_at': 'Thời gian',
 'old_value': 'Giá trị trước',
 'operation_date': 'Thời gian',
 'operation_type': 'Loại sự kiện',
 'parent': 'Cấp trên',
 'parts_replaced': 'Linh kiện thay thế',
 'password': 'Mật khẩu',
 'performed_by': 'Người thực hiện',
 'photo_upload': 'Ảnh tài sản',
 'photo_url': 'Ảnh',
 'physical_location': 'Vị trí thực tế',
 'port': 'Cổng',
 'prefix': 'Tiền tố',
 'problem': 'Vấn đề',
 'quantity': 'Số lượng',
 'reason': 'Lý do',
 'reassign': 'Chuyển người phụ trách',
 'received_by': 'Người nhập',
 'received_date': 'Ngày nhập',
 'recipient_location': 'Trạm nhận',
 'recipient_user': 'Người nhận',
 'record': 'Bản ghi',
 'records': 'Số bản ghi',
 'resolution': 'Hướng xử lý',
 'retire': 'Ngừng sử dụng',
 'return': 'Thu hồi',
 'returned_at': 'Ngày thu hồi',
 'role': 'Vai trò',
 'serial': 'Số sê-ri',
 'since': 'Từ ngày',
 'site': 'Cơ sở',
 'source_ref': 'Tham chiếu nguồn',
 'source_vendor': 'Nguồn nhập',
 'start_at': 'Bắt đầu',
 'state': 'Trạng thái',
 'station': 'Trạm',
 'status': 'Trạng thái',
 'stock': 'Tồn kho',
 'subnet': 'Dải mạng',
 'summary': 'Tóm tắt',
 'switch': 'Switch',
 'switch_name': 'Tên switch',
 'symptoms': 'Triệu chứng',
 'tag': 'Thẻ',
 'tagged_vlans': 'VLAN gắn thẻ',
 'tags': 'Thẻ',
 'team': 'Bộ phận',
 'technician': 'Kỹ thuật viên',
 'title': 'Sự kiện',
 'to': 'Đến',
 'to_entity': 'Đích',
 'to_entity_type': 'Loại đích',
 'total_ips': 'Tổng IP',
 'track_location': 'Theo dõi vị trí',
 'track_maintenance': 'Theo dõi bảo trì',
 'track_network': 'Theo dõi mạng',
 'transaction_date': 'Ngày giao dịch',
 'transaction_type': 'Loại giao dịch',
 'transfer': 'Chuyển người phụ trách',
 'type': 'Loại',
 'unit': 'Đơn vị',
 'updated_at': 'Ngày cập nhật',
 'updated_by': 'Người cập nhật',
 'used_ips': 'IP đã dùng',
 'user': 'Người dùng',
 'username': 'Tên đăng nhập',
 'vendor': 'Nhà cung cấp',
 'vlan': 'VLAN',
 'warehouse': 'Kho',
 'warehouse_id': 'Mã kho'}

def field_label(key):
    if key in FIELD_LABELS: return FIELD_LABELS[key]
    if key.endswith('_label'): return FIELD_LABELS.get(key[:-6],key[:-6])
    if key.endswith('_id'): return 'ID '+FIELD_LABELS.get(key[:-3],key[:-3]).lower()
    return key
