import { useEffect,useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Routes,Route,NavLink,Link,useNavigate,useLocation } from 'react-router-dom'
import { LayoutDashboard,Ticket,Monitor,ArrowRightLeft,Network,Wrench,BookOpen,ChartNoAxesCombined,Settings,Search,Plus,ChevronDown,Bell,LogOut,Menu,X,Command,ShieldCheck,ArrowUpRight,LoaderCircle,Boxes,CheckCircle2 } from 'lucide-react'
import { api,queryClient,canWrite,type Row } from './api'
import { Button } from './components/ui/button'
import { Editor,type EditorState } from './components/Editor'
import { Dashboard } from './Dashboard'
import { Resources } from './Resources'
import { Detail } from './Detail'
const groups=[{label:'WORKSPACE',items:[{name:'Dashboard',path:'/',icon:LayoutDashboard},{name:'Helpdesk',path:'/tickets',icon:Ticket,children:[['All tickets','/tickets'],['My tickets','/tickets?view=my'],['Unassigned','/tickets?view=unassigned'],['Open','/tickets?status=open'],['In progress','/tickets?status=in_progress'],['Waiting','/tickets?status=waiting'],['Resolved','/tickets?status=resolved'],['Closed','/tickets?status=closed']]},{name:'Assets',path:'/assets',icon:Monitor,children:[['All assets','/assets'],['Asset types','/asset-types']]},{name:'Asset operations',path:'/assignments',icon:ArrowRightLeft,children:[['Locations','/locations'],['Assignments','/assignments'],['Returns','/assignments?view=returned'],['Movement history','/location-history']]},{name:'Network / IPAM',path:'/ip-addresses',icon:Network,children:[['IP addresses','/ip-addresses'],['Interfaces','/interfaces'],['Subnets','/subnets'],['VLANs','/vlans'],['Switches','/assets?type=Switch'],['Switch ports','/switch-ports']]},{name:'Maintenance',path:'/maintenance',icon:Wrench},{name:'Knowledge base',path:'/articles',icon:BookOpen},{name:'Reports',path:'/reports',icon:ChartNoAxesCombined}]},{label:'ADMINISTRATION',items:[{name:'Settings',path:'/settings',icon:Settings,children:[['Master data','/master-data'],['Users & roles','/users'],['Audit logs','/audit-logs']]}]}]
function Login({onSuccess}:{onSuccess:()=>void}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [pending,setPending]=useState(false);return <div className="login-page"><div className="login-story"><div className="brand"><div className="brand-mark"><Boxes size={23}/></div><div>IT Helpdesk<span>ASSET MANAGEMENT</span></div></div><div><span className="eyebrow">BUILT FOR THE PEOPLE BEHIND IT</span><h1>Everything IT.<br/>All connected.</h1><p>One workspace for your assets, your network,<br/>and the people who keep it all running.</p><div className="login-features"><span><CheckCircle2 size={18}/>Know every device</span><span><CheckCircle2 size={18}/>Resolve issues faster</span><span><CheckCircle2 size={18}/>Keep a complete history</span></div></div><span>IT Helpdesk & Asset Management System</span></div><div className="login-form"><form onSubmit={async e=>{e.preventDefault();setPending(true);setError('');try{await api('/auth/login',{method:'POST',body:JSON.stringify({username,password})});onSuccess()}catch(e){setError((e as Error).message)}finally{setPending(false)}}}><div className="login-symbol"><ShieldCheck size={26}/></div><h2>Welcome to your workspace</h2><p>Sign in to manage your IT operations.</p><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter your username" required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/></label>{error&&<p role="alert" className="error">{error}</p>}<Button disabled={pending}>{pending?<LoaderCircle size={17} className="spin"/>:null}Sign in<ArrowUpRight size={17}/></Button><small>Internal workspace · Contact your administrator for access.</small></form></div></div>}
export default function App(){
 const {data:user,isLoading,refetch}=useQuery({queryKey:['me'],queryFn:()=>api('/auth/me'),retry:false});const [editor,setEditor]=useState<EditorState|null>(null);const [quick,setQuick]=useState(false);const [mobile,setMobile]=useState(false);const [search,setSearch]=useState('');const [debounced,setDebounced]=useState('');const [notifications,setNotifications]=useState(false);const [profile,setProfile]=useState(false);const location=useLocation();const navigate=useNavigate()
 useEffect(()=>{const timer=setTimeout(()=>setDebounced(search),250);return ()=>clearTimeout(timer)},[search]);useEffect(()=>{setMobile(false);setSearch('');setQuick(false);setNotifications(false)},[location]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();document.getElementById('global-search')?.focus()}if(e.key==='Escape'){setSearch('');setQuick(false);setProfile(false);setNotifications(false)}};window.addEventListener('keydown',key);return ()=>window.removeEventListener('keydown',key)},[])
 const {data:results}=useQuery({queryKey:['search',debounced],queryFn:()=>api('/search?q='+encodeURIComponent(debounced)),enabled:debounced.length>=2&&!!user})
 const {data:dashboard}=useQuery({queryKey:['dashboard'],queryFn:()=>api('/dashboard'),enabled:!!user})
 if(isLoading)return <div className="loading full">Opening your workspace…</div>
 if(!user)return <Login onSuccess={()=>{queryClient.clear();refetch()}}/>
 const open=(s:EditorState)=>{setEditor(s);setQuick(false)}
 return <div className="app-shell">{mobile&&<div className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}<aside className={'sidebar '+(mobile?'show':'')}><Link to="/" className="brand"><div className="brand-mark"><Boxes size={23}/></div><div>IT Helpdesk<span>ASSET MANAGEMENT</span></div></Link><div className="workspace-label"><div>Q7</div><span>IT Operations<small>Internal workspace</small></span><ShieldCheck size={16}/></div><nav>{groups.map(group=><div className="nav-group" key={group.label}><span>{group.label}</span>{group.items.map(item=>{const active=item.path==='/'?location.pathname==='/':location.pathname===item.path||item.children?.some(([,path])=>(path.includes('?')?location.pathname+location.search===path:location.pathname===path));return <div key={item.name}><NavLink to={item.path} end className={'nav-item '+(active?'selected':'')}><item.icon size={18}/><span>{item.name}</span>{item.name==='Helpdesk'&&<small>{dashboard?.stats['Open tickets']||0}</small>}{item.children&&<ChevronDown className={active?'rotated':''} size={13}/>}</NavLink>{item.children&&active&&<div className="subnav">{item.children.filter(([,p])=>p!=='/users'||user.role==='ADMIN').map(([name,path])=><Link className={location.pathname+location.search===path?'active':''} key={path} to={path}>{name}</Link>)}</div>}</div>})}</div>)}</nav><div className="sidebar-bottom"><div className="status-note"><span className="live-dot"/>Workspace connected</div><button className="sidebar-user" onClick={()=>setProfile(!profile)}><span className="avatar">{user.name.split(' ').slice(-2).map((s:string)=>s[0]).join('')}</span><span>{user.name}<small>{user.role.replaceAll('_',' ')}</small></span><ChevronDown size={15}/></button></div></aside>
 <div className="main-shell"><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={21}/></button><div className="global-search"><Search size={18}/><input id="global-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search assets, tickets, IP addresses…" aria-label="Global search"/><kbd><Command size={11}/>K</kbd>{search.length>=2&&<div className="search-results"><div className="search-heading">WORKSPACE SEARCH</div>{results?.length===0&&<p>No matching records</p>}{results?.map((r:Row)=><Link to={`/${r.resource==='users'&&user.role!=='ADMIN'?'assignments':r.resource}${r.resource==='users'&&user.role!=='ADMIN'?'?user='+r.id:'/'+r.id}`} key={r.resource+r.id} onClick={()=>setSearch('')}><span className="search-type">{r.resource}</span><strong>{r.code||r.number||r.address||r.mac||r.name} {r.title||''}</strong><small>{r.name||r.hostname} {r.location_label||''} {r.asset_label||''}</small></Link>)}</div>}</div><div className="header-actions">{user.role!=='VIEWER'&&<div className="relative"><Button onClick={()=>setQuick(!quick)}><Plus size={16}/>Create<ChevronDown size={14}/></Button>{quick&&<div className="popover quick-menu">{[{name:'New ticket',resource:'tickets'},{name:'New asset',resource:'assets'},{name:'Move device',resource:'assets',operation:'move'},{name:'Assign device',resource:'assets',operation:'assign'},{name:'Return device',resource:'assets',operation:'return'},{name:'Maintenance',resource:'maintenance'},{name:'Knowledge article',resource:'articles'}].filter(x=>canWrite(user.role,x.operation?'operations':x.resource)).map(x=><button key={x.name} onClick={()=>open(x)}>{x.name}<Plus size={13}/></button>)}</div>}</div>}<div className="relative"><button className="notification-button" aria-label="Notifications" onClick={()=>setNotifications(!notifications)}><Bell size={19}/>{dashboard?.attention.length>0&&<i/>}</button>{notifications&&<div className="popover notifications"><h3>Attention required</h3>{dashboard?.attention.map((r:Row,i:number)=><Link key={i} to={`/${r.resource}/${r.id}`}><strong>{r.title}</strong><small>{r.subtitle}</small></Link>)}{dashboard?.attention.length===0&&<p>You're all caught up.</p>}</div>}</div><div className="header-divider"/><button className="avatar" aria-label="User profile" onClick={()=>setProfile(!profile)}>{user.name.split(' ').slice(-2).map((s:string)=>s[0]).join('')}</button></div></header>
 {profile&&<div className="profile-popover popover"><button className="close-profile" aria-label="Close profile" onClick={()=>setProfile(false)}><X size={15}/></button><strong>{user.name}</strong><p>{user.role} · {user.department}</p><Button variant="outline" onClick={async()=>{await api('/auth/logout',{method:'POST'});queryClient.clear();setProfile(false);navigate('/');refetch()}}><LogOut size={15}/>Sign out</Button></div>}
 <main className="main-content"><Routes><Route path="/" element={<Dashboard open={open} user={user}/>}/><Route path="/reports" element={<Resources key="reports" report open={open} user={user}/>}/><Route path="/settings" element={<SettingsPage user={user}/>}/><Route path="/:resource/:id" element={<Detail key={location.pathname} open={open} user={user}/>}/><Route path="/:resource" element={<Resources key={location.pathname+location.search} open={open} user={user}/>}/></Routes></main></div>{editor&&<Editor state={editor} onClose={()=>setEditor(null)}/>}</div>
}
function SettingsPage({user}:{user:Row}){return <><div className="page-heading"><div><span className="eyebrow">ADMINISTRATION</span><h1>Workspace settings</h1><p>Configure your IT operations workspace.</p></div></div><div className="settings-grid">{[['Master data','Statuses, priorities and categories','/master-data',Settings],['Asset types','Device capabilities and assignment rules','/asset-types',Monitor],['Locations','Sites, areas and stations','/locations',Network],...(user.role==='ADMIN'?[['Users & roles','Accounts and role-based permissions','/users',ShieldCheck]]:[]),['Audit logs','Review all operational changes','/audit-logs',BookOpen]].map(([title,description,path,Icon]:any)=><Link className="settings-card" to={path} key={path}><Icon size={24}/><h2>{title}</h2><p>{description}</p><ArrowUpRight size={17}/></Link>)}</div></>}
