import { vi,eventLabels,statusLabels } from './i18n'
import { useEffect,useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Routes,Route,Navigate,NavLink,Link,useNavigate,useLocation } from 'react-router-dom'
import { LayoutDashboard,History as HistoryIcon,Monitor,ArrowRightLeft,Network,Wrench,BookOpen,ChartNoAxesCombined,Settings,Search,Plus,ChevronDown,ChevronRight,Bell,LogOut,Menu,X,Command,ShieldCheck,ArrowUpRight,LoaderCircle,Boxes,CheckCircle2,Warehouse as WarehouseIcon } from 'lucide-react'
import { configs } from './config'
import { api,queryClient,canWrite,type Row } from './api'
import { Button } from './components/ui/button'
import { Editor,type EditorState } from './components/Editor'
import { Dashboard } from './Dashboard'
import { Resources } from './Resources'
import { Warehouse } from './Warehouse'
import { Stations } from './Stations'
import { Stock } from './Stock'
import { LegacyHistoryRedirect } from './History'
import { Detail } from './Detail'
const groups=[{label:'WORKSPACE',items:[
 {name:'Dashboard',path:'/',icon:LayoutDashboard},
 {name:'Assets',path:'/assets',icon:Monitor},
 {name:'Warehouse',path:'/warehouses',icon:WarehouseIcon},
 {name:'Inventory',path:'/inventory',icon:Boxes},
 {name:'Stations',path:'/locations',icon:Network},
 {name:'Network / IPAM',path:'/ip-addresses',icon:Network,children:[['IP addresses','/ip-addresses'],['Interfaces','/interfaces'],['Subnets','/subnets'],['VLANs','/vlans'],['Switch ports','/switch-ports']]},
 {name:'Maintenance',path:'/maintenance',icon:Wrench},
 {name:'Knowledge base',path:'/articles',icon:BookOpen},
 {name:'Reports',path:'/reports',icon:ChartNoAxesCombined}
 ]},{label:'ADMINISTRATION',items:[{name:'Settings',path:'/settings',icon:Settings,children:[['Overview','/settings'],['Asset types','/asset-types'],['Master data','/master-data'],['Users & roles','/users']]}]}]

function Login({onSuccess}:{onSuccess:()=>void}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [pending,setPending]=useState(false);return <div className="login-page"><div className="login-story"><div className="brand"><div className="brand-mark"><Boxes size={23}/></div><div>IT Helpdesk<span>QUẢN LÝ TÀI SẢN</span></div></div><div><span className="eyebrow">DÀNH CHO ĐỘI NGŨ VẬN HÀNH CNTT</span><h1>Quản lý CNTT.<br/>Kết nối toàn diện.</h1><p>Một nơi quản lý tài sản, hạ tầng mạng,<br/>và đội ngũ vận hành.</p><div className="login-features"><span><CheckCircle2 size={18}/>Nắm rõ từng thiết bị</span><span><CheckCircle2 size={18}/>Xử lý sự cố nhanh hơn</span><span><CheckCircle2 size={18}/>Lưu đầy đủ lịch sử</span></div></div><span>Hệ thống hỗ trợ và quản lý tài sản CNTT</span></div><div className="login-form"><form onSubmit={async e=>{e.preventDefault();setPending(true);setError('');try{await api('/auth/login',{method:'POST',body:JSON.stringify({username,password})});onSuccess()}catch(e){setError((e as Error).message)}finally{setPending(false)}}}><div className="login-symbol"><ShieldCheck size={26}/></div><h2>Chào mừng bạn</h2><p>Đăng nhập để quản lý hoạt động CNTT.</p><label>Tên đăng nhập<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Nhập tên đăng nhập" required/></label><label>Mật khẩu<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nhập mật khẩu" required/></label>{error&&<p role="alert" className="error">{error}</p>}<Button disabled={pending}>{pending?<LoaderCircle size={17} className="spin"/>:null}Đăng nhập<ArrowUpRight size={17}/></Button><small>Hệ thống nội bộ · Liên hệ quản trị viên để được cấp quyền.</small></form></div></div>}
export default function App(){
 const {data:user,isLoading,refetch}=useQuery({queryKey:['me'],queryFn:()=>api('/auth/me'),retry:false});const [editor,setEditor]=useState<EditorState|null>(null);const [quick,setQuick]=useState(false);const [mobile,setMobile]=useState(false);const [search,setSearch]=useState('');const [debounced,setDebounced]=useState('');const [notifications,setNotifications]=useState(false);const [profile,setProfile]=useState(false);const [openMenus,setOpenMenus]=useState<Set<string>>(new Set());const location=useLocation();const navigate=useNavigate()
 useEffect(()=>{const timer=setTimeout(()=>setDebounced(search),250);return ()=>clearTimeout(timer)},[search]);useEffect(()=>{setMobile(false);setSearch('');setQuick(false);setNotifications(false)},[location]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();document.getElementById('global-search')?.focus()}if(e.key==='Escape'){setSearch('');setQuick(false);setProfile(false);setNotifications(false)}};window.addEventListener('keydown',key);return ()=>window.removeEventListener('keydown',key)},[])
 const {data:results}=useQuery({queryKey:['search',debounced],queryFn:()=>api('/search?q='+encodeURIComponent(debounced)),enabled:debounced.length>=2&&!!user})
 const {data:dashboard}=useQuery({queryKey:['dashboard'],queryFn:()=>api('/dashboard'),enabled:!!user})
 if(isLoading)return <div className="loading full">Đang mở không gian làm việc…</div>
 if(!user)return <Login onSuccess={()=>{queryClient.clear();refetch()}}/>
 const open=(s:EditorState)=>{setEditor(s);setQuick(false)}
 return <div className="app-shell">{mobile&&<div className="sidebar-backdrop" onClick={()=>setMobile(false)}/>}<aside className={'sidebar '+(mobile?'show':'')}><Link to="/" className="brand"><div className="brand-mark"><Boxes size={23}/></div><div>IT Helpdesk<span>QUẢN LÝ TÀI SẢN</span></div></Link><div className="workspace-label"><div>Q7</div><span>Vận hành CNTT<small>Không gian nội bộ</small></span><ShieldCheck size={16}/></div><nav>{groups.map(group=><div className="nav-group" key={vi(group.label)}><span>{vi(group.label)}</span>{group.items.map(item=>{const active=item.path==='/'?location.pathname==='/':location.pathname===item.path||location.pathname.startsWith(item.path+'/')||item.children?.some(([,path])=>(path.includes('?')?location.pathname+location.search===path:location.pathname===path||location.pathname.startsWith(path+'/')))||item.path==='/inventory'&&location.pathname.startsWith('/inventory-items/');const expanded=openMenus.has(item.name);return <div key={vi(item.name)}>{item.children?<button type="button" aria-expanded={expanded} className={'nav-item nav-toggle '+(active?'selected':'')} onClick={()=>setOpenMenus(current=>{const next=new Set(current);next.has(item.name)?next.delete(item.name):next.add(item.name);return next})}><item.icon size={18}/><span>{vi(item.name)}</span><ChevronDown className={expanded?'rotated':''} size={13}/></button>:<NavLink to={item.path} end className={'nav-item '+(active?'selected':'')}><item.icon size={18}/><span>{vi(item.name)}</span></NavLink>}{item.children&&expanded&&<div className="subnav">{item.children.filter(([,p])=>p!=='/users'||user.role==='ADMIN').map(([name,path])=><Link className={location.pathname+location.search===path?'active':''} key={path} to={path}>{vi(name)}</Link>)}</div>}</div>})}</div>)}</nav><div className="sidebar-bottom"><div className="status-note"><span className="live-dot"/>Đã kết nối hệ thống</div><button className="sidebar-user" onClick={()=>setProfile(!profile)}><span className="avatar">{user.name.split(' ').slice(-2).map((s:string)=>s[0]).join('')}</span><span>{user.name}<small>{vi(user.role)}</small></span><ChevronDown size={15}/></button></div></aside>
 <div className="main-shell"><header className="topbar"><button className="mobile-menu" aria-label="Mở menu" onClick={()=>setMobile(true)}><Menu size={21}/></button><div className="global-search"><Search size={18}/><input id="global-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tài sản, vật tư, địa chỉ IP…" aria-label="Tìm kiếm toàn hệ thống"/><kbd><Command size={11}/>K</kbd>{search.length>=2&&<div className="search-results"><div className="search-heading">TÌM KIẾM</div>{results?.length===0&&<p>Không có bản ghi phù hợp</p>}{results?.map((r:Row)=><Link to={`/${r.resource==='users'&&user.role!=='ADMIN'?'assets':r.resource}${r.resource==='users'&&user.role!=='ADMIN'?'?user='+r.id:'/'+r.id}`} key={r.resource+r.id} onClick={()=>setSearch('')}><span className="search-type">{configs[r.resource]?.title||r.resource}</span><strong>{r.code||r.number||r.address||r.mac||r.name} {r.title||''}</strong><small>{r.name||r.hostname} {r.location_label||''} {r.asset_label||''}</small></Link>)}</div>}</div><div className="header-actions">{user.role!=='VIEWER'&&<div className="relative"><Button onClick={()=>setQuick(!quick)}><Plus size={16}/>Tạo mới<ChevronDown size={14}/></Button>{quick&&<div className="popover quick-menu">{[{name:'Move device',resource:'assets',operation:'move'},{name:'Assign device',resource:'assets',operation:'assign'},{name:'Return device',resource:'assets',operation:'return'},{name:'Maintenance',resource:'maintenance'},{name:'Knowledge article',resource:'articles'}].filter(x=>canWrite(user.role,x.operation?'operations':x.resource)).map(x=><button key={vi(x.name)} onClick={()=>open(x)}>{vi(x.name)}<Plus size={13}/></button>)}</div>}</div>}<div className="relative"><button className="notification-button" aria-label="Thông báo" onClick={()=>setNotifications(!notifications)}><Bell size={19}/>{dashboard?.attention.length>0&&<i/>}</button>{notifications&&<div className="popover notifications"><h3>Cần chú ý</h3>{dashboard?.attention.map((r:Row,i:number)=><Link key={i} to={`/${r.resource}/${r.id}`}><strong>{r.title}</strong><small>{r.subtitle}</small></Link>)}{dashboard?.attention.length===0&&<p>Không có mục nào cần xử lý.</p>}</div>}</div><div className="header-divider"/><button className="avatar" aria-label="Tài khoản người dùng" onClick={()=>setProfile(!profile)}>{user.name.split(' ').slice(-2).map((s:string)=>s[0]).join('')}</button></div></header>
 {profile&&<div className="profile-popover popover"><button className="close-profile" aria-label="Đóng thông tin tài khoản" onClick={()=>setProfile(false)}><X size={15}/></button><strong>{user.name}</strong><p>{vi(user.role)} · {user.department}</p><Button variant="outline" onClick={async()=>{await api('/auth/logout',{method:'POST'});queryClient.clear();setProfile(false);navigate('/');refetch()}}><LogOut size={15}/>Đăng xuất</Button></div>}
 <main className="main-content"><WorkspaceBreadcrumb/><Routes><Route path="/" element={<Dashboard open={open} user={user}/>}/><Route path="/warehouses" element={<Warehouse user={user} open={open}/>}/><Route path="/warehouses/:id" element={<Warehouse user={user} open={open}/>}/><Route path="/locations" element={<Stations user={user} open={open}/>}/><Route path="/locations/:id" element={<Stations user={user} open={open}/>}/><Route path="/inventory" element={<Stock user={user}/>}/><Route path="/inventory-items" element={<InventoryRedirect/>}/><Route path="/history" element={<LegacyHistoryRedirect/>}/><Route path="/history/:resource/:id" element={<LegacyHistoryRedirect/>}/><Route path="/asset-operations" element={<Navigate replace to="/assets"/>}/><Route path="/inventory-transactions" element={<Navigate replace to="/inventory?tab=history"/>}/><Route path="/tickets/*" element={<Navigate replace to="/assets"/>}/><Route path="/ticket-articles/*" element={<Navigate replace to="/articles"/>}/><Route path="/reports" element={<Resources key="reports" report open={open} user={user}/>}/><Route path="/settings" element={<SettingsPage user={user}/>}/><Route path="/:resource/:id" element={<Detail key={location.pathname} open={open} user={user}/>}/><Route path="/:resource" element={<Resources key={location.pathname+location.search} open={open} user={user}/>}/></Routes></main></div>{editor&&<Editor state={editor} onClose={()=>setEditor(null)}/>}</div>
}
function SettingsPage({user}:{user:Row}){return <><div className="page-heading"><div><span className="eyebrow">QUẢN TRỊ</span><h1>Cài đặt hệ thống</h1><p>Cấu hình không gian vận hành CNTT.</p></div></div><div className="settings-grid">{[['Master data','Statuses, priorities and categories','/master-data',Settings],['Asset types','Device capabilities and assignment rules','/asset-types',Monitor],['Locations','Sites, teams and stations','/locations',Network],...(user.role==='ADMIN'?[['Users & roles','Accounts and role-based permissions','/users',ShieldCheck]]:[]),['Audit logs','Changes to workspace records','/audit-logs',HistoryIcon]].map(([title,description,path,Icon]:any)=><Link className="settings-card" to={path} key={path}><Icon size={24}/><h2>{vi(title)}</h2><p>{vi(description)}</p><ArrowUpRight size={17}/></Link>)}</div></>}

function WorkspaceBreadcrumb(){
 const {pathname}=useLocation();const [resource,id]=pathname.split('/').filter(Boolean)
 const title=({warehouses:'Warehouse',locations:'Locations',reports:'Reports',settings:'Settings',inventory:'Inventory',history:'History','inventory-items':'Inventory'} as Record<string,string>)[resource]||configs[resource]?.title||'Dashboard'
 return <nav className="workspace-breadcrumb" aria-label="Đường dẫn"><Link to="/">Vận hành CNTT</Link><ChevronRight size={15}/>{id?<><Link to={'/'+resource}>{vi(title)}</Link><ChevronRight size={15}/><span aria-current="page">Chi tiết</span></>:<span aria-current="page">{vi(title)}</span>}</nav>
}

function InventoryRedirect(){const {search}=useLocation();return <Navigate replace to={'/inventory'+search}/> }
