export type Field={key:string,label?:string,type?:string,ref?:string,group?:string,required?:boolean,options?:string[]}
const f=(key:string,required=false,type='text'):Field=>({key,required,type})
const ref=(key:string,resource:string,required=true,group?:string):Field=>({key,ref:resource,required,group})
const master=(key:string,group:string)=>ref(key,'master-data',true,group)
export const configs:Record<string,{title:string,subtitle:string,fields:Field[],columns:string[]}>= {
 assets:{title:"Danh sách tài sản",subtitle:"Quản lý tập trung mọi thiết bị.",fields:[ref('type_id','asset-types'),master('status_id','asset_status'),f('brand'),f('model',true),f('serial',true),f('received_date',false,'date'),f('description',false,'textarea')],columns:['photo_url','code','type_label','model','serial','status_label','assigned_to','location_label','since','received_date']},
 'asset-types':{title:"Loại tài sản",subtitle:"Cấu hình cách quản lý từng loại thiết bị.",fields:[f('name',true),f('prefix',true),...['track_location','allow_assignment','track_network','track_maintenance','has_ports'].map(k=>f(k,false,'checkbox'))],columns:['name','prefix','track_location','allow_assignment','track_network','has_ports']},
 locations:{title:"Vị trí",subtitle:"Tổ chức theo Cơ sở → Bộ phận → Trạm.",fields:[f('name',true),{key:'kind',required:true,options:['site','team','station']},ref('parent_id','locations',false),f('active',false,'checkbox'),f('physical_location'),f('department'),f('floor'),f('area'),f('description',false,'textarea')],columns:['name','kind','parent_label','description']},
 assignments:{title:"Cấp phát thiết bị",subtitle:"Theo dõi người chịu trách nhiệm cho từng thiết bị.",fields:[],columns:['asset_label','user_label','department','created_at','expected_return','returned_at','condition_out','condition_in']},
 'location-history':{title:"Lịch sử điều chuyển",subtitle:"Lưu đầy đủ lịch sử vị trí thiết bị.",fields:[],columns:['asset_label','from_location_label','location_label','reason','technician_label','created_at','ended_at']},
 'asset-operations':{title:"Lịch sử thao tác",subtitle:"Lưu đầy đủ các sự kiện trong vòng đời tài sản.",fields:[],columns:['number','operation_type','asset_label','from_label','to_label','operation_date','performed_by_label','note']},
 warehouses:{title:"Kho",subtitle:"Quản lý kho lưu tài sản và vật tư.",fields:[f('code',true),f('name',true),ref('location_id','locations'),f('description',false,'textarea')],columns:['code','name','location_label','description']},
 'inventory-items':{title:"Vật tư",subtitle:"Theo dõi vật tư theo số lượng.",fields:[f('code',true),f('name',true),f('category',true),f('unit',true),f('minimum_stock',false,'number'),ref('warehouse_id','warehouses'),f('bin_shelf'),f('description',false,'textarea')],columns:['code','name','category','quantity','minimum_stock','unit','warehouse_label','bin_shelf']},
 vlans:{title:"VLAN",subtitle:"Quản lý và ghi chép hạ tầng mạng.",fields:[f('tag',true,'number'),f('name',true),ref('site_id','locations'),f('description',false,'textarea')],columns:['tag','name','site_label','description']},
 subnets:{title:"Dải mạng",subtitle:"Dải địa chỉ, cổng mạng và dung lượng mạng.",fields:[f('cidr',true),f('gateway'),f('dns'),ref('vlan_id','vlans'),ref('site_id','locations'),f('description',false,'textarea')],columns:['cidr','gateway','vlan_label','site_label','total_ips','used_ips','available_ips']},
 'ip-addresses':{title:"Quản lý địa chỉ IP",subtitle:"Tra cứu địa chỉ IP đến thiết bị sử dụng.",fields:[f('address',true),ref('interface_id','interfaces',false),ref('subnet_id','subnets'),master('status_id','ip_status'),f('description',false,'textarea')],columns:['address','status_label','asset_label','mac','hostname','vlan_label','location_label','switch_label','switch_name','port']},
 interfaces:{title:"Giao diện mạng",subtitle:"Quản lý địa chỉ MAC và tên máy.",fields:[ref('asset_id','assets'),f('name',true),f('mac',true),f('hostname')],columns:['asset_label','name','mac','hostname']},
 'switch-ports':{title:"Cổng switch",subtitle:"Ghi nhận kết nối vật lý và cấu hình VLAN.",fields:[ref('switch_id','assets'),f('name',true),master('mode_id','port_mode'),ref('native_vlan_id','vlans',false),{key:'tagged_vlans',type:'multiselect',ref:'vlans'},ref('connected_asset_id','assets',false),master('status_id','port_status')],columns:['switch_label','name','mode_label','native_vlan_label','tagged_vlans_label','connected_asset_label','status_label']},
 maintenance:{title:"Bảo trì",subtitle:"Theo dõi bảo trì và sửa chữa thiết bị.",fields:[ref('asset_id','assets'),master('type_id','maintenance_type'),master('status_id','maintenance_status'),f('problem',true,'textarea'),f('diagnosis',false,'textarea'),f('action_taken',false,'textarea'),ref('technician_id','users'),f('start_at',false,'datetime-local'),f('due_at',false,'datetime-local'),f('vendor'),f('cost',false,'number'),f('parts_replaced'),f('note',false,'textarea')],columns:['number','asset_label','type_label','problem','status_label','technician_label','cost','due_at']},
 articles:{title:"Kho kiến thức",subtitle:"Chia sẻ kiến thức để xử lý sự cố nhanh hơn.",fields:[f('title',true),master('category_id','kb_category'),f('summary',false,'textarea'),f('problem',false,'textarea'),f('symptoms',false,'textarea'),f('cause',false,'textarea'),f('resolution',true,'textarea'),f('commands',false,'textarea'),f('notes',false,'textarea'),f('tags'),master('status_id','article_status')],columns:['number','title','category_label','status_label','author_label','updated_at']},
 users:{title:"Người dùng và phân quyền",subtitle:"Quản lý quyền truy cập hệ thống.",fields:[f('username',true),f('name',true),f('password',true,'password'),{key:'role',required:true,options:['ADMIN','IT_MANAGER','IT_SUPPORT','VIEWER']},f('department')],columns:['username','name','role','department']},
 'master-data':{title:"Danh mục dùng chung",subtitle:"Cấu hình danh mục, trạng thái và thuật ngữ nghiệp vụ.",fields:[f('group',true),f('code',true),f('name',true),{key:'color',options:['slate','green','amber','red','blue']}],columns:['group','code','name','color']},
 'audit-logs':{title:"Nhật ký kiểm toán",subtitle:"Nhật ký thay đổi bất biến trong hệ thống.",fields:[],columns:['created_at','user_label','action','object_type','object_id','old_value','new_value']},
 'inventory-transactions':{title:"Lịch sử nhập xuất",subtitle:"Lịch sử nhập xuất kho không thể chỉnh sửa.",fields:[],columns:['number','transaction_type','warehouse_label','item_label','asset_label','quantity','recipient_user_label','recipient_location_label','transaction_date','performed_by_label']}
}
export const operationFields:Record<string,Field[]>={reassign:[ref('asset_id','assets'),{...ref('user_id','users'),label:'Người phụ trách mới'},f('reason',true,'textarea'),f('note',false,'textarea')],retire:[ref('asset_id','assets'),f('reason',true,'textarea')],move:[ref('asset_id','assets'),ref('location_id','locations'),f('reason',true,'textarea'),f('note',false,'textarea')],assign:[ref('asset_id','assets'),ref('user_id','users'),f('department'),f('expected_return',false,'datetime-local'),f('condition_out',true),f('note',false,'textarea')],return:[ref('asset_id','assets'),f('condition_in',true),f('note',false,'textarea')],transfer:[ref('asset_id','assets'),ref('user_id','users'),f('department'),f('expected_return',false,'datetime-local'),f('condition_out',true),f('condition_in',true),f('note',false,'textarea')]}
