export type Field={key:string,label?:string,type?:string,ref?:string,group?:string,required?:boolean,options?:string[]}
const f=(key:string,required=false,type='text'):Field=>({key,required,type})
const ref=(key:string,resource:string,required=true,group?:string):Field=>({key,ref:resource,required,group})
const master=(key:string,group:string)=>ref(key,'master-data',true,group)
export const configs:Record<string,{title:string,subtitle:string,fields:Field[],columns:string[]}>= {
 assets:{title:'Asset inventory',subtitle:'Every device. One reliable source of truth.',fields:[f('code',true),f('name',true),ref('type_id','asset-types'),master('status_id','asset_status'),f('brand'),f('model'),f('serial'),f('purchase_date',false,'datetime-local'),f('warranty_expiry',false,'datetime-local'),f('vendor'),f('cost',false,'number'),f('description',false,'textarea'),f('notes',false,'textarea'),f('photo')],columns:['code','name','type_label','status_label','location_label','assigned_to','serial']},
 'asset-types':{title:'Asset types',subtitle:'Configure how each type of device is managed.',fields:[f('name',true),f('prefix',true),...['track_location','allow_assignment','track_network','allow_ticket','track_maintenance','has_ports'].map(k=>f(k,false,'checkbox'))],columns:['name','prefix','track_location','allow_assignment','track_network','has_ports']},
 locations:{title:'Locations',subtitle:'Organize sites, areas and stations.',fields:[f('name',true),{key:'kind',required:true,options:['site','area','station']},ref('parent_id','locations',false),f('description',false,'textarea')],columns:['name','kind','parent_label','description']},
 assignments:{title:'Device assignments',subtitle:'Know who is responsible for every device.',fields:[],columns:['asset_label','user_label','department','created_at','expected_return','returned_at','condition_out','condition_in']},
 'location-history':{title:'Movement history',subtitle:'A complete, permanent record of device locations.',fields:[],columns:['asset_label','from_location_label','location_label','reason','technician_label','created_at','ended_at']},
 tickets:{title:'Helpdesk tickets',subtitle:'Keep your people and operations moving.',fields:[f('title',true),f('description',true,'textarea'),master('category_id','ticket_category'),f('subcategory'),master('priority_id','priority'),master('status_id','ticket_status'),ref('asset_id','assets',false),ref('location_id','locations',false),ref('technician_id','users',false),f('due_at',false,'datetime-local')],columns:['number','title','priority_label','status_label','asset_label','technician_label','due_at']},
 vlans:{title:'VLANs',subtitle:'Keep your network organized and documented.',fields:[f('tag',true,'number'),f('name',true),ref('site_id','locations'),f('description',false,'textarea')],columns:['tag','name','site_label','description']},
 subnets:{title:'Subnets',subtitle:'Address space, gateways and network capacity.',fields:[f('cidr',true),f('gateway'),f('dns'),ref('vlan_id','vlans'),ref('site_id','locations'),f('description',false,'textarea')],columns:['cidr','gateway','vlan_label','site_label','total_ips','used_ips','available_ips']},
 'ip-addresses':{title:'IP address management',subtitle:'Trace an IP address all the way to its device.',fields:[f('address',true),ref('interface_id','interfaces',false),ref('subnet_id','subnets'),master('status_id','ip_status'),f('description',false,'textarea')],columns:['address','status_label','asset_label','mac','hostname','vlan_label','location_label','switch_label','switch_name','port']},
 interfaces:{title:'Network interfaces',subtitle:'Manage device MAC addresses and hostnames.',fields:[ref('asset_id','assets'),f('name',true),f('mac',true),f('hostname')],columns:['asset_label','name','mac','hostname']},
 'switch-ports':{title:'Switch ports',subtitle:'Document physical connections and VLAN configuration.',fields:[ref('switch_id','assets'),f('name',true),master('mode_id','port_mode'),ref('native_vlan_id','vlans',false),{key:'tagged_vlans',type:'multiselect',ref:'vlans'},ref('connected_asset_id','assets',false),master('status_id','port_status')],columns:['switch_label','name','mode_label','native_vlan_label','tagged_vlans_label','connected_asset_label','status_label']},
 maintenance:{title:'Maintenance',subtitle:'Keep equipment healthy and repairs on track.',fields:[ref('asset_id','assets'),master('type_id','maintenance_type'),master('status_id','maintenance_status'),f('problem',true,'textarea'),f('diagnosis',false,'textarea'),f('action_taken',false,'textarea'),ref('technician_id','users'),f('start_at',false,'datetime-local'),f('due_at',false,'datetime-local'),f('vendor'),f('cost',false,'number'),f('parts_replaced'),f('note',false,'textarea'),ref('ticket_id','tickets',false)],columns:['number','asset_label','type_label','problem','status_label','technician_label','cost','due_at']},
 articles:{title:'Knowledge base',subtitle:'Shared knowledge. Faster resolutions.',fields:[f('title',true),master('category_id','kb_category'),f('summary',false,'textarea'),f('problem',false,'textarea'),f('symptoms',false,'textarea'),f('cause',false,'textarea'),f('resolution',true,'textarea'),f('commands',false,'textarea'),f('notes',false,'textarea'),f('tags'),master('status_id','article_status')],columns:['number','title','category_label','status_label','author_label','updated_at']},
 users:{title:'Users & roles',subtitle:'Manage access to your IT workspace.',fields:[f('username',true),f('name',true),f('password',true,'password'),{key:'role',required:true,options:['ADMIN','IT_MANAGER','IT_SUPPORT','VIEWER']},f('department')],columns:['username','name','role','department']},
 'master-data':{title:'Master data',subtitle:'Configure categories, statuses and operational terminology.',fields:[f('group',true),f('code',true),f('name',true),{key:'color',options:['slate','green','amber','red','blue']}],columns:['group','code','name','color']},
 'audit-logs':{title:'Audit logs',subtitle:'An immutable trail of changes across your workspace.',fields:[],columns:['created_at','user_label','action','object_type','object_id','old_value','new_value']},
 'ticket-articles':{title:'Link knowledge article',subtitle:'',fields:[ref('ticket_id','tickets'),ref('article_id','articles')],columns:['ticket_label','article_label']}
}
export const operationFields:Record<string,Field[]>={move:[ref('asset_id','assets'),ref('location_id','locations'),f('reason',true,'textarea'),f('note',false,'textarea')],assign:[ref('asset_id','assets'),ref('user_id','users'),f('department'),f('expected_return',false,'datetime-local'),f('condition_out',true),f('note',false,'textarea')],return:[ref('asset_id','assets'),f('condition_in',true),f('note',false,'textarea')],transfer:[ref('asset_id','assets'),ref('user_id','users'),f('department'),f('expected_return',false,'datetime-local'),f('condition_out',true),f('condition_in',true),f('note',false,'textarea')]}
