import { vi,eventLabels,statusLabels } from './i18n'
import { useQuery } from '@tanstack/react-query'
import { Link,useNavigate } from 'react-router-dom'
import { Monitor,ArrowUpRight,ArrowRight,CalendarDays,Activity,AlertCircle,MapPin,PackageCheck,Wrench,Boxes } from 'lucide-react'
import { api,formatDate,type Row } from './api'
import { Button } from './components/ui/button'
import { Badge } from './components/DataTable'
import type { EditorState } from './components/Editor'

export function Dashboard({open,user}:{open:(s:EditorState)=>void,user:Row}){
 const {data,error,isLoading}=useQuery({queryKey:['dashboard'],queryFn:()=>api('/dashboard')});const navigate=useNavigate()
 if(isLoading)return <div className="loading">Đang tải không gian làm việc…</div>;if(error)return <div className="error">{error.message}</div>
 const stats=data.stats;const icons=[Monitor,PackageCheck,Activity,PackageCheck,Boxes,Wrench,AlertCircle,Boxes,Wrench]
 const links=['/assets','/assets?status=available','/assets?status=in_use','/assets?view=assigned','/inventory?tab=assets','/assets?status=maintenance','/assets?status=retired','/inventory?tab=consumables','/maintenance?view=active']
 return <><div className="page-heading"><div><div className="eyebrow">QUẢN LÝ TÀI SẢN CNTT</div><h1>Tổng quan</h1><p>Chào mừng trở lại, {user.name.split(' ').at(-1)}. Đây là tình hình tài sản hiện tại.</p></div><div className="heading-actions"><span className="date-pill"><CalendarDays size={15}/>{new Date().toLocaleDateString('vi-VN',{day:'numeric',month:'short',year:'numeric'})}</span><Button variant="outline" onClick={()=>navigate('/reports')}>Xem báo cáo<ArrowUpRight size={16}/></Button></div></div>
 <div className="welcome-strip"><div className="live-dot"/><strong>Danh sách tài sản đã được kết nối.</strong><span>Theo dõi thiết bị, điều chuyển và hàng tồn kho.</span><Link to="/assets">Khám phá tài sản <ArrowRight size={15}/></Link></div>
 <div className="stats-grid">{Object.entries(stats).map(([name,value],i)=>{const Icon=icons[i%icons.length];return <button className="stat-card" onClick={()=>navigate(links[i]||'/assets')} key={name}><div className="stat-top"><span>{vi(name)}</span><Icon size={17}/></div><div className="stat-number">{String(value)}<ArrowUpRight size={17}/></div></button>})}</div>
 <div className="dashboard-row"><section className="panel"><div className="panel-heading"><div><h2>Thao tác tài sản gần đây</h2><p>Các sự kiện mới nhất trong vòng đời tài sản</p></div><Link to="/assets">Xem tài sản<ArrowUpRight size={14}/></Link></div><div className="table-scroll"><table><thead><tr><th>Thao tác</th><th>Tài sản</th><th>Từ</th><th>Đến</th><th>Ngày</th></tr></thead><tbody>{data.operations.slice(0,6).map((r:Row)=><tr className="clickable" key={r.id} onClick={()=>navigate('/assets/'+r.asset_id)}><td><Badge>{r.operation_type}</Badge></td><td><strong className="table-title">{r.asset_label||r.asset_id}</strong></td><td>{r.from_label||'—'}</td><td>{r.to_label||'—'}</td><td>{formatDate(r.operation_date)}</td></tr>)}</tbody></table></div></section><section className="panel attention"><div className="panel-heading"><div><h2><AlertCircle size={17}/>Cần chú ý</h2><p>Tài sản và phiếu bảo trì cần xem xét</p></div><span className="count-pill">{data.attention.length}</span></div><div className="attention-list">{data.attention.slice(0,5).map((r:Row,i:number)=><Link to={`/${r.resource}/${r.id}`} key={i}><span className="attention-icon"><AlertCircle size={16}/></span><div><strong>{r.title}</strong><span>{r.subtitle}</span></div><ArrowRight size={15}/></Link>)}{!data.attention.length&&<p className="empty">Không có mục nào cần xử lý.</p>}</div></section></div>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><div><h2>Tổng quan tài sản</h2><p>Phân bố theo loại và trạng thái tài sản</p></div><Monitor size={18}/></div><div className="asset-bars">{Object.entries(data.asset_type).map(([name,count])=><button key={name} onClick={()=>navigate('/assets?q='+encodeURIComponent(name))}><span>{vi(name)}</span><div><i style={{width:`${Number(count)/Math.max(...Object.values(data.asset_type).map(Number),1)*100}%`}}/></div><strong>{String(count)}</strong></button>)}</div></section><section className="panel quick-panel"><div className="panel-heading"><div><h2>Thao tác nhanh</h2><p>Thao tác quản lý tài sản thường dùng</p></div></div><div>{[{title:'Open warehouse',sub:'Receive assets and consumables',icon:Monitor,resource:'assets'},{title:'Move a device',sub:'Update its current location',icon:MapPin,operation:'move',resource:'assets'},{title:'Start maintenance',sub:'Record repair or inspection',icon:Wrench,resource:'maintenance'}].filter(a=>user.role!=='VIEWER'||a.title==='Open warehouse').map(a=><button key={vi(a.title)} onClick={()=>a.title==='Open warehouse'?navigate('/warehouses'):open({resource:a.resource!,operation:a.operation})}><a.icon size={19}/><div><strong>{vi(a.title)}</strong><span>{vi(a.sub)}</span></div><ArrowRight size={17}/></button>)}</div></section></div>
 <div className="dashboard-bottom">{[['Asset statuses','asset_status','assets','status'],['Current locations','asset_location','assets','location']].map(([title,key,resource,filter])=><section className="panel" key={key}><div className="panel-heading"><h2>{vi(title)}</h2></div><div className="chart-legend compact">{Object.entries(data[key]).map(([name,count])=><button key={name} onClick={()=>navigate(`/${resource}?${filter}=${encodeURIComponent(name)}`)}><span>{vi(name)}</span><strong>{String(count)}</strong><ArrowUpRight size={14}/></button>)}</div></section>)}</div>
 <footer className="page-footer">Quản lý tài sản CNTT<span><span className="live-dot"/>Đã kết nối hệ thống</span></footer></>
}
