import { useQuery } from '@tanstack/react-query'
import { Link,useNavigate } from 'react-router-dom'
import { Monitor,ArrowUpRight,ArrowRight,CalendarDays,Activity,AlertCircle,MapPin,PackageCheck,Wrench,Boxes } from 'lucide-react'
import { api,formatDate,type Row } from './api'
import { Button } from './components/ui/button'
import { Badge } from './components/DataTable'
import type { EditorState } from './components/Editor'

export function Dashboard({open,user}:{open:(s:EditorState)=>void,user:Row}){
 const {data,error,isLoading}=useQuery({queryKey:['dashboard'],queryFn:()=>api('/dashboard')});const navigate=useNavigate()
 if(isLoading)return <div className="loading">Loading your workspace…</div>;if(error)return <div className="error">{error.message}</div>
 const stats=data.stats;const icons=[Monitor,PackageCheck,Activity,PackageCheck,Boxes,Wrench,AlertCircle,Boxes,Wrench]
 const links=['/assets','/assets?status=available','/assets?status=active','/assignments?view=active','/assets?location=warehouse','/assets?status=repair','/assets?status=broken','/inventory-items','/maintenance?view=active']
 return <><div className="page-heading"><div><div className="eyebrow">IT ASSET OPERATIONS</div><h1>Dashboard</h1><p>Welcome back, {user.name.split(' ').at(-1)}. Here's your current inventory state.</p></div><div className="heading-actions"><span className="date-pill"><CalendarDays size={15}/>{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span><Button variant="outline" onClick={()=>navigate('/reports')}>View reports<ArrowUpRight size={16}/></Button></div></div>
 <div className="welcome-strip"><div className="live-dot"/><strong>Your asset register is connected.</strong><span>Track every device, movement and stock item.</span><Link to="/assets">Explore assets <ArrowRight size={15}/></Link></div>
 <div className="stats-grid">{Object.entries(stats).map(([name,value],i)=>{const Icon=icons[i%icons.length];return <button className="stat-card" onClick={()=>navigate(links[i]||'/assets')} key={name}><div className="stat-top"><span>{name}</span><Icon size={17}/></div><div className="stat-number">{String(value)}<ArrowUpRight size={17}/></div><span className="stat-note">View details</span></button>})}</div>
 <div className="dashboard-row"><section className="panel"><div className="panel-heading"><div><h2>Recent asset operations</h2><p>The latest lifecycle events across your inventory</p></div><Link to="/asset-operations">View history<ArrowUpRight size={14}/></Link></div><div className="table-scroll"><table><thead><tr><th>Operation</th><th>Asset</th><th>From</th><th>To</th><th>Date</th></tr></thead><tbody>{data.operations.slice(0,6).map((r:Row)=><tr className="clickable" key={r.id} onClick={()=>navigate('/assets/'+r.asset_id)}><td><Badge>{r.operation_type}</Badge></td><td><strong className="table-title">{r.asset_label||r.asset_id}</strong></td><td>{r.from_label||'—'}</td><td>{r.to_label||'—'}</td><td>{formatDate(r.operation_date)}</td></tr>)}</tbody></table></div></section><section className="panel attention"><div className="panel-heading"><div><h2><AlertCircle size={17}/>Attention required</h2><p>Assets and maintenance needing review</p></div><span className="count-pill">{data.attention.length}</span></div><div className="attention-list">{data.attention.slice(0,5).map((r:Row,i:number)=><Link to={`/${r.resource}/${r.id}`} key={i}><span className="attention-icon"><AlertCircle size={16}/></span><div><strong>{r.title}</strong><span>{r.subtitle}</span></div><ArrowRight size={15}/></Link>)}{!data.attention.length&&<p className="empty">You're all caught up.</p>}</div></section></div>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><div><h2>Asset overview</h2><p>Inventory by type and lifecycle status</p></div><Monitor size={18}/></div><div className="asset-bars">{Object.entries(data.asset_type).map(([name,count])=><button key={name} onClick={()=>navigate('/assets?q='+encodeURIComponent(name))}><span>{name}</span><div><i style={{width:`${Number(count)/Math.max(...Object.values(data.asset_type).map(Number),1)*100}%`}}/></div><strong>{String(count)}</strong></button>)}</div></section><section className="panel quick-panel"><div className="panel-heading"><div><h2>Quick actions</h2><p>Common inventory operations</p></div></div><div>{[{title:'Register an asset',sub:'Add a device to inventory',icon:Monitor,resource:'assets'},{title:'Move a device',sub:'Update its current location',icon:MapPin,operation:'move',resource:'assets'},{title:'Start maintenance',sub:'Record repair or inspection',icon:Wrench,resource:'maintenance'}].filter(a=>user.role!=='VIEWER'||a.title==='Register an asset').map(a=><button key={a.title} onClick={()=>open({resource:a.resource!,operation:a.operation})}><a.icon size={19}/><div><strong>{a.title}</strong><span>{a.sub}</span></div><ArrowRight size={17}/></button>)}</div></section></div>
 <div className="dashboard-bottom">{[['Asset statuses','asset_status','assets','status'],['Current locations','asset_location','assets','location']].map(([title,key,resource,filter])=><section className="panel" key={key}><div className="panel-heading"><h2>{title}</h2></div><div className="chart-legend compact">{Object.entries(data[key]).map(([name,count])=><button key={name} onClick={()=>navigate(`/${resource}?${filter}=${encodeURIComponent(name)}`)}><span>{name}</span><strong>{String(count)}</strong><ArrowUpRight size={14}/></button>)}</div></section>)}</div>
 <footer className="page-footer">IT Asset Management<span><span className="live-dot"/>Connected to your workspace</span></footer></>
}
