import { useQuery } from '@tanstack/react-query'
import { Link,useNavigate } from 'react-router-dom'
import { Monitor,Ticket,Clock3,Wrench,ArrowUpRight,ArrowRight,CheckCircle2,Box,CalendarDays,Activity,AlertCircle,MapPin,UserCheck } from 'lucide-react'
import { api,formatDate,type Row } from './api'
import { Button } from './components/ui/button'
import { Badge } from './components/DataTable'
import type { EditorState } from './components/Editor'
export function Dashboard({open,user}:{open:(s:EditorState)=>void,user:Row}){
 const {data,error,isLoading}=useQuery({queryKey:['dashboard'],queryFn:()=>api('/dashboard')});const navigate=useNavigate()
 if(isLoading)return <div className="loading">Loading your workspace…</div>;if(error)return <div className="error">{error.message}</div>
 const stats=data.stats;const icons=[Monitor,Box,CheckCircle2,Wrench,Ticket,Activity,Clock3,CheckCircle2,Wrench,UserCheck]
 const statLinks=['/assets','/assets?status=in_use','/assets?status=available','/assets?status=repair','/tickets?view=open','/tickets?status=in_progress','/tickets?view=overdue','/tickets?view=resolved-today','/maintenance?view=active','/assignments?view=active']
 return <><div className="page-heading"><div><div className="eyebrow">YOUR OPERATIONS AT A GLANCE</div><h1>Dashboard</h1><p>Welcome back, {user.name.split(' ').at(-1)}. Here's what's happening today.</p></div><div className="heading-actions"><span className="date-pill"><CalendarDays size={15}/>{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span><Button variant="outline" onClick={()=>navigate('/reports')}>View reports<ArrowUpRight size={16}/></Button></div></div>
 <div className="welcome-strip"><div className="live-dot"/><strong>Your workspace, connected.</strong><span>Assets, people and support — all in one place.</span><Link to="/assets">Explore inventory <ArrowRight size={15}/></Link></div>
 <div className="stats-grid">{Object.entries(stats).map(([name,value],i)=>{const Icon=icons[i];return <button className="stat-card" onClick={()=>navigate(statLinks[i])} key={name}><div className="stat-top"><span>{name}</span><Icon size={17}/></div><div className="stat-number">{String(value)}<ArrowUpRight size={17}/></div><span className={'stat-note '+(i===6&&Number(value)>0?'text-red':'')}>{i===0?'Across all locations':i===6?'Needs your attention':i===7?'Back on track':'View details'}</span></button>})}</div>
 <div className="dashboard-row"><section className="panel ticket-chart"><div className="panel-heading"><div><h2>Ticket overview</h2><p>Support workload by current status</p></div><Link to="/tickets">View all<ArrowUpRight size={14}/></Link></div><div className="donut-layout"><div className="donut" style={{background:donutBackground(data.ticket_status)}}><div><strong>{Object.values(data.ticket_status).reduce((a:any,b:any)=>a+b,0) as number}</strong><span>Total tickets</span></div></div><div className="chart-legend">{Object.entries(data.ticket_status).map(([name,count],i)=><button key={name} onClick={()=>navigate('/tickets?status='+name.toLowerCase().replaceAll(' ','_'))}><i style={{background:colors[i%colors.length]}}/><span>{name}</span><strong>{String(count)}</strong></button>)}</div></div></section>
 <section className="panel trend-panel"><div className="panel-heading"><div><h2>Ticket activity</h2><p>A look at the last 7 days</p></div><span className="badge slate">This week</span></div><div className="trend-legend"><span><i style={{background:'#247d68'}}/>Created</span><span><i style={{background:'#c6dcd4'}}/>Resolved</span></div><div className="bar-chart">{data.trend.map((r:Row)=>{const max=Math.max(...data.trend.map((x:Row)=>Math.max(x.created,x.resolved)),1);return <button className="bar-group" key={r.date} onClick={()=>navigate('/tickets?q='+r.date)} title={`${r.date}: ${r.created} created, ${r.resolved} resolved`}><div><span style={{height:`${Math.max(r.created/max*100,2)}%`}}/><span style={{height:`${Math.max(r.resolved/max*100,2)}%`}}/></div><small>{new Date(r.date).toLocaleDateString('en-US',{weekday:'short'})}</small></button>})}</div></section>
 <section className="panel attention"><div className="panel-heading"><div><h2><AlertCircle size={17}/>Attention required</h2><p>A few things that need a closer look</p></div><span className="count-pill">{data.attention.length}</span></div><div className="attention-list">{data.attention.slice(0,4).map((r:Row,i:number)=><Link to={`/${r.resource}/${r.id}`} key={i}><span className="attention-icon"><AlertCircle size={16}/></span><div><strong>{r.title}</strong><span>{r.subtitle}</span></div><ArrowRight size={15}/></Link>)}{!data.attention.length&&<p className="empty">You're all caught up.</p>}</div></section></div>
 <div className="dashboard-bottom"><section className="panel recent-tickets"><div className="panel-heading"><div><h2>Recent tickets</h2><p>The latest requests from your team</p></div><Link to="/tickets">All tickets <ArrowRight size={14}/></Link></div><div className="table-scroll"><table><thead><tr><th>Ticket / Subject</th><th>Asset</th><th>Priority</th><th>Status</th></tr></thead><tbody>{data.recent_tickets.slice(0,5).map((t:Row)=><tr className="clickable" key={t.id} onClick={()=>navigate('/tickets/'+t.id)}><td><small className="mono muted">{t.number}</small><strong className="table-title">{t.title}</strong></td><td><span className="asset-tag">{t.asset_label||'—'}</span></td><td><Badge>{t.priority_label}</Badge></td><td><Badge>{t.status_label}</Badge></td></tr>)}</tbody></table></div></section>
 <section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Your workspace's latest updates</p></div><Link to="/audit-logs"><ArrowUpRight size={17}/></Link></div><div className="activity-list">{data.activities.slice(0,5).map((r:Row)=><Link key={r.id} to={`/${r.object_type}/${r.object_id}`}><div className="activity-icon"><Activity size={15}/></div><div><strong>{r.new_value?.code||r.new_value?.number||r.new_value?.name||r.object_type} <span>{r.action}</span></strong><p>{r.user_label} · {formatDate(r.created_at)}</p></div></Link>)}</div></section></div>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-heading"><div><h2>Asset overview</h2><p>Inventory across device types</p></div><Monitor size={18}/></div><div className="asset-bars">{Object.entries(data.asset_type).map(([name,count])=><button key={name} onClick={()=>navigate('/assets?type='+encodeURIComponent(name))}><span>{name}</span><div><i style={{width:`${Number(count)/Math.max(...Object.values(data.asset_type).map(Number))*100}%`}}/></div><strong>{String(count)}</strong></button>)}</div></section><section className="panel quick-panel"><div className="panel-heading"><div><h2>Quick actions</h2><p>Less clicking. More getting things done.</p></div></div><div>{[{title:'Create a ticket',sub:'Get an issue on our radar',icon:Ticket,resource:'tickets'},{title:'Find a device',sub:'Search your asset inventory',icon:Monitor,path:'/assets'},{title:'Move a device',sub:'Keep locations up to date',icon:MapPin,operation:'move',resource:'assets'}].filter(a=>user.role!=='VIEWER'||a.path).map(a=><button key={a.title} onClick={()=>a.path?navigate(a.path):open({resource:a.resource!,operation:a.operation})}><a.icon size={19}/><div><strong>{a.title}</strong><span>{a.sub}</span></div><ArrowRight size={17}/></button>)}</div></section></div>
 <div className="dashboard-bottom">{[['Ticket priorities','ticket_priority','tickets','priority'],['Ticket categories','ticket_category','tickets','category'],['Asset statuses','asset_status','assets','status'],['Asset locations','asset_location','assets','location']].map(([title,key,resource,filter])=><section className="panel" key={key}><div className="panel-heading"><h2>{title}</h2></div><div className="chart-legend compact">{Object.entries(data[key]).map(([name,count])=><button key={name} onClick={()=>navigate(`/${resource}?${filter}=${encodeURIComponent(name)}`)}><span>{name}</span><strong>{String(count)}</strong><ArrowUpRight size={14}/></button>)}</div></section>)}</div>
 <footer className="page-footer">IT Helpdesk & Asset Management<span><span className="live-dot"/>Connected to your workspace</span></footer></>
}
const colors=['#267963','#85b8a2','#d9ad63','#94a7c0','#c7dcd1','#deded6','#657e73']
function donutBackground(data:Record<string,number>){const total=Object.values(data).reduce((a,b)=>a+b,0)||1;let start=0;return 'conic-gradient('+Object.values(data).map((v,i)=>{const from=start;start+=v/total*100;return `${colors[i%colors.length]} ${from}% ${start}%`}).join(',')+')'}
