import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useNavigate,useParams,useSearchParams,Link } from 'react-router-dom'
import { Plus,Download,BookOpen,ArrowUpRight,SlidersHorizontal } from 'lucide-react'
import type { SortingState } from '@tanstack/react-table'
import { api,canWrite,label,type Row } from './api'
import { configs } from './config'
import { DataTable,Badge } from './components/DataTable'
import { Button } from './components/ui/button'
import type { EditorState } from './components/Editor'
export function Resources({user,open,report=false}:{user:Row,open:(s:EditorState)=>void,report?:boolean}){
 const {resource:routeResource}=useParams();const [params]=useSearchParams();const [reportResource,setReportResource]=useState('assets');const resource=report?reportResource:routeResource!;const config=configs[resource];const navigate=useNavigate()
 const [q,setQ]=useState(params.get('q')||'');const [page,setPage]=useState(1);const [sorting,setSorting]=useState<SortingState>([]);const [filterValues,setFilterValues]=useState<Row>({});const [groupBy,setGroupBy]=useState('');const [showFilters,setShowFilters]=useState(false)
 const {data:meta}=useQuery({queryKey:['meta'],queryFn:()=>api('/meta')})
 const filters:Row={...filterValues};const group=resource==='assets'?'asset_status':resource==='tickets'?'ticket_status':resource==='maintenance'?'maintenance_status':resource==='articles'?'article_status':resource==='ip-addresses'?'ip_status':null
 for(const key of ['status','priority','category']){const value=params.get(key);if(value&&meta){const item=meta['master-data'].find((r:Row)=>(r.code===value||r.name===value)&&(key!=='status'||r.group===group));if(item)filters[key+'_id']=item.id}}
 if(params.get('type')&&meta){const item=meta['asset-types'].find((r:Row)=>r.name===params.get('type'));if(item)filters.type_id=item.id}
 if(params.get('user')&&resource==='assignments')filters.user_id=Number(params.get('user'))
 if(params.get('view')==='my')filters.technician_id=user.id
 if(params.get('view')==='unassigned')filters.technician_id=null
 if(params.get('view')==='active'&&resource==='assignments')filters.returned_at=null
 if(params.get('view')==='active'&&resource==='maintenance')filters.end_at=null
 const qs=new URLSearchParams({q,filters:JSON.stringify(filters),page:String(page),page_size:'20',sort:sorting[0]?.id||'id',direction:sorting[0]?.desc===false?'asc':'desc'})
 if(params.get('view'))qs.set('view',params.get('view')!)
 if(params.get('location'))qs.set('location',params.get('location')!)
 const {data,error,isLoading}=useQuery({queryKey:['list',resource,qs.toString()],queryFn:()=>api(`/${resource}?${qs}`),enabled:!!config})
 const {data:summary}=useQuery({queryKey:['report-summary',resource,qs.toString(),groupBy],queryFn:()=>api(`/reports/${resource}/summary?${qs}&group_by=${groupBy}`),enabled:report&&!!config})
 if(!config)return <div className="empty"><h1>Page not found</h1><Link to="/">Return to dashboard</Link></div>
 const rows=data?.items||[]
 const exportData=(format:string)=>{const query=new URLSearchParams(qs);query.set('format',format);window.location.href=`/api/reports/${resource}/export?${query}`}
 return <><div className="page-heading"><div><span className="eyebrow">{report?'INSIGHTS & EXPORTS':resource==='assets'?'YOUR CONNECTED INVENTORY':'IT OPERATIONS'}</span><h1>{report?'Reports':config.title}{!report&&data&&<span className="title-count">{data.total}</span>}</h1><p>{report?'Explore operational data and export the records you need.':config.subtitle}</p></div><div className="heading-actions"><Button variant="outline" onClick={()=>exportData('csv')}><Download size={16}/>CSV</Button><Button variant="outline" onClick={()=>exportData('xlsx')}>XLSX</Button>{!report&&config.fields.length>0&&canWrite(user.role,resource)&&<Button onClick={()=>open({resource})}><Plus size={16}/>Create {resource==='assets'?'asset':resource==='tickets'?'ticket':'record'}</Button>}{resource==='assignments'&&canWrite(user.role,'operations')&&<Button onClick={()=>open({resource:'assets',operation:'assign'})}><Plus size={16}/>Assign device</Button>}{resource==='location-history'&&canWrite(user.role,'operations')&&<Button onClick={()=>open({resource:'assets',operation:'move'})}><Plus size={16}/>Move device</Button>}</div></div>
 {report&&<div className="report-tabs">{['assets','assignments','tickets','ip-addresses','subnets','switch-ports','maintenance','articles','location-history'].map(r=><button className={resource===r?'active':''} key={r} onClick={()=>{setReportResource(r);setFilterValues({});setPage(1);setQ('');setSorting([])}}>{configs[r].title}</button>)}</div>}
 {resource==='tickets'&&!report&&<div className="view-tabs">{[['All tickets',''],['My tickets','my'],['Unassigned','unassigned'],['Open','open'],['Overdue','overdue'],['Resolved today','resolved-today']].map(([name,view])=><Link className={(params.get('view')||'')===view?'active':''} to={'/tickets'+(view?'?view='+view:'')} key={name}>{name}</Link>)}</div>}
 {report&&summary&&<><div className="report-metrics">{Object.entries(summary.totals).map(([name,value])=><div className="panel" key={name}><span>{name}</span><strong>{String(value)}</strong></div>)}<label>Group by<select value={groupBy} onChange={e=>setGroupBy(e.target.value)}><option value="">All records</option>{config.columns.filter(c=>c.endsWith('_label')||['department','assigned_to'].includes(c)).map(c=><option key={c} value={c}>{label(c.replace('_label',''))}</option>)}</select></label></div>{groupBy&&<div className="report-groups">{summary.groups.map((g:Row)=><span key={g.group}>{g.group}<strong>{g.count}</strong>{resource==='maintenance'&&<small>Cost: {g.cost}</small>}</span>)}</div>}</>}
 {showFilters&&<div className="filter-panel">{config.fields.filter(f=>f.ref&&f.type!=='multiselect').map(f=><label key={f.key}>{label(f.key.replace('_id',''))}<select value={filterValues[f.key]??''} onChange={e=>{const next={...filterValues};if(e.target.value)next[f.key]=Number(e.target.value);else delete next[f.key];setFilterValues(next);setPage(1)}}><option value="">All</option>{(meta?.[f.ref!]||[]).filter((r:Row)=>!f.group||r.group===f.group).map((r:Row)=><option key={r.id} value={r.id}>{r.name||r.code||r.number||r.cidr}</option>)}</select></label>)}{resource==='assignments'&&<label>Assigned to<select value={filterValues.user_id||''} onChange={e=>setFilterValues(e.target.value?{user_id:Number(e.target.value)}:{})}><option value="">All users</option>{meta?.users.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}<Button variant="ghost" onClick={()=>{setFilterValues({});navigate('/'+(report?'reports':resource));setQ('');setPage(1)}}>Reset filters</Button></div>}
 {error&&<div className="error">{error.message}</div>}{isLoading?<div className="loading">Loading records…</div>:resource==='articles'&&!report?<><div className="kb-search"><input placeholder="Search knowledge articles…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div><div className="article-grid">{rows.map((r:Row)=><Link to={'/articles/'+r.id} className="article-card" key={r.id}><div className="article-icon"><BookOpen size={23}/></div><Badge>{r.category_label}</Badge><h2>{r.title}</h2><p>{r.summary}</p><footer><span>{r.number}</span><ArrowUpRight size={18}/></footer></Link>)}</div><div className="pagination"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={page*20>=data.total} onClick={()=>setPage(page+1)}>Next</Button></div></>:<DataTable rows={rows} columns={config.columns} onRow={r=>navigate(`/${resource}/${r.id}`)} q={q} setQ={s=>{setQ(s);setPage(1)}} total={data?.total} page={page} setPage={setPage} sorting={sorting} setSorting={setSorting} toolbar={<Button variant="outline" size="sm" onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={15}/>Filters {Object.keys(filters).length>0&&`(${Object.keys(filters).length})`}</Button>}/>}
 </>
}
