import { vi,eventLabels,statusLabels } from './i18n'
import { LocationPath } from './components/LocationPath'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { Building2,Users,Monitor,ChevronDown,ChevronRight,Search,Plus,Pencil,Network,Info,Camera,MapPin } from 'lucide-react'
import { api,canWrite,formatDate,queryClient,type Row } from './api'
import { Button } from './components/ui/button'
import { DataTable,Badge } from './components/DataTable'
import type { EditorState } from './components/Editor'
import { configs } from './config'

export function Stations({user,open}:{user:Row,open:(s:EditorState)=>void}){
 const {id}=useParams();const navigate=useNavigate();const [q,setQ]=useState('');const [status,setStatus]=useState('all');const [collapsed,setCollapsed]=useState<Set<number>>(new Set());const [tab,setTab]=useState('Overview');const [addMenu,setAddMenu]=useState(false);const [uploadError,setUploadError]=useState('');const [uploading,setUploading]=useState(false)
 const {data:meta,error:metaError}=useQuery({queryKey:['meta'],queryFn:()=>api('/meta')})
 const locations:Row[]=meta?.locations||[];const stations=locations.filter(l=>l.kind==='station');const selectedId=Number(id||stations[0]?.id||locations[0]?.id||0)
 const {data,error,isLoading}=useQuery({queryKey:['station',selectedId],queryFn:()=>api(`/locations/${selectedId}/detail`),enabled:!!selectedId})
 const writable=canWrite(user.role,'locations')
 const select=(row:Row)=>{navigate('/locations/'+row.id);setTab('Overview');setUploadError('')}
 const toggle=(key:number)=>setCollapsed(old=>{const next=new Set(old);next.has(key)?next.delete(key):next.add(key);return next})
 const children=(parent:number)=>locations.filter(l=>l.parent_id===parent)
 const matches=(row:Row):boolean=>(!q||String(row.path).toLowerCase().includes(q.toLowerCase()))&&(status==='all'||row.kind!=='station'||(status==='active'?row.active:!row.active))
 const visible=(row:Row):boolean=>matches(row)&&row.kind==='station'||children(row.id).some(visible)||row.kind!=='station'&&!q&&status==='all'||row.kind!=='station'&&!!q&&matches(row)
 const tree=(row:Row,depth=0)=>{const nested=children(row.id).filter(visible);const Icon=row.kind==='site'?Building2:row.kind==='team'?Users:Monitor;const expanded=!collapsed.has(row.id)||!!q;const count=row.kind==='site'?locations.filter(l=>l.kind==='station'&&children(row.id).some(t=>t.id===l.parent_id)).length:children(row.id).filter(l=>l.kind==='station').length;return <div key={row.id} className="location-tree-group"><div className={'location-tree-row '+(selectedId===row.id?'selected':'')} style={{paddingLeft:8+depth*20}}>{row.kind!=='station'?<button className="tree-toggle" aria-label={`${expanded?'Thu gọn':'Mở rộng'} ${row.name}`} aria-expanded={expanded} onClick={()=>toggle(row.id)}>{expanded?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button>:<span className="tree-spacer"/>}<button className="tree-select" onClick={()=>select(row)}><Icon size={19}/><strong>{row.name}</strong>{row.kind==='station'?<i className={'station-dot '+(row.active?'active':'')}/>:<small>{count} trạm</small>}</button></div>{expanded&&nested.map(child=>tree(child,depth+1))}</div>}
 const upload=async(file:File)=>{setUploading(true);setUploadError('');try{const form=new FormData();form.append('file',file);await api(`/locations/${selectedId}/photo`,{method:'POST',body:form});await queryClient.invalidateQueries()}catch(e){setUploadError((e as Error).message)}finally{setUploading(false)}}
 const network=data?.network||[]
 return <div className="stations-page"><div className="page-heading"><div><h1>Vị trí</h1><p>Tổ chức theo Cơ sở → Bộ phận → Trạm</p></div>{writable&&<div className="relative"><Button onClick={()=>setAddMenu(!addMenu)}><Plus size={18}/>Thêm vị trí<ChevronDown size={15}/></Button>{addMenu&&<div className="popover location-add-menu">{['site','team','station'].map(kind=><button key={kind} onClick={()=>{setAddMenu(false);open({resource:'locations',initial:{kind,active:true,parent_id:kind==='team'&&data?.kind==='site'?data.id:kind==='station'&&data?.kind==='team'?data.id:''}})}}>Thêm {vi(kind)}</button>)}</div>}</div>}</div>
 <div className="location-metrics">{[{name:'Sites',count:locations.filter(l=>l.kind==='site').length,icon:Building2},{name:'Teams',count:locations.filter(l=>l.kind==='team').length,icon:Users},{name:'Stations',count:stations.length,icon:Monitor},{name:'Active Stations',count:stations.filter(l=>l.active).length,status:'active'},{name:'Inactive Stations',count:stations.filter(l=>!l.active).length,status:'inactive'}].map(metric=><div className="location-metric" key={metric.name}>{metric.icon?<span className="metric-icon"><metric.icon size={25}/></span>:<i className={'station-dot '+metric.status}/>}<div><strong>{metric.count}</strong><span>{vi(metric.name)}</span></div></div>)}</div>
 {(metaError||error)&&<div className="error">{(metaError||error)?.message}</div>}
 <div className="location-workspace"><aside className="location-tree"><div className="tree-search"><Search size={17}/><input aria-label="Tìm vị trí" placeholder="Tìm cơ sở, bộ phận hoặc trạm…" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="station-filter" aria-label="Lọc trạng thái trạm" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tất cả trạng thái trạm</option><option value="active">Trạm hoạt động</option><option value="inactive">Trạm ngừng hoạt động</option></select><div className="location-tree-content">{locations.filter(l=>l.kind==='site').filter(visible).map(l=>tree(l))}{!locations.filter(l=>l.kind==='site').some(visible)&&<p className="location-empty">Không có vị trí phù hợp.</p>}</div></aside>
 <section className="location-detail">{isLoading?<div className="loading">Đang tải vị trí…</div>:data?<><header className="location-detail-heading"><div className="location-device-icon">{data.kind==='station'?<Monitor size={40}/>:data.kind==='team'?<Users size={40}/>:<Building2 size={40}/>}</div><div><h2>{data.name}<span className={'station-status '+(data.active?'active':'')}><i/>{data.active?'Hoạt động':'Ngừng hoạt động'}</span></h2><p><LocationPath value={data.path}/></p></div>{writable&&<Button variant="outline" onClick={()=>open({resource:'locations',initial:data,edit:true})}><Pencil size={16}/>Sửa</Button>}</header>
 <div className="location-tabs" role="tablist">{['Overview','Assets','Network','People','History'].map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{vi(t)}{t==='Assets'&&<small>{data.assets.length}</small>}</button>)}</div>
 <div className="location-tab-content" role="tabpanel">{tab==='Overview'?<><section className="location-overview-card"><dl><div><dt>Cơ sở</dt><dd><Building2 size={15}/>{data.site_name||'—'}</dd></div><div><dt>Bộ phận</dt><dd><Users size={15}/>{data.team_name||(data.kind==='team'?data.name:'—')}</dd></div><div><dt>{data.kind==='station'?'Mã trạm':'Tên'}</dt><dd>{data.name}</dd></div><div><dt>Trạng thái</dt><dd><span className={'station-status '+(data.active?'active':'')}><i/>{data.active?'Hoạt động':'Ngừng hoạt động'}</span></dd></div><div><dt>Vị trí thực tế</dt><dd>{data.physical_location||'—'}</dd></div><div><dt>Mô tả</dt><dd>{data.description||'—'}</dd></div></dl><div className="station-photo">{data.photo_url?<img src={`${data.photo_url}?v=${encodeURIComponent(data.updated_at)}`} alt={data.name}/>:<div className="station-photo-empty"><Monitor size={42}/><span>Chưa có ảnh vị trí</span></div>}{writable&&<label className="station-photo-upload"><Camera size={15}/>{uploading?'Đang tải…':data.photo_url?'Thay ảnh':'Thêm ảnh'}<input disabled={uploading} aria-label="Ảnh vị trí" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value=''}}/></label>}</div></section>{uploadError&&<p className="error">{uploadError}</p>}
 <div className="location-info-grid"><section><h3><Network size={17}/>Thông tin mạng</h3>{network.length?<dl><div><dt>Địa chỉ IP</dt><dd>{network[0].address}{network.length>1&&<button className="inline-link" onClick={()=>setTab('Network')}> +{network.length-1} địa chỉ khác</button>}</dd></div><div><dt>Switch</dt><dd>{network[0].switch_name||network[0].switch_label||'—'}</dd></div><div><dt>Cổng switch</dt><dd>{network[0].port||'—'}</dd></div><div><dt>VLAN</dt><dd>{network[0].vlan_label||'—'}</dd></div></dl>:<p className="location-empty">Chưa có kết nối mạng được ghi nhận tại vị trí này.</p>}</section><section><h3><Info size={17}/>Thông tin bổ sung</h3><dl>{[['Department',data.department],['Floor',data.floor],['Area',data.area],['Last Updated',formatDate(data.updated_at)]].map(([name,value])=><div key={name}><dt>{vi(name)}</dt><dd>{value||'—'}</dd></div>)}</dl>{data.updated_by&&<p className="updated-by">bởi {data.updated_by}</p>}</section></div>
 <section className="station-asset-preview"><header><h3><Monitor size={23}/>Tài sản ({data.assets.length})</h3><Button variant="outline" size="sm" onClick={()=>setTab('Assets')}>Xem tất cả</Button></header><div className="table-scroll"><table><thead><tr><th>#</th><th>Loại tài sản</th><th>Model</th><th>Mã tài sản</th><th>Trạng thái</th><th>Ngày cấp phát</th></tr></thead><tbody>{data.assets.slice(0,5).map((a:Row,index:number)=><tr key={a.id}><td>{index+1}</td><td>{a.type_label}</td><td>{a.model}</td><td><Link to={'/assets/'+a.id}>{a.code}</Link></td><td><Badge>{a.status_label}</Badge></td><td>{formatDate(a.since)}</td></tr>)}</tbody></table>{!data.assets.length&&<p className="location-empty"><MapPin size={18}/>Chưa có tài sản tại vị trí này. Xuất kho để cấp thiết bị cho trạm.</p>}</div></section></>:tab==='Assets'?<DataTable rows={data.assets} columns={['type_label','model','code','serial','status_label','assigned_to','since']} onRow={r=>navigate('/assets/'+r.id)}/>:tab==='Network'?<DataTable rows={network} columns={['address','asset_label','mac','hostname','switch_name','port','vlan_label']} onRow={r=>navigate('/ip-addresses/'+r.id)}/>:tab==='People'?<DataTable rows={data.people} columns={['user_label','asset_label','department','created_at','condition_out']}/>:<><h3 className="station-section-heading">Lịch sử vị trí thiết bị</h3><DataTable rows={data.history} columns={['asset_label','from_location_label','location_label','reason','created_at','ended_at']}/><h3 className="station-section-heading">Lịch sử xuất kho cho trạm</h3><DataTable rows={data.stock_movements} columns={configs['inventory-transactions'].columns}/></>}</div></>:<div className="location-empty"><Building2 size={35}/><h2>Chưa có vị trí</h2><p>Thêm cơ sở, sau đó thêm bộ phận và trạm.</p></div>}</section></div></div>
}
