import { vi,eventLabels,statusLabels } from './i18n'
import { useState,useEffect } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { useMutation,useQuery } from '@tanstack/react-query'
import { Link,useParams } from 'react-router-dom'
import { Warehouse as WarehouseIcon,Package,ArrowDownToLine,ArrowUpFromLine,Plus,X,Upload,Monitor,LoaderCircle,Wrench,Check,Cpu,Search,ArrowRight,MapPin,History,SlidersHorizontal,Laptop,Printer } from 'lucide-react'
import { api,canWrite,queryClient,type Row } from './api'
import { Button } from './components/ui/button'
import { deviceName } from './deviceName'
import { HandoverPanel } from './components/Handover'
import { AssetImport } from './components/AssetImport'
import type { EditorState } from './components/Editor'

export function Warehouse({user,open}:{user:Row,open:(s:EditorState)=>void}){
 const {id}=useParams();const [selected,setSelected]=useState(id||'');const [movement,setMovement]=useState<'RECEIVE'|'ISSUE'|null>(null);const [showImport,setShowImport]=useState(false);const [returnAsset,setReturnAsset]=useState(false)
 const [page,setPage]=useState(1);const pageSize=8
 const [tab,setTab]=useState('equipment');const [search,setSearch]=useState('');const [filter,setFilter]=useState('all')
 const {data:meta,error,isLoading}=useQuery({queryKey:['meta'],queryFn:()=>api('/meta')})
 const warehouseId=Number(selected||meta?.warehouses[0]?.id||0);const warehouse=meta?.warehouses.find((r:Row)=>r.id===warehouseId)
 const isComponent=(row:Row)=>['linh kiện','component','components'].includes(String(row.type_label).trim().toLowerCase())
 const assets:Row[]=(meta?.assets||[]).filter((r:Row)=>r.warehouse_id===warehouseId).map((r:Row)=>({...r,type_label:meta?.['asset-types'].find((t:Row)=>t.id===r.type_id)?.name,status_label:statusLabels[r.current_status]||r.current_status}))
 const items:Row[]=(meta?.['inventory-items']||[]).filter((r:Row)=>r.warehouse_id===warehouseId)
 const equipment=assets.filter(r=>!isComponent(r)),components=assets.filter(isComponent),lowItems=items.filter(r=>Number(r.quantity)<Number(r.minimum_stock))
 const writable=canWrite(user.role,'warehouses');const inventoryLink=(section:string)=>`/inventory?tab=${section}&warehouse=${warehouseId}`
 const categoryRows=tab==='consumables'?items:tab==='components'?components:equipment
 const normalizedSearch=search.trim().toLocaleLowerCase('vi')
 const rows=categoryRows.filter(r=>(!normalizedSearch||[r.code,r.name,r.model,r.serial,r.brand,r.category,r.type_label,r.bin_shelf].some(value=>String(value||'').toLocaleLowerCase('vi').includes(normalizedSearch)))&&(filter==='all'||(tab==='consumables'?filter==='available'?Number(r.quantity)>0:Number(r.quantity)<Number(r.minimum_stock):r.current_status===(filter==='available'?'AVAILABLE':'MAINTENANCE'))))
 useEffect(()=>setPage(1),[warehouseId,tab,search,filter])
 const totalPages=Math.max(1,Math.ceil(rows.length/pageSize));const currentPage=Math.min(page,totalPages)
 const categories=[{key:'equipment',name:'Thiết bị',icon:Monitor,count:equipment.length},{key:'components',name:'Linh kiện',icon:Cpu,count:components.length},{key:'consumables',name:'Vật tư',icon:Package,count:items.length}]
 return <div className="warehouse-page it-store-page">
  <div className="page-heading"><div><span className="eyebrow">KHO THIẾT BỊ & VẬT TƯ CNTT</span><h1>IT Store</h1><p>Tiếp nhận, lưu kho và cấp phát cho đội ngũ.</p></div><div className="heading-actions">{writable&&<Button variant="outline" onClick={()=>open({resource:'warehouses'})}><Plus size={16}/>Thêm kho</Button>}<Link className="button button-outline" to={inventoryLink('history')}><History size={16}/>Lịch sử nhập xuất</Link></div></div>
  {error&&<div role="alert" className="error">{error.message}</div>}
  <section className="it-store-hero">
   <div className="it-store-warehouse"><span className="it-store-icon"><WarehouseIcon size={27}/></span><div><label htmlFor="warehouse-select">Kho đang quản lý</label><select id="warehouse-select" disabled={!meta?.warehouses.length} value={warehouseId||''} onChange={e=>{setSelected(e.target.value);setSearch('');setFilter('all')}}>{!warehouseId&&<option value="">Chưa có kho</option>}{meta?.warehouses.map((w:Row)=><option key={w.id} value={w.id}>{w.name}</option>)}</select><p><MapPin size={13}/>{meta?.locations.find((l:Row)=>l.id===warehouse?.location_id)?.path||'Thêm kho để bắt đầu quản lý tồn.'}</p></div>{warehouse&&writable&&<Button variant="ghost" onClick={()=>open({resource:'warehouses',initial:warehouse,edit:true})}>Sửa kho</Button>}</div>
   {writable&&<div className="it-store-actions"><Button disabled={!warehouse} onClick={()=>setMovement('ISSUE')}><ArrowUpFromLine size={16}/>Xuất kho</Button><Button variant="outline" disabled={!warehouse} onClick={()=>open({resource:'assets',initial:{warehouse_id:warehouseId}})}><Plus size={16}/>Nhập thiết bị</Button><Button variant="outline" disabled={!warehouse} onClick={()=>setMovement('RECEIVE')}><Package size={16}/>Nhập vật tư</Button><Button variant="ghost" disabled={!warehouse} onClick={()=>setReturnAsset(true)}><ArrowDownToLine size={16}/>Thu hồi</Button></div>}
  </section>
  <div className="it-store-metrics">{[{name:'Thiết bị trong kho',value:equipment.length,icon:Monitor,tone:'blue'},{name:'Linh kiện trong kho',value:components.length,icon:Cpu,tone:'purple'},{name:'Sẵn sàng cấp phát',value:assets.filter(r=>r.current_status==='AVAILABLE').length,icon:Check,tone:'green'},{name:'Vật tư cần bổ sung',value:lowItems.length,icon:Package,tone:'orange'}].map(metric=><div className="it-store-metric" key={metric.name}><span className={'it-store-metric-icon '+metric.tone}><metric.icon size={21}/></span><div><strong>{metric.value}</strong><span>{metric.name}</span></div></div>)}</div>
  <section className="it-store-catalog panel">
   <header className="it-store-catalog-heading"><div><h2>Hàng trong kho</h2><p>Chọn thiết bị hoặc vật tư để xem chi tiết và cấp phát.</p></div><div>{writable&&<Button size="sm" variant="ghost" disabled={!warehouse} onClick={()=>setShowImport(true)}><Upload size={15}/>Nhập Excel</Button>}<Link to={inventoryLink(tab==='consumables'?'consumables':'assets')}>Xem bảng tồn kho<ArrowRight size={14}/></Link></div></header>
   <div className="it-store-toolbar"><div className="it-store-tabs" role="tablist" aria-label="Nhóm hàng IT Store">{categories.map(category=><button key={category.key} role="tab" id={'store-tab-'+category.key} aria-selected={tab===category.key} aria-controls="store-catalog" className={tab===category.key?'selected':''} onClick={()=>{setTab(category.key);setFilter('all')}}><category.icon size={16}/>{category.name}<span>{category.count}</span></button>)}</div><div className="it-store-filters"><label className="it-store-search"><Search size={16}/><input aria-label="Tìm hàng trong kho" placeholder="Tìm mã, model, serial…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="it-store-filter"><SlidersHorizontal size={15}/><select aria-label="Lọc tình trạng hàng" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tất cả tình trạng</option><option value="available">{tab==='consumables'?'Còn hàng':'Sẵn sàng cấp phát'}</option><option value="attention">{tab==='consumables'?'Cần bổ sung':'Đang bảo trì'}</option></select></label></div></div>
   <div id="store-catalog" role="tabpanel" aria-labelledby={'store-tab-'+tab}>
    {isLoading?<div className="loading">Đang tải hàng trong kho…</div>:!rows.length?<div className="it-store-empty"><Package size={36}/><h3>{search||filter!=='all'?'Không có hàng phù hợp':'Chưa có '+categories.find(c=>c.key===tab)?.name.toLowerCase()+' trong kho'}</h3><p>{search||filter!=='all'?'Thử thay đổi từ khóa hoặc tình trạng.':'Tiếp nhận hàng vào kho để bắt đầu cấp phát.'}</p></div>:<div className="it-store-grid">{rows.slice((currentPage-1)*pageSize,currentPage*pageSize).map(row=>{
     const consumable=tab==='consumables',low=consumable&&Number(row.quantity)<Number(row.minimum_stock),CardIcon=consumable?Package:tab==='components'?Cpu:String(row.type_label).toLowerCase().includes('laptop')?Laptop:['máy in','printer'].includes(String(row.type_label).toLowerCase())?Printer:Monitor
     return <article className="it-store-card" key={row.id}><Link className="it-store-card-main" to={`/${consumable?'inventory-items':'assets'}/${row.id}`}><div className="it-store-card-visual">{!consumable&&row.photo_url?<img src={row.photo_url} alt={row.model||row.code}/>:<CardIcon size={37}/>}<span className={'it-store-stock-badge '+(consumable?low||Number(row.quantity)<=0?'low':'ready':row.current_status==='AVAILABLE'?'ready':row.current_status==='MAINTENANCE'?'repair':'retired')}>{consumable?low?'Cần bổ sung':Number(row.quantity)>0?'Còn hàng':'Hết hàng':row.status_label}</span></div><div className="it-store-card-info"><span className="it-store-card-category">{consumable?row.category:row.type_label}</span><h3>{consumable?row.name:row.model||row.code}</h3><p className="mono">{row.code}</p><p className="it-store-card-description">{consumable?row.bin_shelf?`Kệ / ngăn: ${row.bin_shelf}`:'Chưa ghi nhận kệ / ngăn':`S/N: ${row.serial||'—'}`}</p></div></Link><footer>{consumable?<span className="it-store-quantity"><strong>{Number(row.quantity).toLocaleString('vi-VN')}</strong> {row.unit}<small>Tối thiểu {Number(row.minimum_stock).toLocaleString('vi-VN')}</small></span>:<Link to={'/assets/'+row.id}>Chi tiết<ArrowRight size={13}/></Link>}<QuickStockIssue user={user} warehouseId={warehouseId} compact {...(consumable?{item:row}:{asset:row})}/></footer></article>
    })}</div>}
    {rows.length>0&&<div className="it-store-pagination"><span>{(currentPage-1)*pageSize+1}–{Math.min(currentPage*pageSize,rows.length)} / {rows.length} mục</span><div><Button size="sm" variant="outline" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Trước</Button><span>{currentPage} / {totalPages}</span><Button size="sm" variant="outline" disabled={currentPage===totalPages} onClick={()=>setPage(currentPage+1)}>Sau</Button></div></div>}
   </div>
  </section>
  {movement&&meta&&<StockDialog warehouseId={warehouseId} mode={movement} meta={meta} onClose={()=>setMovement(null)}/>}{returnAsset&&meta&&<StockDialog warehouseId={warehouseId} mode="RECEIVE" assetOnly meta={meta} onClose={()=>setReturnAsset(false)}/>}{showImport&&<AssetImport onClose={()=>setShowImport(false)}/>}
 </div>
}
export function StockDialog({warehouseId:initialWarehouseId,mode,meta,onClose,asset,item,maintenanceMode=false,assetOnly=false,onBack}:{warehouseId:number,mode:'RECEIVE'|'ISSUE',meta:Row,onClose:()=>void,asset?:Row,item?:Row,maintenanceMode?:boolean,assetOnly?:boolean,onBack?:()=>void}){
 const [warehouseId,setWarehouseId]=useState(initialWarehouseId);const fixed=!!(asset||item)
 const issue=mode==='ISSUE';const [openedAt]=useState(()=>new Date());const [initialDate]=useState(()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,19));const [kind,setKind]=useState(asset||maintenanceMode||assetOnly?'asset':item?'consumable':issue?'asset':'consumable');const [itemMode,setItemMode]=useState('existing');const [values,setValues]=useState<Row>({create_maintenance:maintenanceMode,quantity:1,condition:'Tốt',return_status:maintenanceMode?'MAINTENANCE':'AVAILABLE',transaction_date:initialDate,asset_id:asset?.id,item_id:item?.id});const [newItem,setNewItem]=useState<Row>({unit:'cái',category:'Vật tư'})
 const {data:actor}=useQuery({queryKey:['me'],queryFn:()=>api('/auth/me')})
 const [handoverFile,setHandoverFile]=useState<File|null>(null);const [handoverOverrides,setHandoverOverrides]=useState<Row>({})
 const returning=!issue&&kind==='asset';const selectedAsset=meta.assets.find((a:Row)=>a.id===Number(values.asset_id));const formerUser=meta.users.find((u:Row)=>u.id===selectedAsset?.current_assignee_id)
 const selectedWarehouse=meta.warehouses.find((w:Row)=>w.id===warehouseId)
 const handoverInfo:Row={sender_name:returning?formerUser?.name||selectedAsset?.assigned_to||'':actor?.name||'',sender_department:returning?formerUser?.department||'—':'IT Helpdesk',recipient_department:returning?'IT Helpdesk':meta.users.find((u:Row)=>u.id===Number(values.recipient_user_id))?.department||'',place:meta.locations.find((l:Row)=>l.id===selectedWarehouse?.location_id)?.physical_location||meta.locations.find((l:Row)=>l.id===selectedWarehouse?.location_id)?.name||'',purpose:returning?'Thu hồi về kho':'Cấp mới',city:'TP.HCM',...handoverOverrides}
 const handoverFingerprint=JSON.stringify([kind,warehouseId,values,handoverInfo])
 useEffect(()=>setHandoverFile(null),[handoverFingerprint])
 const change=(key:string,value:any)=>{if(mutation.error)mutation.reset();setValues(v=>({...v,[key]:value}))}
 const assets=meta.assets.filter((r:Row)=>issue?r.warehouse_id===warehouseId&&r.current_status==='AVAILABLE':!r.warehouse_id&&!['RETIRED','DISPOSED'].includes(r.current_status))
 const returnStatuses:Row[]=(meta['asset-statuses']||[]).filter((s:Row)=>['AVAILABLE','MAINTENANCE','RETIRED'].includes(s.id))
 const items=meta['inventory-items'].filter((r:Row)=>r.warehouse_id===warehouseId)
 const warehouseLocations=new Set(meta.warehouses.map((w:Row)=>w.location_id))
 const mutation=useMutation({mutationFn:()=>{const payload:Row={transaction_type:mode,warehouse_id:warehouseId,quantity:kind==='asset'?1:Number(values.quantity),transaction_date:((returning||issue&&values.recipient_user_id)?(values.transaction_date===initialDate?openedAt:new Date(values.transaction_date)):values.transaction_date===initialDate?new Date():new Date(values.transaction_date)).toISOString(),condition:values.condition,note:values.note||null};if(kind==='asset'){payload.asset_id=Number(values.asset_id);if(!issue){if(!values.return_status)throw new Error('Vui lòng chọn tình trạng thu hồi.');payload.return_status=values.create_maintenance?'MAINTENANCE':values.return_status;payload.reason=values.reason;if(values.create_maintenance)payload.maintenance={type_id:Number(values.maintenance_type_id),technician_id:Number(values.technician_id),problem:values.problem,diagnosis:values.diagnosis||null,...(values.estimate_hours?{estimate_hours:Number(values.estimate_hours)}:{})};payload.condition=statusLabels[payload.return_status]||vi(returnStatuses.find(s=>s.id===values.return_status)?.name||values.return_status)}}else if(!issue&&itemMode==='new')payload.new_item=newItem;else payload.item_id=Number(values.item_id);if(issue){if(values.recipient_user_id)payload.recipient_user_id=Number(values.recipient_user_id);if(values.recipient_location_id)payload.recipient_location_id=Number(values.recipient_location_id);if(!payload.recipient_user_id&&!payload.recipient_location_id)throw new Error('Vui lòng chọn người hoặc trạm nhận.')}if(returning||issue&&payload.recipient_user_id){if(!handoverFile)throw new Error(returning?'Vui lòng tải biên bản thu hồi đã ký.':'Vui lòng tải biên bản bàn giao đã ký.');const body=new FormData();body.append('payload',JSON.stringify(payload));body.append('handover_info',JSON.stringify(handoverInfo));body.append('file',handoverFile);return api(returning?'/inventory/movement-with-document':'/inventory/issue-with-handover',{method:'POST',body})}return api('/inventory/transactions',{method:'POST',body:JSON.stringify(payload)})},onSuccess:()=>{queryClient.invalidateQueries();onClose()}})
 if(!issue&&kind==='asset'){
  return <Dialog.Root open onOpenChange={v=>{if(!v&&!mutation.isPending)onClose()}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content aria-describedby="return-dialog-description" className="editor quick-maintenance-dialog return-dialog">
   <header className="editor-heading"><div><span className="eyebrow">TIẾP NHẬN VỀ KHO</span><Dialog.Title>Thu hồi</Dialog.Title><p id="return-dialog-description">Kết thúc cấp phát và đưa thiết bị về kho nhận.</p></div><Button variant="ghost" size="icon" aria-label="Đóng" disabled={mutation.isPending} onClick={onClose}><X size={20}/></Button></header>
   <form onSubmit={e=>{e.preventDefault();mutation.mutate()}}><div className="quick-maintenance-body return-body">
    <div className="form-grid quick-maintenance-grid">
     <label><span>Tài sản<b> *</b></span><select required disabled={!!asset||mutation.isPending} value={values.asset_id||''} onChange={e=>change('asset_id',e.target.value)}><option value="">Chọn tài sản</option>{assets.map((a:Row)=><option key={a.id} value={a.id}>{a.code} · {a.serial}</option>)}</select></label>
     <label><span>Kho nhận<b> *</b></span><select required disabled={mutation.isPending} value={warehouseId||''} onChange={e=>setWarehouseId(Number(e.target.value))}><option value="">Chọn kho</option>{meta.warehouses.map((w:Row)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>
     <label><span>Tình trạng thu hồi<b> *</b></span><select required disabled={!!values.create_maintenance||mutation.isPending} value={values.create_maintenance?'MAINTENANCE':values.return_status} onChange={e=>change('return_status',e.target.value)}>{returnStatuses.map(row=><option key={row.id} value={row.id}>{statusLabels[row.id]||vi(row.name)}</option>)}</select></label>
     <label><span>Ngày thu hồi<b> *</b></span><input required step="1" type="datetime-local" disabled={mutation.isPending} value={values.transaction_date} onChange={e=>change('transaction_date',e.target.value)}/></label>
     <label className={values.create_maintenance?'':'wide'}><span>Nguyên nhân thu hồi<b> *</b></span><textarea rows={2} required minLength={3} maxLength={2000} disabled={mutation.isPending} value={values.reason||''} onChange={e=>change('reason',e.target.value)}/></label>
     {values.create_maintenance&&<label><span>Vấn đề<b> *</b></span><textarea rows={2} required disabled={mutation.isPending} value={values.problem||''} onChange={e=>change('problem',e.target.value)}/></label>}
    </div>
    <label className={'return-maintenance-toggle'+(values.create_maintenance?' selected':'')}><span className="return-maintenance-icon"><Wrench size={19}/></span><span className="return-maintenance-copy"><strong>Tạo phiếu bảo trì sau thu hồi</strong><small>{values.create_maintenance?'Thiết bị về kho với tình trạng Đang bảo trì.':'Bật nếu thiết bị cần tiếp tục sửa chữa tại kho.'}</small></span><input type="checkbox" disabled={maintenanceMode||mutation.isPending} checked={!!values.create_maintenance} onChange={e=>change('create_maintenance',e.target.checked)}/></label>
    {values.create_maintenance&&<div className="form-grid quick-maintenance-grid return-maintenance-fields"><label><span>Nhóm vấn đề<b> *</b></span><select required disabled={mutation.isPending} value={values.maintenance_type_id||''} onChange={e=>change('maintenance_type_id',e.target.value)}><option value="">Chọn nhóm vấn đề</option>{meta['master-data'].filter((r:Row)=>r.group==='maintenance_type').map((r:Row)=><option key={r.id} value={r.id}>{vi(r.name)}</option>)}</select></label><label><span>Người xử lý<b> *</b></span><select required disabled={mutation.isPending} value={values.technician_id||''} onChange={e=>change('technician_id',e.target.value)}><option value="">Chọn người xử lý</option>{meta.users.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{!maintenanceMode&&<p className="wide field-help">Đã có phiếu bảo trì mở? Bỏ chọn tạo phiếu để tiếp tục xử lý trên phiếu hiện tại.</p>}</div>}
    <HandoverPanel info={handoverInfo} onChange={(key,value)=>setHandoverOverrides(v=>({...v,[key]:value}))} snapshot={{...handoverInfo,document_kind:'RETURN',recipient_name:actor?.name,transaction_date:values.transaction_date,asset_code:selectedAsset?.code,serial:selectedAsset?.serial,model:selectedAsset?.model,device_name:deviceName(selectedAsset,meta),condition:statusLabels[values.create_maintenance?'MAINTENANCE':values.return_status]||values.return_status,quantity:1,reason:values.reason}} file={handoverFile} onFile={setHandoverFile} pending={mutation.isPending} ready={!!selectedAsset&&!!values.reason?.trim()&&['sender_name','sender_department','place','purpose','city'].every(key=>!!handoverInfo[key]?.trim())}/>
    <details className="quick-maintenance-extra return-extra"><summary>Thông tin bổ sung</summary><div className="form-grid quick-maintenance-grid">{values.create_maintenance&&<label><span>Nguyên nhân / Chẩn đoán</span><textarea rows={2} disabled={mutation.isPending} value={values.diagnosis||''} onChange={e=>change('diagnosis',e.target.value)}/></label>}<label className={values.create_maintenance?'':'wide'}><span>Ghi chú</span><textarea rows={2} disabled={mutation.isPending} value={values.note||''} onChange={e=>change('note',e.target.value)}/></label></div></details>
    {mutation.error&&<p className="error" role="alert">{mutation.error.message}</p>}
   </div><footer className="editor-footer">{onBack&&<Button type="button" variant="ghost" className="return-back" disabled={mutation.isPending} onClick={onBack}>Bảo trì nhanh</Button>}<Button type="button" variant="outline" disabled={mutation.isPending} onClick={onClose}>Hủy</Button><Button type="submit" disabled={mutation.isPending||!handoverFile}>{mutation.isPending?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {values.create_maintenance?'Thu hồi và tạo bảo trì':'Xác nhận thu hồi'}</Button></footer></form>
  </Dialog.Content></Dialog.Portal></Dialog.Root>
 }
 const currentItem=kind==='consumable'?items.find((row:Row)=>row.id===Number(values.item_id)):undefined
 const currentAsset=kind==='asset'?assets.find((row:Row)=>row.id===Number(values.asset_id)):undefined
 const input=(key:string,name:string,required=false,type='text')=><label><span>{name}{required&&<b> *</b>}</span><input required={required} minLength={key==='condition'?2:undefined} type={type} disabled={mutation.isPending} value={values[key]||''} onChange={e=>change(key,e.target.value)}/></label>
 return <Dialog.Root open onOpenChange={v=>{if(!v&&!mutation.isPending)onClose()}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content aria-describedby="stock-movement-description" className={"editor quick-maintenance-dialog store-movement-dialog"+(issue&&values.recipient_user_id?" stock-handover-dialog":"")}>
  <header className="editor-heading"><div><span className="eyebrow">IT STORE</span><Dialog.Title>{issue?'Xuất kho':'Nhập vật tư'}</Dialog.Title><p id="stock-movement-description">{issue?'Cấp phát thiết bị hoặc vật tư cho người dùng và trạm.':'Bổ sung vật tư mới hoặc nhập thêm hàng đã có.'}</p></div><Button variant="ghost" size="icon" aria-label="Đóng" disabled={mutation.isPending} onClick={onClose}><X size={20}/></Button></header>
  <form onSubmit={e=>{e.preventDefault();mutation.mutate()}}><div className="quick-maintenance-body">
   {issue&&!fixed&&<fieldset className="store-kind-picker" disabled={mutation.isPending}><legend>Loại hàng</legend><label className={kind==='asset'?'selected':''}><input type="radio" name="stock-kind" checked={kind==='asset'} onChange={()=>setKind('asset')}/><Monitor size={17}/>Thiết bị / Linh kiện</label><label className={kind==='consumable'?'selected':''}><input type="radio" name="stock-kind" checked={kind==='consumable'} onChange={()=>setKind('consumable')}/><Package size={17}/>Vật tư</label></fieldset>}
   <div className="form-grid quick-maintenance-grid">
    <label><span>Kho<b> *</b></span><select required disabled={fixed&&issue||mutation.isPending} value={warehouseId||''} onChange={e=>{setWarehouseId(Number(e.target.value));setValues(v=>({...v,asset_id:asset?.id||'',item_id:item?.id||''}))}}><option value="">Chọn kho</option>{meta.warehouses.map((w:Row)=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>
    <label><span>{issue?'Ngày xuất':'Ngày nhập'}<b> *</b></span><input required step="1" type="datetime-local" disabled={mutation.isPending} value={values.transaction_date} onChange={e=>change('transaction_date',e.target.value)}/></label>
    {!issue&&!item&&<label className="wide"><span>Nhập vật tư</span><select disabled={mutation.isPending} value={itemMode} onChange={e=>setItemMode(e.target.value)}><option value="existing">Nhập vật tư đã có</option><option value="new">Tạo và nhập vật tư mới</option></select></label>}
    {kind==='asset'?<label className="wide"><span>Tài sản<b> *</b></span><select required disabled={!!asset||mutation.isPending} value={values.asset_id||''} onChange={e=>change('asset_id',e.target.value)}><option value="">Chọn thiết bị sẵn sàng</option>{assets.map((a:Row)=><option key={a.id} value={a.id}>{a.code} · {a.model||a.serial}</option>)}</select></label>:!issue&&itemMode==='new'?<>{['code','name','category','unit'].map(key=><label key={key}><span>{({code:'Mã',name:'Tên',category:'Phân loại',unit:'Đơn vị'} as Row)[key]}<b> *</b></span><input required disabled={mutation.isPending} value={newItem[key]||''} onChange={e=>setNewItem(v=>({...v,[key]:e.target.value}))}/></label>)}</>:<label className="wide"><span>Vật tư<b> *</b></span><select required disabled={!!item||mutation.isPending} value={values.item_id||''} onChange={e=>change('item_id',e.target.value)}><option value="">Chọn vật tư</option>{items.map((r:Row)=><option key={r.id} value={r.id}>{r.code} · {r.name} ({r.quantity} {r.unit})</option>)}</select></label>}
    {kind==='consumable'&&<label><span>Số lượng<b> *</b></span><input required type="number" min="0.001" step="0.001" disabled={mutation.isPending} value={values.quantity} onChange={e=>change('quantity',e.target.value)}/></label>}
    {input('condition','Tình trạng',true)}
   </div>
   {(currentItem||currentAsset)&&<div className="store-form-notice"><Package size={19}/><span>{currentItem?`Tồn hiện tại: ${Number(currentItem.quantity).toLocaleString('vi-VN')} ${currentItem.unit}`:currentAsset.model||currentAsset.code}<small>{currentItem?currentItem.bin_shelf?`Kệ / ngăn: ${currentItem.bin_shelf}`:'Vật tư được quản lý theo số lượng.':`S/N: ${currentAsset.serial||'—'} · 1 thiết bị`}</small></span></div>}
   {issue&&<section className="store-recipient-section"><header><h3>Người / Trạm nhận</h3><p>Chọn ít nhất một người hoặc trạm. Có thể chọn cả hai.</p></header><div className="form-grid quick-maintenance-grid"><label><span>Người nhận</span><select disabled={mutation.isPending} value={values.recipient_user_id||''} onChange={e=>change('recipient_user_id',e.target.value)}><option value="">Chọn người dùng</option>{meta.users.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label><span>Trạm nhận</span><select disabled={mutation.isPending} value={values.recipient_location_id||''} onChange={e=>change('recipient_location_id',e.target.value)}><option value="">Chọn trạm</option>{meta.locations.filter((r:Row)=>r.kind==='station'&&r.active&&!warehouseLocations.has(r.id)).map((r:Row)=><option key={r.id} value={r.id}>{r.path||r.name}</option>)}</select></label></div></section>}
   {issue&&values.recipient_user_id&&<HandoverPanel info={handoverInfo} onChange={(key,value)=>setHandoverOverrides(v=>({...v,[key]:value}))} snapshot={{...handoverInfo,recipient_name:meta.users.find((u:Row)=>u.id===Number(values.recipient_user_id))?.name,transaction_date:values.transaction_date,asset_code:(kind==='asset'?currentAsset:currentItem)?.code,serial:currentAsset?.serial,model:currentAsset?.model,device_name:kind==='asset'?deviceName(currentAsset,meta):currentItem?.name,condition:values.condition,quantity:kind==='asset'?1:values.quantity}} file={handoverFile} onFile={setHandoverFile} pending={mutation.isPending} ready={!!(kind==='asset'?currentAsset:currentItem)&&!!values.condition?.trim()&&['sender_name','sender_department','place','purpose','city'].every(key=>!!handoverInfo[key]?.trim())&&Number(values.quantity)>0}/>}
   <details className="quick-maintenance-extra"><summary>Ghi chú</summary><div className="form-grid quick-maintenance-grid"><label className="wide"><span>Ghi chú</span><textarea rows={2} disabled={mutation.isPending} value={values.note||''} onChange={e=>change('note',e.target.value)}/></label></div></details>
   {mutation.error&&<p className="error" role="alert">{mutation.error.message}</p>}
  </div><footer className="editor-footer"><Button type="button" variant="outline" disabled={mutation.isPending} onClick={onClose}>Hủy</Button><Button type="submit" disabled={mutation.isPending||!!(issue&&values.recipient_user_id&&!handoverFile)}>{mutation.isPending?<LoaderCircle className="spin" size={16}/>:issue?<ArrowUpFromLine size={16}/>:<ArrowDownToLine size={16}/>} {issue?'Xác nhận xuất kho':'Xác nhận nhập kho'}</Button></footer></form>
 </Dialog.Content></Dialog.Portal></Dialog.Root>

}

export function QuickStockIssue({user,asset,item,warehouseId=0,compact=false}:{user:Row,asset?:Row,item?:Row,warehouseId?:number,compact?:boolean}){
 const [show,setShow]=useState(false)
 const {data:meta}=useQuery({queryKey:['meta'],queryFn:()=>api('/meta')})
 if(!canWrite(user.role,'warehouses')||asset&&(!asset.warehouse_id||asset.current_status!=='AVAILABLE')||item&&item.quantity<=0)return null
 const id=asset?.warehouse_id||item?.warehouse_id||warehouseId||meta?.warehouses[0]?.id||0
 return <><Button size={compact?'sm':'default'} variant={compact?'outline':'default'} disabled={!meta||!id} onClick={()=>setShow(true)}><ArrowUpFromLine size={15}/>Xuất kho</Button>{show&&meta&&<StockDialog warehouseId={id} mode="ISSUE" meta={meta} asset={asset} item={item} onClose={()=>setShow(false)}/>}</>
}
