import { vi,eventLabels,statusLabels } from './i18n'
import { useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { useMutation,useQuery } from '@tanstack/react-query'
import { Link,useParams } from 'react-router-dom'
import { Warehouse as WarehouseIcon,Package,ArrowDownToLine,ArrowUpFromLine,Plus,X,Upload,Monitor,LoaderCircle } from 'lucide-react'
import { api,canWrite,queryClient,type Row } from './api'
import { Button } from './components/ui/button'
import { AssetImport } from './components/AssetImport'
import type { EditorState } from './components/Editor'

export function Warehouse({user,open}:{user:Row,open:(s:EditorState)=>void}){
 const {id}=useParams();const [selected,setSelected]=useState(id||'');const [movement,setMovement]=useState<'RECEIVE'|'ISSUE'|null>(null);const [showImport,setShowImport]=useState(false)
 const {data:meta,error}=useQuery({queryKey:['meta'],queryFn:()=>api('/meta')})
 const warehouseId=Number(selected||meta?.warehouses[0]?.id||0);const warehouse=meta?.warehouses.find((r:Row)=>r.id===warehouseId)
 const assets=(meta?.assets||[]).filter((r:Row)=>r.warehouse_id===warehouseId).map((r:Row)=>({...r,type_label:meta['asset-types'].find((t:Row)=>t.id===r.type_id)?.name,status_label:meta['master-data'].find((t:Row)=>t.id===r.status_id)?.name}))
 const items=(meta?.['inventory-items']||[]).filter((r:Row)=>r.warehouse_id===warehouseId)
 const writable=canWrite(user.role,'warehouses')
 return <div className="warehouse-page"><div className="page-heading"><div><span className="eyebrow">TỒN KHO VÀ BÀN GIAO</span><h1>Kho</h1><p>Nhập thiết bị, vật tư và cấp phát cho người dùng hoặc trạm.</p></div>{writable&&<Button variant="outline" onClick={()=>open({resource:'warehouses'})}><Plus size={16}/>Thêm kho</Button>}</div>
 {error&&<div className="error">{error.message}</div>}
 <div className="warehouse-selector panel"><WarehouseIcon size={28}/><div><label htmlFor="warehouse-select">Kho hiện tại</label><select id="warehouse-select" value={warehouseId||''} onChange={e=>{setSelected(e.target.value)}}>{!warehouseId&&<option value="">Chọn kho</option>}{meta?.warehouses.map((w:Row)=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></div><p>{meta?.locations.find((l:Row)=>l.id===warehouse?.location_id)?.path||'Tạo kho để bắt đầu nhập hàng.'}</p>{warehouse&&writable&&<Button variant="ghost" onClick={()=>open({resource:'warehouses',initial:warehouse,edit:true})}>Sửa kho</Button>}</div>
 <div className="stock-metrics"><div className="panel"><Monitor/><strong>{assets.length}</strong><span>Tài sản trong kho</span></div><div className="panel"><Package/><strong>{items.length}</strong><span>Loại vật tư</span></div><div className="panel"><ArrowDownToLine/><strong>{items.filter((r:Row)=>r.quantity<r.minimum_stock).length}</strong><span>Vật tư dưới mức tối thiểu</span></div></div>
 {writable&&<div className="warehouse-actions"><section className="panel"><div><ArrowDownToLine/><h2>Nhập kho</h2></div><p>Mỗi lần nhập ghi nhận kho, số lượng và ngày nhập.</p><div><Button disabled={!warehouse} onClick={()=>open({resource:'assets',initial:{warehouse_id:warehouseId}})}><Plus size={16}/>Nhập tài sản</Button><Button disabled={!warehouse} variant="outline" onClick={()=>setMovement('RECEIVE')}><Package size={16}/>Nhập vật tư / thu hồi</Button><Button variant="ghost" onClick={()=>setShowImport(true)}><Upload size={16}/>Nhập Excel</Button></div></section><section className="panel"><div><ArrowUpFromLine/><h2>Xuất kho</h2></div><p>Chọn người hoặc trạm nhận. Ngày xuất được lưu trong lịch sử kho.</p><Button disabled={!warehouse} onClick={()=>setMovement('ISSUE')}><ArrowUpFromLine size={16}/>Xuất kho</Button></section></div>}
 <div className="warehouse-destinations"><Link className="button button-outline" to={'/inventory?tab=assets'+(warehouseId?'&warehouse='+warehouseId:'')}>Xem tài sản và vật tư</Link><Link className="button button-outline" to={'/inventory?tab=history'+(warehouseId?'&warehouse='+warehouseId:'')}>Xem lịch sử nhập xuất</Link></div>
 {movement&&meta&&<StockDialog warehouseId={warehouseId} mode={movement} meta={meta} onClose={()=>setMovement(null)}/>}{showImport&&<AssetImport onClose={()=>setShowImport(false)}/>}
 </div>
}
export function StockDialog({warehouseId:initialWarehouseId,mode,meta,onClose,asset,item}:{warehouseId:number,mode:'RECEIVE'|'ISSUE',meta:Row,onClose:()=>void,asset?:Row,item?:Row}){
 const [warehouseId,setWarehouseId]=useState(initialWarehouseId);const fixed=!!(asset||item)
 const issue=mode==='ISSUE';const [initialDate]=useState(()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,19));const [kind,setKind]=useState(asset?'asset':item?'consumable':issue?'asset':'consumable');const [itemMode,setItemMode]=useState('existing');const [values,setValues]=useState<Row>({quantity:1,condition:'Tốt',transaction_date:initialDate,asset_id:asset?.id,item_id:item?.id});const [newItem,setNewItem]=useState<Row>({unit:'cái',category:'Vật tư'})
 const change=(key:string,value:any)=>setValues(v=>({...v,[key]:value}))
 const assets=meta.assets.filter((r:Row)=>issue?r.warehouse_id===warehouseId&&r.current_status==='AVAILABLE':!r.warehouse_id&&r.current_status!=='RETIRED')
 const items=meta['inventory-items'].filter((r:Row)=>r.warehouse_id===warehouseId)
 const warehouseLocations=new Set(meta.warehouses.map((w:Row)=>w.location_id))
 const mutation=useMutation({mutationFn:()=>{const payload:Row={transaction_type:mode,warehouse_id:warehouseId,quantity:kind==='asset'?1:Number(values.quantity),transaction_date:(values.transaction_date===initialDate?new Date():new Date(values.transaction_date)).toISOString(),condition:values.condition,note:values.note||null};if(kind==='asset')payload.asset_id=Number(values.asset_id);else if(!issue&&itemMode==='new')payload.new_item=newItem;else payload.item_id=Number(values.item_id);if(issue){if(values.recipient_user_id)payload.recipient_user_id=Number(values.recipient_user_id);if(values.recipient_location_id)payload.recipient_location_id=Number(values.recipient_location_id);if(!payload.recipient_user_id&&!payload.recipient_location_id)throw new Error('Vui lòng chọn người hoặc trạm nhận.')}return api('/inventory/transactions',{method:'POST',body:JSON.stringify(payload)})},onSuccess:()=>{queryClient.invalidateQueries();onClose()}})
 return <Dialog.Root open onOpenChange={v=>{if(!v&&!mutation.isPending)onClose()}}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="editor stock-dialog"><div className="editor-heading"><div><span className="eyebrow">NHẬP XUẤT KHO</span><Dialog.Title>{issue?'Xuất kho':'Nhập kho'}</Dialog.Title><Dialog.Description>{issue?'Cấp phát tài sản hoặc vật tư cho người dùng / trạm.':'Nhập vật tư hoặc thu hồi tài sản về kho.'}</Dialog.Description></div><Button variant="ghost" size="icon" aria-label="Đóng" disabled={mutation.isPending} onClick={onClose}><X size={20}/></Button></div><form onSubmit={e=>{e.preventDefault();mutation.mutate()}}><div className="form-grid">
 <label className="wide">Kho *<select required disabled={fixed&&issue} value={warehouseId||''} onChange={e=>{setWarehouseId(Number(e.target.value));setValues(v=>({...v,asset_id:asset?.id||'',item_id:item?.id||''}))}}><option value="">Chọn kho</option>{meta.warehouses.map((w:Row)=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></label>
 <label className="wide">Loại hàng<select disabled={fixed} value={kind} onChange={e=>setKind(e.target.value)}><option value="asset">Tài sản có số sê-ri{!issue?' · thu hồi về kho':''}</option><option value="consumable">Vật tư</option></select></label>
 {kind==='asset'?<label className="wide">Tài sản *<select required disabled={!!asset} value={values.asset_id||''} onChange={e=>change('asset_id',e.target.value)}><option value="">Chọn tài sản</option>{assets.map((a:Row)=><option key={a.id} value={a.id}>{a.code} · {a.serial}</option>)}</select></label>:<>{!issue&&<label className="wide">Nhập vật tư<select value={itemMode} onChange={e=>setItemMode(e.target.value)}><option value="existing">Nhập vật tư đã có</option><option value="new">Tạo và nhập vật tư mới</option></select></label>}{!issue&&itemMode==='new'?['code','name','category','unit'].map(key=><label key={key}>{({code:'Mã',name:'Tên',category:'Phân loại',unit:'Đơn vị'} as Record<string,string>)[key]} *<input required value={newItem[key]||''} onChange={e=>setNewItem({...newItem,[key]:e.target.value})}/></label>):<label className="wide">Vật tư *<select required disabled={!!item} value={values.item_id||''} onChange={e=>change('item_id',e.target.value)}><option value="">Chọn vật tư</option>{items.map((r:Row)=><option key={r.id} value={r.id}>{r.code} · {r.name} ({r.quantity} {r.unit})</option>)}</select></label>}<label>Số lượng *<input required type="number" min="0.001" step="0.001" value={values.quantity} onChange={e=>change('quantity',e.target.value)}/></label></>}
 <label>{issue?'Ngày xuất':'Ngày nhập'} *<input required step="1" type="datetime-local" value={values.transaction_date} onChange={e=>change('transaction_date',e.target.value)}/></label>
 {issue&&<><p className="wide field-help">Chọn ít nhất một người hoặc trạm nhận. Có thể chọn cả hai.</p><label>Người nhận<select value={values.recipient_user_id||''} onChange={e=>change('recipient_user_id',e.target.value)}><option value="">Chọn người dùng</option>{meta.users.map((r:Row)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Trạm nhận<select value={values.recipient_location_id||''} onChange={e=>change('recipient_location_id',e.target.value)}><option value="">Chọn trạm</option>{meta.locations.filter((r:Row)=>r.kind==='station'&&r.active&&!warehouseLocations.has(r.id)).map((r:Row)=><option key={r.id} value={r.id}>{r.path}</option>)}</select></label></>}
 <label className="wide">Tình trạng *<input required minLength={2} value={values.condition} onChange={e=>change('condition',e.target.value)}/></label><label className="wide">Ghi chú<textarea value={values.note||''} onChange={e=>change('note',e.target.value)}/></label></div>{mutation.error&&<p className="error" role="alert">{mutation.error.message}</p>}<footer className="editor-footer"><Button type="button" variant="outline" disabled={mutation.isPending} onClick={onClose}>Hủy</Button><Button disabled={mutation.isPending}>{mutation.isPending&&<LoaderCircle className="spin" size={16}/>}Xác nhận {issue?'xuất kho':'nhập kho'}</Button></footer></form></Dialog.Content></Dialog.Portal></Dialog.Root>
}

export function QuickStockIssue({user,asset,item,warehouseId=0,compact=false}:{user:Row,asset?:Row,item?:Row,warehouseId?:number,compact?:boolean}){
 const [show,setShow]=useState(false)
 const {data:meta}=useQuery({queryKey:['meta'],queryFn:()=>api('/meta')})
 if(!canWrite(user.role,'warehouses')||asset&&!asset.warehouse_id||item&&item.quantity<=0)return null
 const id=asset?.warehouse_id||item?.warehouse_id||warehouseId||meta?.warehouses[0]?.id||0
 return <><Button size={compact?'sm':'default'} variant={compact?'outline':'default'} disabled={!meta||!id} onClick={()=>setShow(true)}><ArrowUpFromLine size={15}/>Xuất kho</Button>{show&&meta&&<StockDialog warehouseId={id} mode="ISSUE" meta={meta} asset={asset} item={item} onClose={()=>setShow(false)}/>}</>
}
